;  Assembly code generated by mikroVirtualMachine - V. 5.0.0.3
;  Date/Time: 17/09/2020 15:13:14
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2804			GOTO	_main
$06A0	$	_mul_32x32_u:
$06A0	$1303			BCF	STATUS, RP1
$06A1	$1283			BCF	STATUS, RP0
;math.ppas,1570 :: 		
;math.ppas,1578 :: 		
$06A2	$3022			MOVLW	34
;math.ppas,1579 :: 		
$06A3	$00FC			MOVWF	STACK_12
;math.ppas,1580 :: 		
$06A4	$01F8			CLRF	STACK_8
;math.ppas,1581 :: 		
$06A5	$01F9			CLRF	STACK_9
;math.ppas,1582 :: 		
$06A6	$01FA			CLRF	STACK_10
;math.ppas,1584 :: 		
$06A7	$01FB			CLRF	STACK_11
;math.ppas,1588 :: 		
$06A8	$	_NEXT:
;math.ppas,1589 :: 		
$06A8	$03FC			DECF	STACK_12, F
;math.ppas,1590 :: 		
$06A9	$1903			BTFSC	STATUS, Z
;math.ppas,1591 :: 		
$06AA	$2ED6			GOTO	_EXIT2
;math.ppas,1593 :: 		
$06AB	$1003			BCF	STATUS, C
;math.ppas,1602 :: 		
$06AC	$	_LOOP:
;math.ppas,1603 :: 		
$06AC	$0CFB			RRF	STACK_11, F
;math.ppas,1604 :: 		
$06AD	$0CFA			RRF	STACK_10, F
;math.ppas,1605 :: 		
$06AE	$0CF9			RRF	STACK_9, F
;math.ppas,1606 :: 		
$06AF	$0CF8			RRF	STACK_8, F
;math.ppas,1607 :: 		
$06B0	$0CF3			RRF	STACK_3, F
;math.ppas,1608 :: 		
$06B1	$0CF2			RRF	STACK_2, F
;math.ppas,1609 :: 		
$06B2	$0CF1			RRF	STACK_1, F
;math.ppas,1614 :: 		
$06B3	$0CF0			RRF	STACK_0, F
;math.ppas,1615 :: 		
$06B4	$1C03			BTFSS	STATUS, C
;math.ppas,1616 :: 		
$06B5	$2EA8			GOTO	_NEXT
;math.ppas,1617 :: 		
$06B6	$03FC			DECF	STACK_12, F
;math.ppas,1618 :: 		
$06B7	$1903			BTFSC	STATUS, Z
;math.ppas,1625 :: 		
$06B8	$2EC8			GOTO	_EXIT1
;math.ppas,1626 :: 		
$06B9	$0874			MOVF	STACK_4, W
;math.ppas,1627 :: 		
$06BA	$07F8			ADDWF	STACK_8, F
;math.ppas,1628 :: 		
$06BB	$0875			MOVF	STACK_5, W
;math.ppas,1629 :: 		
$06BC	$1803			BTFSC	STATUS, C
;math.ppas,1630 :: 		
$06BD	$0F75			INCFSZ	STACK_5, W
;math.ppas,1631 :: 		
$06BE	$07F9			ADDWF	STACK_9, F
;math.ppas,1632 :: 		
$06BF	$0876			MOVF	STACK_6, W
;math.ppas,1633 :: 		
$06C0	$1803			BTFSC	STATUS, C
;math.ppas,1634 :: 		
$06C1	$0F76			INCFSZ	STACK_6, W
;math.ppas,1635 :: 		
$06C2	$07FA			ADDWF	STACK_10, F
;math.ppas,1636 :: 		
$06C3	$0877			MOVF	STACK_7, W
;math.ppas,1637 :: 		
$06C4	$1803			BTFSC	STATUS, C
;math.ppas,1638 :: 		
$06C5	$0F77			INCFSZ	STACK_7, W
;math.ppas,1640 :: 		
$06C6	$07FB			ADDWF	STACK_11, F
;math.ppas,1642 :: 		
$06C7	$2EAC			GOTO	_LOOP
;math.ppas,1647 :: 		
$06C8	$	_EXIT1:
;math.ppas,1648 :: 		
$06C8	$0874			MOVF	STACK_4, W
;math.ppas,1649 :: 		
$06C9	$07F8			ADDWF	STACK_8, F
;math.ppas,1650 :: 		
$06CA	$0875			MOVF	STACK_5, W
;math.ppas,1651 :: 		
$06CB	$1803			BTFSC	STATUS, C
;math.ppas,1652 :: 		
$06CC	$0F75			INCFSZ	STACK_5, W
;math.ppas,1653 :: 		
$06CD	$07F9			ADDWF	STACK_9, F
;math.ppas,1654 :: 		
$06CE	$0876			MOVF	STACK_6, W
;math.ppas,1655 :: 		
$06CF	$1803			BTFSC	STATUS, C
;math.ppas,1656 :: 		
$06D0	$0F76			INCFSZ	STACK_6, W
;math.ppas,1657 :: 		
$06D1	$07FA			ADDWF	STACK_10, F
;math.ppas,1658 :: 		
$06D2	$0877			MOVF	STACK_7, W
;math.ppas,1659 :: 		
$06D3	$1803			BTFSC	STATUS, C
;math.ppas,1660 :: 		
$06D4	$0F77			INCFSZ	STACK_7, W
;math.ppas,1663 :: 		
$06D5	$07FB			ADDWF	STACK_11, F
;math.ppas,1664 :: 		
$06D6	$	_EXIT2:
;math.ppas,1665 :: 		
$06D6	$	math_L_13:
;math.ppas,1666 :: 		
$06D6	$0008			RETURN
$02B5	$	_sdiv3232l:
$02B5	$1303			BCF	STATUS, RP1
$02B6	$1283			BCF	STATUS, RP0
;math.ppas,539 :: 		
;math.ppas,541 :: 		
$02B7	$0874			MOVF	STACK_4, W
;math.ppas,542 :: 		
$02B8	$02F8			SUBWF	STACK_8, F
;math.ppas,543 :: 		
$02B9	$0875			MOVF	STACK_5, W
;math.ppas,544 :: 		
$02BA	$1C03			BTFSS	STATUS, C
;math.ppas,545 :: 		
$02BB	$0F75			INCFSZ	STACK_5, W
;math.ppas,546 :: 		
$02BC	$02F9			SUBWF	STACK_9, F
;math.ppas,547 :: 		
$02BD	$0876			MOVF	STACK_6, W
;math.ppas,548 :: 		
$02BE	$1C03			BTFSS	STATUS, C
;math.ppas,549 :: 		
$02BF	$0F76			INCFSZ	STACK_6, W
;math.ppas,550 :: 		
$02C0	$02FA			SUBWF	STACK_10, F
;math.ppas,551 :: 		
$02C1	$0877			MOVF	STACK_7, W
;math.ppas,552 :: 		
$02C2	$1C03			BTFSS	STATUS, C
;math.ppas,553 :: 		
$02C3	$0F77			INCFSZ	STACK_7, W
;math.ppas,554 :: 		
$02C4	$02FB			SUBWF	STACK_11, F
;math.ppas,556 :: 		
$02C5	$0DF3			RLF	STACK_3, F
;math.ppas,557 :: 		
$02C6	$3007			MOVLW	7
;math.ppas,559 :: 		
$02C7	$00FC			MOVWF	STACK_12
;math.ppas,560 :: 		
$02C8	$	LOOPS3232A:
;math.ppas,561 :: 		
$02C8	$0D73			RLF	STACK_3, W
;math.ppas,562 :: 		
$02C9	$0DF8			RLF	STACK_8, F
;math.ppas,563 :: 		
$02CA	$0DF9			RLF	STACK_9, F
;math.ppas,564 :: 		
$02CB	$0DFA			RLF	STACK_10, F
;math.ppas,565 :: 		
$02CC	$0DFB			RLF	STACK_11, F
;math.ppas,566 :: 		
$02CD	$0874			MOVF	STACK_4, W
;math.ppas,567 :: 		
$02CE	$1C73			BTFSS	STACK_3, 0
;math.ppas,569 :: 		
$02CF	$2ADE			GOTO	SADD22LA
;math.ppas,570 :: 		
$02D0	$02F8			SUBWF	STACK_8, F
;math.ppas,571 :: 		
$02D1	$0875			MOVF	STACK_5, W
;math.ppas,572 :: 		
$02D2	$1C03			BTFSS	STATUS, C
;math.ppas,573 :: 		
$02D3	$0F75			INCFSZ	STACK_5, W
;math.ppas,574 :: 		
$02D4	$02F9			SUBWF	STACK_9, F
;math.ppas,575 :: 		
$02D5	$0876			MOVF	STACK_6, W
;math.ppas,576 :: 		
$02D6	$1C03			BTFSS	STATUS, C
;math.ppas,577 :: 		
$02D7	$0F76			INCFSZ	STACK_6, W
;math.ppas,578 :: 		
$02D8	$02FA			SUBWF	STACK_10, F
;math.ppas,579 :: 		
$02D9	$0877			MOVF	STACK_7, W
;math.ppas,580 :: 		
$02DA	$1C03			BTFSS	STATUS, C
;math.ppas,581 :: 		
$02DB	$0F77			INCFSZ	STACK_7, W
;math.ppas,582 :: 		
$02DC	$02FB			SUBWF	STACK_11, F
;math.ppas,584 :: 		
$02DD	$2AEB			GOTO	SOK22LA
;math.ppas,585 :: 		
$02DE	$	SADD22LA:
;math.ppas,586 :: 		
$02DE	$07F8			ADDWF	STACK_8, F
;math.ppas,587 :: 		
$02DF	$0875			MOVF	STACK_5, W
;math.ppas,588 :: 		
$02E0	$1803			BTFSC	STATUS, C
;math.ppas,589 :: 		
$02E1	$0F75			INCFSZ	STACK_5, W
;math.ppas,590 :: 		
$02E2	$07F9			ADDWF	STACK_9, F
;math.ppas,591 :: 		
$02E3	$0876			MOVF	STACK_6, W
;math.ppas,592 :: 		
$02E4	$1803			BTFSC	STATUS, C
;math.ppas,593 :: 		
$02E5	$0F76			INCFSZ	STACK_6, W
;math.ppas,594 :: 		
$02E6	$07FA			ADDWF	STACK_10, F
;math.ppas,595 :: 		
$02E7	$0877			MOVF	STACK_7, W
;math.ppas,596 :: 		
$02E8	$1803			BTFSC	STATUS, C
;math.ppas,597 :: 		
$02E9	$0F77			INCFSZ	STACK_7, W
;math.ppas,599 :: 		
$02EA	$07FB			ADDWF	STACK_11, F
;math.ppas,600 :: 		
$02EB	$	SOK22LA:
;math.ppas,602 :: 		
$02EB	$0DF3			RLF	STACK_3, F
;math.ppas,603 :: 		
$02EC	$0BFC			DECFSZ	STACK_12, F
;math.ppas,605 :: 		
$02ED	$2AC8			GOTO	LOOPS3232A
;math.ppas,606 :: 		
$02EE	$0D72			RLF	STACK_2, W
;math.ppas,607 :: 		
$02EF	$0DF8			RLF	STACK_8, F
;math.ppas,608 :: 		
$02F0	$0DF9			RLF	STACK_9, F
;math.ppas,609 :: 		
$02F1	$0DFA			RLF	STACK_10, F
;math.ppas,610 :: 		
$02F2	$0DFB			RLF	STACK_11, F
;math.ppas,611 :: 		
$02F3	$0874			MOVF	STACK_4, W
;math.ppas,612 :: 		
$02F4	$1C73			BTFSS	STACK_3, 0
;math.ppas,614 :: 		
$02F5	$2B04			GOTO	SADD22L8
;math.ppas,615 :: 		
$02F6	$02F8			SUBWF	STACK_8, F
;math.ppas,616 :: 		
$02F7	$0875			MOVF	STACK_5, W
;math.ppas,617 :: 		
$02F8	$1C03			BTFSS	STATUS, C
;math.ppas,618 :: 		
$02F9	$0F75			INCFSZ	STACK_5, W
;math.ppas,619 :: 		
$02FA	$02F9			SUBWF	STACK_9, F
;math.ppas,620 :: 		
$02FB	$0876			MOVF	STACK_6, W
;math.ppas,621 :: 		
$02FC	$1C03			BTFSS	STATUS, C
;math.ppas,622 :: 		
$02FD	$0F76			INCFSZ	STACK_6, W
;math.ppas,623 :: 		
$02FE	$02FA			SUBWF	STACK_10, F
;math.ppas,624 :: 		
$02FF	$0877			MOVF	STACK_7, W
;math.ppas,625 :: 		
$0300	$1C03			BTFSS	STATUS, C
;math.ppas,626 :: 		
$0301	$0F77			INCFSZ	STACK_7, W
;math.ppas,627 :: 		
$0302	$02FB			SUBWF	STACK_11, F
;math.ppas,629 :: 		
$0303	$2B11			GOTO	SOK22L8
;math.ppas,630 :: 		
$0304	$	SADD22L8:
;math.ppas,631 :: 		
$0304	$07F8			ADDWF	STACK_8, F
;math.ppas,632 :: 		
$0305	$0875			MOVF	STACK_5, W
;math.ppas,633 :: 		
$0306	$1803			BTFSC	STATUS, C
;math.ppas,634 :: 		
$0307	$0F75			INCFSZ	STACK_5, W
;math.ppas,635 :: 		
$0308	$07F9			ADDWF	STACK_9, F
;math.ppas,636 :: 		
$0309	$0876			MOVF	STACK_6, W
;math.ppas,637 :: 		
$030A	$1803			BTFSC	STATUS, C
;math.ppas,638 :: 		
$030B	$0F76			INCFSZ	STACK_6, W
;math.ppas,639 :: 		
$030C	$07FA			ADDWF	STACK_10, F
;math.ppas,640 :: 		
$030D	$0877			MOVF	STACK_7, W
;math.ppas,641 :: 		
$030E	$1803			BTFSC	STATUS, C
;math.ppas,642 :: 		
$030F	$0F77			INCFSZ	STACK_7, W
;math.ppas,644 :: 		
$0310	$07FB			ADDWF	STACK_11, F
;math.ppas,645 :: 		
$0311	$	SOK22L8:
;math.ppas,647 :: 		
$0311	$0DF2			RLF	STACK_2, F
;math.ppas,648 :: 		
$0312	$3007			MOVLW	7
;math.ppas,650 :: 		
$0313	$00FC			MOVWF	STACK_12
;math.ppas,651 :: 		
$0314	$	LOOPS3232B:
;math.ppas,652 :: 		
$0314	$0D72			RLF	STACK_2, W
;math.ppas,653 :: 		
$0315	$0DF8			RLF	STACK_8, F
;math.ppas,654 :: 		
$0316	$0DF9			RLF	STACK_9, F
;math.ppas,655 :: 		
$0317	$0DFA			RLF	STACK_10, F
;math.ppas,656 :: 		
$0318	$0DFB			RLF	STACK_11, F
;math.ppas,657 :: 		
$0319	$0874			MOVF	STACK_4, W
;math.ppas,658 :: 		
$031A	$1C72			BTFSS	STACK_2, 0
;math.ppas,660 :: 		
$031B	$2B2A			GOTO	SADD22LB
;math.ppas,661 :: 		
$031C	$02F8			SUBWF	STACK_8, F
;math.ppas,662 :: 		
$031D	$0875			MOVF	STACK_5, W
;math.ppas,663 :: 		
$031E	$1C03			BTFSS	STATUS, C
;math.ppas,664 :: 		
$031F	$0F75			INCFSZ	STACK_5, W
;math.ppas,665 :: 		
$0320	$02F9			SUBWF	STACK_9, F
;math.ppas,666 :: 		
$0321	$0876			MOVF	STACK_6, W
;math.ppas,667 :: 		
$0322	$1C03			BTFSS	STATUS, C
;math.ppas,668 :: 		
$0323	$0F76			INCFSZ	STACK_6, W
;math.ppas,669 :: 		
$0324	$02FA			SUBWF	STACK_10, F
;math.ppas,670 :: 		
$0325	$0877			MOVF	STACK_7, W
;math.ppas,671 :: 		
$0326	$1C03			BTFSS	STATUS, C
;math.ppas,672 :: 		
$0327	$0F77			INCFSZ	STACK_7, W
;math.ppas,673 :: 		
$0328	$02FB			SUBWF	STACK_11, F
;math.ppas,675 :: 		
$0329	$2B37			GOTO	SOK22LB
;math.ppas,676 :: 		
$032A	$	SADD22LB:
;math.ppas,677 :: 		
$032A	$07F8			ADDWF	STACK_8, F
;math.ppas,678 :: 		
$032B	$0875			MOVF	STACK_5, W
;math.ppas,679 :: 		
$032C	$1803			BTFSC	STATUS, C
;math.ppas,680 :: 		
$032D	$0F75			INCFSZ	STACK_5, W
;math.ppas,681 :: 		
$032E	$07F9			ADDWF	STACK_9, F
;math.ppas,682 :: 		
$032F	$0876			MOVF	STACK_6, W
;math.ppas,683 :: 		
$0330	$1803			BTFSC	STATUS, C
;math.ppas,684 :: 		
$0331	$0F76			INCFSZ	STACK_6, W
;math.ppas,685 :: 		
$0332	$07FA			ADDWF	STACK_10, F
;math.ppas,686 :: 		
$0333	$0877			MOVF	STACK_7, W
;math.ppas,687 :: 		
$0334	$1803			BTFSC	STATUS, C
;math.ppas,688 :: 		
$0335	$0F77			INCFSZ	STACK_7, W
;math.ppas,690 :: 		
$0336	$07FB			ADDWF	STACK_11, F
;math.ppas,691 :: 		
$0337	$	SOK22LB:
;math.ppas,693 :: 		
$0337	$0DF2			RLF	STACK_2, F
;math.ppas,694 :: 		
$0338	$0BFC			DECFSZ	STACK_12, F
;math.ppas,696 :: 		
$0339	$2B14			GOTO	LOOPS3232B
;math.ppas,697 :: 		
$033A	$0D71			RLF	STACK_1, W
;math.ppas,698 :: 		
$033B	$0DF8			RLF	STACK_8, F
;math.ppas,699 :: 		
$033C	$0DF9			RLF	STACK_9, F
;math.ppas,700 :: 		
$033D	$0DFA			RLF	STACK_10, F
;math.ppas,701 :: 		
$033E	$0DFB			RLF	STACK_11, F
;math.ppas,702 :: 		
$033F	$0874			MOVF	STACK_4, W
;math.ppas,703 :: 		
$0340	$1C72			BTFSS	STACK_2, 0
;math.ppas,705 :: 		
$0341	$2B50			GOTO	SADD22L16
;math.ppas,706 :: 		
$0342	$02F8			SUBWF	STACK_8, F
;math.ppas,707 :: 		
$0343	$0875			MOVF	STACK_5, W
;math.ppas,708 :: 		
$0344	$1C03			BTFSS	STATUS, C
;math.ppas,709 :: 		
$0345	$0F75			INCFSZ	STACK_5, W
;math.ppas,710 :: 		
$0346	$02F9			SUBWF	STACK_9, F
;math.ppas,711 :: 		
$0347	$0876			MOVF	STACK_6, W
;math.ppas,712 :: 		
$0348	$1C03			BTFSS	STATUS, C
;math.ppas,713 :: 		
$0349	$0F76			INCFSZ	STACK_6, W
;math.ppas,714 :: 		
$034A	$02FA			SUBWF	STACK_10, F
;math.ppas,715 :: 		
$034B	$0877			MOVF	STACK_7, W
;math.ppas,716 :: 		
$034C	$1C03			BTFSS	STATUS, C
;math.ppas,717 :: 		
$034D	$0F77			INCFSZ	STACK_7, W
;math.ppas,718 :: 		
$034E	$02FB			SUBWF	STACK_11, F
;math.ppas,720 :: 		
$034F	$2B5D			GOTO	SOK22L16
;math.ppas,721 :: 		
$0350	$	SADD22L16:
;math.ppas,722 :: 		
$0350	$07F8			ADDWF	STACK_8, F
;math.ppas,723 :: 		
$0351	$0875			MOVF	STACK_5, W
;math.ppas,724 :: 		
$0352	$1803			BTFSC	STATUS, C
;math.ppas,725 :: 		
$0353	$0F75			INCFSZ	STACK_5, W
;math.ppas,726 :: 		
$0354	$07F9			ADDWF	STACK_9, F
;math.ppas,727 :: 		
$0355	$0876			MOVF	STACK_6, W
;math.ppas,728 :: 		
$0356	$1803			BTFSC	STATUS, C
;math.ppas,729 :: 		
$0357	$0F76			INCFSZ	STACK_6, W
;math.ppas,730 :: 		
$0358	$07FA			ADDWF	STACK_10, F
;math.ppas,731 :: 		
$0359	$0877			MOVF	STACK_7, W
;math.ppas,732 :: 		
$035A	$1803			BTFSC	STATUS, C
;math.ppas,733 :: 		
$035B	$0F77			INCFSZ	STACK_7, W
;math.ppas,735 :: 		
$035C	$07FB			ADDWF	STACK_11, F
;math.ppas,736 :: 		
$035D	$	SOK22L16:
;math.ppas,738 :: 		
$035D	$0DF1			RLF	STACK_1, F
;math.ppas,739 :: 		
$035E	$3007			MOVLW	7
;math.ppas,741 :: 		
$035F	$00FC			MOVWF	STACK_12
;math.ppas,742 :: 		
$0360	$	LOOPS3232C:
;math.ppas,743 :: 		
$0360	$0D71			RLF	STACK_1, W
;math.ppas,744 :: 		
$0361	$0DF8			RLF	STACK_8, F
;math.ppas,745 :: 		
$0362	$0DF9			RLF	STACK_9, F
;math.ppas,746 :: 		
$0363	$0DFA			RLF	STACK_10, F
;math.ppas,747 :: 		
$0364	$0DFB			RLF	STACK_11, F
;math.ppas,748 :: 		
$0365	$0874			MOVF	STACK_4, W
;math.ppas,749 :: 		
$0366	$1C71			BTFSS	STACK_1, 0
;math.ppas,751 :: 		
$0367	$2B76			GOTO	SADD22LC
;math.ppas,752 :: 		
$0368	$02F8			SUBWF	STACK_8, F
;math.ppas,753 :: 		
$0369	$0875			MOVF	STACK_5, W
;math.ppas,754 :: 		
$036A	$1C03			BTFSS	STATUS, C
;math.ppas,755 :: 		
$036B	$0F75			INCFSZ	STACK_5, W
;math.ppas,756 :: 		
$036C	$02F9			SUBWF	STACK_9, F
;math.ppas,757 :: 		
$036D	$0876			MOVF	STACK_6, W
;math.ppas,758 :: 		
$036E	$1C03			BTFSS	STATUS, C
;math.ppas,759 :: 		
$036F	$0F76			INCFSZ	STACK_6, W
;math.ppas,760 :: 		
$0370	$02FA			SUBWF	STACK_10, F
;math.ppas,761 :: 		
$0371	$0877			MOVF	STACK_7, W
;math.ppas,762 :: 		
$0372	$1C03			BTFSS	STATUS, C
;math.ppas,763 :: 		
$0373	$0F77			INCFSZ	STACK_7, W
;math.ppas,764 :: 		
$0374	$02FB			SUBWF	STACK_11, F
;math.ppas,766 :: 		
$0375	$2B83			GOTO	SOK22LC
;math.ppas,767 :: 		
$0376	$	SADD22LC:
;math.ppas,768 :: 		
$0376	$07F8			ADDWF	STACK_8, F
;math.ppas,769 :: 		
$0377	$0875			MOVF	STACK_5, W
;math.ppas,770 :: 		
$0378	$1803			BTFSC	STATUS, C
;math.ppas,771 :: 		
$0379	$0F75			INCFSZ	STACK_5, W
;math.ppas,772 :: 		
$037A	$07F9			ADDWF	STACK_9, F
;math.ppas,773 :: 		
$037B	$0876			MOVF	STACK_6, W
;math.ppas,774 :: 		
$037C	$1803			BTFSC	STATUS, C
;math.ppas,775 :: 		
$037D	$0F76			INCFSZ	STACK_6, W
;math.ppas,776 :: 		
$037E	$07FA			ADDWF	STACK_10, F
;math.ppas,777 :: 		
$037F	$0877			MOVF	STACK_7, W
;math.ppas,778 :: 		
$0380	$1803			BTFSC	STATUS, C
;math.ppas,779 :: 		
$0381	$0F77			INCFSZ	STACK_7, W
;math.ppas,781 :: 		
$0382	$07FB			ADDWF	STACK_11, F
;math.ppas,782 :: 		
$0383	$	SOK22LC:
;math.ppas,784 :: 		
$0383	$0DF1			RLF	STACK_1, F
;math.ppas,785 :: 		
$0384	$0BFC			DECFSZ	STACK_12, F
;math.ppas,787 :: 		
$0385	$2B60			GOTO	LOOPS3232C
;math.ppas,788 :: 		
$0386	$0D70			RLF	STACK_0, W
;math.ppas,789 :: 		
$0387	$0DF8			RLF	STACK_8, F
;math.ppas,790 :: 		
$0388	$0DF9			RLF	STACK_9, F
;math.ppas,791 :: 		
$0389	$0DFA			RLF	STACK_10, F
;math.ppas,792 :: 		
$038A	$0DFB			RLF	STACK_11, F
;math.ppas,793 :: 		
$038B	$0874			MOVF	STACK_4, W
;math.ppas,794 :: 		
$038C	$1C71			BTFSS	STACK_1, 0
;math.ppas,796 :: 		
$038D	$2B9C			GOTO	SADD22L24
;math.ppas,797 :: 		
$038E	$02F8			SUBWF	STACK_8, F
;math.ppas,798 :: 		
$038F	$0875			MOVF	STACK_5, W
;math.ppas,799 :: 		
$0390	$1C03			BTFSS	STATUS, C
;math.ppas,800 :: 		
$0391	$0F75			INCFSZ	STACK_5, W
;math.ppas,801 :: 		
$0392	$02F9			SUBWF	STACK_9, F
;math.ppas,802 :: 		
$0393	$0876			MOVF	STACK_6, W
;math.ppas,803 :: 		
$0394	$1C03			BTFSS	STATUS, C
;math.ppas,804 :: 		
$0395	$0F76			INCFSZ	STACK_6, W
;math.ppas,805 :: 		
$0396	$02FA			SUBWF	STACK_10, F
;math.ppas,806 :: 		
$0397	$0877			MOVF	STACK_7, W
;math.ppas,807 :: 		
$0398	$1C03			BTFSS	STATUS, C
;math.ppas,808 :: 		
$0399	$0F77			INCFSZ	STACK_7, W
;math.ppas,809 :: 		
$039A	$02FB			SUBWF	STACK_11, F
;math.ppas,811 :: 		
$039B	$2BA9			GOTO	SOK22L24
;math.ppas,812 :: 		
$039C	$	SADD22L24:
;math.ppas,813 :: 		
$039C	$07F8			ADDWF	STACK_8, F
;math.ppas,814 :: 		
$039D	$0875			MOVF	STACK_5, W
;math.ppas,815 :: 		
$039E	$1803			BTFSC	STATUS, C
;math.ppas,816 :: 		
$039F	$0F75			INCFSZ	STACK_5, W
;math.ppas,817 :: 		
$03A0	$07F9			ADDWF	STACK_9, F
;math.ppas,818 :: 		
$03A1	$0876			MOVF	STACK_6, W
;math.ppas,819 :: 		
$03A2	$1803			BTFSC	STATUS, C
;math.ppas,820 :: 		
$03A3	$0F76			INCFSZ	STACK_6, W
;math.ppas,821 :: 		
$03A4	$07FA			ADDWF	STACK_10, F
;math.ppas,822 :: 		
$03A5	$0877			MOVF	STACK_7, W
;math.ppas,823 :: 		
$03A6	$1803			BTFSC	STATUS, C
;math.ppas,824 :: 		
$03A7	$0F77			INCFSZ	STACK_7, W
;math.ppas,826 :: 		
$03A8	$07FB			ADDWF	STACK_11, F
;math.ppas,827 :: 		
$03A9	$	SOK22L24:
;math.ppas,829 :: 		
$03A9	$0DF0			RLF	STACK_0, F
;math.ppas,830 :: 		
$03AA	$3007			MOVLW	7
;math.ppas,832 :: 		
$03AB	$00FC			MOVWF	STACK_12
;math.ppas,833 :: 		
$03AC	$	LOOPS3232D:
;math.ppas,834 :: 		
$03AC	$0D70			RLF	STACK_0, W
;math.ppas,835 :: 		
$03AD	$0DF8			RLF	STACK_8, F
;math.ppas,836 :: 		
$03AE	$0DF9			RLF	STACK_9, F
;math.ppas,837 :: 		
$03AF	$0DFA			RLF	STACK_10, F
;math.ppas,838 :: 		
$03B0	$0DFB			RLF	STACK_11, F
;math.ppas,839 :: 		
$03B1	$0874			MOVF	STACK_4, W
;math.ppas,840 :: 		
$03B2	$1C70			BTFSS	STACK_0, 0
;math.ppas,842 :: 		
$03B3	$2BC2			GOTO	SADD22LD
;math.ppas,843 :: 		
$03B4	$02F8			SUBWF	STACK_8, F
;math.ppas,844 :: 		
$03B5	$0875			MOVF	STACK_5, W
;math.ppas,845 :: 		
$03B6	$1C03			BTFSS	STATUS, C
;math.ppas,846 :: 		
$03B7	$0F75			INCFSZ	STACK_5, W
;math.ppas,847 :: 		
$03B8	$02F9			SUBWF	STACK_9, F
;math.ppas,848 :: 		
$03B9	$0876			MOVF	STACK_6, W
;math.ppas,849 :: 		
$03BA	$1C03			BTFSS	STATUS, C
;math.ppas,850 :: 		
$03BB	$0F76			INCFSZ	STACK_6, W
;math.ppas,851 :: 		
$03BC	$02FA			SUBWF	STACK_10, F
;math.ppas,852 :: 		
$03BD	$0877			MOVF	STACK_7, W
;math.ppas,853 :: 		
$03BE	$1C03			BTFSS	STATUS, C
;math.ppas,854 :: 		
$03BF	$0F77			INCFSZ	STACK_7, W
;math.ppas,855 :: 		
$03C0	$02FB			SUBWF	STACK_11, F
;math.ppas,857 :: 		
$03C1	$2BCF			GOTO	SOK22LD
;math.ppas,858 :: 		
$03C2	$	SADD22LD:
;math.ppas,859 :: 		
$03C2	$07F8			ADDWF	STACK_8, F
;math.ppas,860 :: 		
$03C3	$0875			MOVF	STACK_5, W
;math.ppas,861 :: 		
$03C4	$1803			BTFSC	STATUS, C
;math.ppas,862 :: 		
$03C5	$0F75			INCFSZ	STACK_5, W
;math.ppas,863 :: 		
$03C6	$07F9			ADDWF	STACK_9, F
;math.ppas,864 :: 		
$03C7	$0876			MOVF	STACK_6, W
;math.ppas,865 :: 		
$03C8	$1803			BTFSC	STATUS, C
;math.ppas,866 :: 		
$03C9	$0F76			INCFSZ	STACK_6, W
;math.ppas,867 :: 		
$03CA	$07FA			ADDWF	STACK_10, F
;math.ppas,868 :: 		
$03CB	$0877			MOVF	STACK_7, W
;math.ppas,870 :: 		
$03CC	$1803			BTFSC	STATUS, C
;math.ppas,871 :: 		
$03CD	$0F77			INCFSZ	STACK_7, W
;math.ppas,873 :: 		
$03CE	$07FB			ADDWF	STACK_11, F
;math.ppas,874 :: 		
$03CF	$	SOK22LD:
;math.ppas,876 :: 		
$03CF	$0DF0			RLF	STACK_0, F
;math.ppas,877 :: 		
$03D0	$0BFC			DECFSZ	STACK_12, F
;math.ppas,879 :: 		
$03D1	$2BAC			GOTO	LOOPS3232D
;math.ppas,880 :: 		
$03D2	$1870			BTFSC	STACK_0, 0
;math.ppas,881 :: 		
$03D3	$2BE2			GOTO	SOK22L
;math.ppas,882 :: 		
$03D4	$0874			MOVF	STACK_4, W
;math.ppas,883 :: 		
$03D5	$07F8			ADDWF	STACK_8, F
;math.ppas,884 :: 		
$03D6	$0875			MOVF	STACK_5, W
;math.ppas,885 :: 		
$03D7	$1803			BTFSC	STATUS, C
;math.ppas,886 :: 		
$03D8	$0F75			INCFSZ	STACK_5, W
;math.ppas,887 :: 		
$03D9	$07F9			ADDWF	STACK_9, F
;math.ppas,888 :: 		
$03DA	$0876			MOVF	STACK_6, W
;math.ppas,889 :: 		
$03DB	$1803			BTFSC	STATUS, C
;math.ppas,890 :: 		
$03DC	$0F76			INCFSZ	STACK_6, W
;math.ppas,891 :: 		
$03DD	$07FA			ADDWF	STACK_10, F
;math.ppas,892 :: 		
$03DE	$0877			MOVF	STACK_7, W
;math.ppas,893 :: 		
$03DF	$1803			BTFSC	STATUS, C
;math.ppas,894 :: 		
$03E0	$0F77			INCFSZ	STACK_7, W
;math.ppas,895 :: 		
$03E1	$07FB			ADDWF	STACK_11, F
;math.ppas,896 :: 		
$03E2	$	SOK22L:
;math.ppas,897 :: 		
$03E2	$	math_L_9:
;math.ppas,898 :: 		
$03E2	$0008			RETURN
$0756	$	_comfrem:
$0756	$1303			BCF	STATUS, RP1
$0757	$1283			BCF	STATUS, RP0
;math.ppas,901 :: 		
;math.ppas,903 :: 		
$0758	$09FB			COMF	STACK_11, F
;math.ppas,904 :: 		
$0759	$09FA			COMF	STACK_10, F
;math.ppas,905 :: 		
$075A	$09F9			COMF	STACK_9, F
;math.ppas,906 :: 		
$075B	$09F8			COMF	STACK_8, F
;math.ppas,907 :: 		
$075C	$0AF8			INCF	STACK_8, F
;math.ppas,908 :: 		
$075D	$1903			BTFSC	STATUS, Z
;math.ppas,909 :: 		
$075E	$0AF9			INCF	STACK_9, F
;math.ppas,910 :: 		
$075F	$1903			BTFSC	STATUS, Z
;math.ppas,911 :: 		
$0760	$0AFA			INCF	STACK_10, F
;math.ppas,912 :: 		
$0761	$1903			BTFSC	STATUS, Z
;math.ppas,913 :: 		
$0762	$0AFB			INCF	STACK_11, F
;math.ppas,914 :: 		
$0763	$	math_L_10:
;math.ppas,915 :: 		
$0763	$0008			RETURN
$086D	$	_usart_data_ready:
;USART_c67.ppas,48 :: 		
;USART_c67.ppas,50 :: 		
$086D	$1303			BCF	STATUS, RP1
$086E	$1283			BCF	STATUS, RP0
$086F	$080C			MOVF	PIR1, 0
$0870	$00F1			MOVWF	STACK_1
$0871	$3000			MOVLW	0
$0872	$1AF1			BTFSC	STACK_1, 5
$0873	$3001			MOVLW	1
$0874	$00F1			MOVWF	STACK_1
$0875	$0871			MOVF	STACK_1, 0
$0876	$00C5			MOVWF	_usart_data_ready_local_result
$0877	$	USART_c67_L_18:
;USART_c67.ppas,51 :: 		
$0877	$0845			MOVF	_usart_data_ready_local_result, 0
$0878	$00F0			MOVWF	STACK_0
$0879	$0008			RETURN
$0848	$	_usart_read:
;USART_c67.ppas,54 :: 		
;USART_c67.ppas,55 :: 		
$0848	$1303			BCF	STATUS, RP1
$0849	$1283			BCF	STATUS, RP0
$084A	$081A			MOVF	RCREG, 0
$084B	$00C5			MOVWF	_usart_read_local_result
;USART_c67.ppas,61 :: 		
$084C	$0818			MOVF	RCSTA, 0
$084D	$00F1			MOVWF	STACK_1
$084E	$3000			MOVLW	0
$084F	$18F1			BTFSC	STACK_1, 1
$0850	$3001			MOVLW	1
$0851	$00F1			MOVWF	STACK_1
$0852	$0871			MOVF	STACK_1, 0
$0853	$3A01			XORLW	1
$0854	$1D03			BTFSS	STATUS, Z
$0855	$2858			GOTO	USART_c67_L_21
$0856	$	USART_c67_L_20:
;USART_c67.ppas,63 :: 		
$0856	$1218			BCF	RCSTA, 4
$0857	$	USART_c67_L_24:
;USART_c67.ppas,64 :: 		
$0857	$	USART_c67_L_25:
$0857	$1618			BSF	RCSTA, 4
$0858	$	USART_c67_L_26:
;USART_c67.ppas,65 :: 		
$0858	$	USART_c67_L_21:
$0858	$	USART_c67_L_22:
$0858	$	USART_c67_L_19:
;USART_c67.ppas,66 :: 		
$0858	$0845			MOVF	_usart_read_local_result, 0
$0859	$00F0			MOVWF	STACK_0
$085A	$0008			RETURN
$062B	$	_mul_32x32_s:
$062B	$1303			BCF	STATUS, RP1
$062C	$1283			BCF	STATUS, RP0
;math.ppas,1675 :: 		
;math.ppas,1680 :: 		
$062D	$01FD			CLRF	STACK_13
;math.ppas,1683 :: 		
$062E	$	_IF_FIRST:
;math.ppas,1684 :: 		
$062E	$1FF3			BTFSS	STACK_3, 7
;math.ppas,1686 :: 		
$062F	$2E3D			GOTO	_IF_SECOND
;math.ppas,1691 :: 		
$0630	$	_INVERCE_FIRST:
;math.ppas,1692 :: 		
$0630	$09F0			COMF	STACK_0, F
;math.ppas,1693 :: 		
$0631	$09F1			COMF	STACK_1, F
;math.ppas,1694 :: 		
$0632	$09F2			COMF	STACK_2, F
;math.ppas,1701 :: 		
$0633	$09F3			COMF	STACK_3, F
;math.ppas,1702 :: 		
$0634	$0AF0			INCF	STACK_0, F
;math.ppas,1703 :: 		
$0635	$1903			BTFSC	STATUS, Z
;math.ppas,1704 :: 		
$0636	$0AF1			INCF	STACK_1, F
;math.ppas,1705 :: 		
$0637	$1903			BTFSC	STATUS, Z
;math.ppas,1706 :: 		
$0638	$0AF2			INCF	STACK_2, F
;math.ppas,1707 :: 		
$0639	$1903			BTFSC	STATUS, Z
;math.ppas,1708 :: 		
$063A	$0AF3			INCF	STACK_3, F
;math.ppas,1709 :: 		
$063B	$3081			MOVLW	129
;math.ppas,1711 :: 		
$063C	$07FD			ADDWF	STACK_13, F
;math.ppas,1714 :: 		
$063D	$	_IF_SECOND:
;math.ppas,1715 :: 		
$063D	$1FF7			BTFSS	STACK_7, 7
;math.ppas,1717 :: 		
$063E	$2E4B			GOTO	_MULT
;math.ppas,1722 :: 		
$063F	$	_INBERSE_SECOND:
;math.ppas,1723 :: 		
$063F	$09F4			COMF	STACK_4, F
;math.ppas,1724 :: 		
$0640	$09F5			COMF	STACK_5, F
;math.ppas,1725 :: 		
$0641	$09F6			COMF	STACK_6, F
;math.ppas,1732 :: 		
$0642	$09F7			COMF	STACK_7, F
;math.ppas,1733 :: 		
$0643	$0AF4			INCF	STACK_4, F
;math.ppas,1734 :: 		
$0644	$1903			BTFSC	STATUS, Z
;math.ppas,1735 :: 		
$0645	$0AF5			INCF	STACK_5, F
;math.ppas,1736 :: 		
$0646	$1903			BTFSC	STATUS, Z
;math.ppas,1737 :: 		
$0647	$0AF6			INCF	STACK_6, F
;math.ppas,1738 :: 		
$0648	$1903			BTFSC	STATUS, Z
;math.ppas,1739 :: 		
$0649	$0AF7			INCF	STACK_7, F
;math.ppas,1741 :: 		
$064A	$0AFD			INCF	STACK_13, F
;math.ppas,1742 :: 		
$064B	$	_MULT:
;math.ppas,1744 :: 		
$064B	$26A0			CALL	_mul_32x32_u
;math.ppas,1748 :: 		
$064C	$1C7D			BTFSS	STACK_13, 0
;math.ppas,1754 :: 		
$064D	$2E65			GOTO	_EXIT
;math.ppas,1755 :: 		
$064E	$09F0			COMF	STACK_0, F
;math.ppas,1756 :: 		
$064F	$09F1			COMF	STACK_1, F
;math.ppas,1757 :: 		
$0650	$09F2			COMF	STACK_2, F
;math.ppas,1763 :: 		
$0651	$09F3			COMF	STACK_3, F
;math.ppas,1764 :: 		
$0652	$09F8			COMF	STACK_8, F
;math.ppas,1765 :: 		
$0653	$09F9			COMF	STACK_9, F
;math.ppas,1766 :: 		
$0654	$09FA			COMF	STACK_10, F
;math.ppas,1776 :: 		
$0655	$09FB			COMF	STACK_11, F
;math.ppas,1777 :: 		
$0656	$0AF0			INCF	STACK_0, F
;math.ppas,1778 :: 		
$0657	$1903			BTFSC	STATUS, Z
;math.ppas,1779 :: 		
$0658	$0AF1			INCF	STACK_1, F
;math.ppas,1780 :: 		
$0659	$1903			BTFSC	STATUS, Z
;math.ppas,1781 :: 		
$065A	$0AF2			INCF	STACK_2, F
;math.ppas,1782 :: 		
$065B	$1903			BTFSC	STATUS, Z
;math.ppas,1783 :: 		
$065C	$0AF3			INCF	STACK_3, F
;math.ppas,1784 :: 		
$065D	$1903			BTFSC	STATUS, Z
;math.ppas,1785 :: 		
$065E	$0AF8			INCF	STACK_8, F
;math.ppas,1786 :: 		
$065F	$1903			BTFSC	STATUS, Z
;math.ppas,1787 :: 		
$0660	$0AF9			INCF	STACK_9, F
;math.ppas,1788 :: 		
$0661	$1903			BTFSC	STATUS, Z
;math.ppas,1789 :: 		
$0662	$0AFA			INCF	STACK_10, F
;math.ppas,1790 :: 		
$0663	$1903			BTFSC	STATUS, Z
;math.ppas,1791 :: 		
$0664	$0AFB			INCF	STACK_11, F
;math.ppas,1792 :: 		
$0665	$	_EXIT:
;math.ppas,1793 :: 		
$0665	$	math_L_14:
;math.ppas,1794 :: 		
$0665	$0008			RETURN
$0800	$	_div_16x16_u:
$0800	$1303			BCF	STATUS, RP1
$0801	$1283			BCF	STATUS, RP0
;math.ppas,108 :: 		
;math.ppas,110 :: 		
$0802	$01F8			CLRF	STACK_8
;math.ppas,111 :: 		
$0803	$01F9			CLRF	STACK_9
;math.ppas,112 :: 		
$0804	$3010			MOVLW	16
;math.ppas,113 :: 		
$0805	$00FC			MOVWF	STACK_12
;math.ppas,114 :: 		
$0806	$0D71			RLF	STACK_1, W
;math.ppas,115 :: 		
$0807	$0DF8			RLF	STACK_8, F
;math.ppas,116 :: 		
$0808	$0DF9			RLF	STACK_9, F
;math.ppas,117 :: 		
$0809	$0874			MOVF	STACK_4, W
;math.ppas,118 :: 		
$080A	$02F8			SUBWF	STACK_8, F
;math.ppas,119 :: 		
$080B	$0875			MOVF	STACK_5, W
;math.ppas,120 :: 		
$080C	$1C03			BTFSS	STATUS, C
;math.ppas,121 :: 		
$080D	$0F75			INCFSZ	STACK_5, W
;math.ppas,122 :: 		
$080E	$02F9			SUBWF	STACK_9, F
;math.ppas,123 :: 		
$080F	$1803			BTFSC	STATUS, C
;math.ppas,124 :: 		
$0810	$2818			GOTO	$+8
;math.ppas,125 :: 		
$0811	$0874			MOVF	STACK_4, W
;math.ppas,126 :: 		
$0812	$07F8			ADDWF	STACK_8, F
;math.ppas,127 :: 		
$0813	$0875			MOVF	STACK_5, W
;math.ppas,128 :: 		
$0814	$1803			BTFSC	STATUS, C
;math.ppas,129 :: 		
$0815	$0F75			INCFSZ	STACK_5, W
;math.ppas,130 :: 		
$0816	$07F9			ADDWF	STACK_9, F
;math.ppas,131 :: 		
$0817	$1003			BCF	STATUS, C
;math.ppas,132 :: 		
$0818	$0DF0			RLF	STACK_0, F
;math.ppas,133 :: 		
$0819	$0DF1			RLF	STACK_1, F
;math.ppas,134 :: 		
$081A	$0BFC			DECFSZ	STACK_12, F
;math.ppas,135 :: 		
$081B	$2806			GOTO	$-21
;math.ppas,136 :: 		
$081C	$	math_L_3:
;math.ppas,137 :: 		
$081C	$0008			RETURN
$04A7	$	_div_32x32_s:
$04A7	$1303			BCF	STATUS, RP1
$04A8	$1283			BCF	STATUS, RP0
;math.ppas,925 :: 		
;math.ppas,928 :: 		
$04A9	$	FXD3232S:
;math.ppas,929 :: 		
$04A9	$01FC			CLRF	STACK_12
;math.ppas,930 :: 		
$04AA	$1BF7			BTFSC	STACK_7, 7
;math.ppas,932 :: 		
$04AB	$0AFC			INCF	STACK_12, F
;math.ppas,933 :: 		
$04AC	$01FD			CLRF	STACK_13
;math.ppas,934 :: 		
$04AD	$01FB			CLRF	STACK_11
;math.ppas,935 :: 		
$04AE	$01FA			CLRF	STACK_10
;math.ppas,936 :: 		
$04AF	$01F9			CLRF	STACK_9
;math.ppas,937 :: 		
$04B0	$01F8			CLRF	STACK_8
;math.ppas,938 :: 		
$04B1	$0873			MOVF	STACK_3, W
;math.ppas,939 :: 		
$04B2	$0472			IORWF	STACK_2, W
;math.ppas,940 :: 		
$04B3	$0471			IORWF	STACK_1, W
;math.ppas,941 :: 		
$04B4	$0470			IORWF	STACK_0, W
;math.ppas,942 :: 		
$04B5	$1903			BTFSC	STATUS, Z
;math.ppas,943 :: 		
$04B6	$2D3B			GOTO	END_ALL
;math.ppas,944 :: 		
$04B7	$0873			MOVF	STACK_3, W
;math.ppas,945 :: 		
$04B8	$0677			XORWF	STACK_7, W
;math.ppas,946 :: 		
$04B9	$00A0			MOVWF	MATH___MATH_TEMPB
;math.ppas,947 :: 		
$04BA	$1BA0			BTFSC	MATH___MATH_TEMPB, 7
;math.ppas,951 :: 		
$04BB	$09FD			COMF	STACK_13, F
;math.ppas,952 :: 		
$04BC	$1FF7			BTFSS	STACK_7, 7
;math.ppas,954 :: 		
$04BD	$2CC9			GOTO	CA3232S
;math.ppas,955 :: 		
$04BE	$09F4			COMF	STACK_4, F
;math.ppas,956 :: 		
$04BF	$09F5			COMF	STACK_5, F
;math.ppas,957 :: 		
$04C0	$09F6			COMF	STACK_6, F
;math.ppas,958 :: 		
$04C1	$09F7			COMF	STACK_7, F
;math.ppas,959 :: 		
$04C2	$0AF4			INCF	STACK_4, F
;math.ppas,960 :: 		
$04C3	$1903			BTFSC	STATUS, Z
;math.ppas,961 :: 		
$04C4	$0AF5			INCF	STACK_5, F
;math.ppas,962 :: 		
$04C5	$1903			BTFSC	STATUS, Z
;math.ppas,963 :: 		
$04C6	$0AF6			INCF	STACK_6, F
;math.ppas,964 :: 		
$04C7	$1903			BTFSC	STATUS, Z
;math.ppas,966 :: 		
$04C8	$0AF7			INCF	STACK_7, F
;math.ppas,967 :: 		
$04C9	$	CA3232S:
;math.ppas,968 :: 		
$04C9	$1FF3			BTFSS	STACK_3, 7
;math.ppas,970 :: 		
$04CA	$2CD6			GOTO	C3232SX
;math.ppas,971 :: 		
$04CB	$09F0			COMF	STACK_0, F
;math.ppas,972 :: 		
$04CC	$09F1			COMF	STACK_1, F
;math.ppas,973 :: 		
$04CD	$09F2			COMF	STACK_2, F
;math.ppas,974 :: 		
$04CE	$09F3			COMF	STACK_3, F
;math.ppas,975 :: 		
$04CF	$0AF0			INCF	STACK_0, F
;math.ppas,976 :: 		
$04D0	$1903			BTFSC	STATUS, Z
;math.ppas,977 :: 		
$04D1	$0AF1			INCF	STACK_1, F
;math.ppas,978 :: 		
$04D2	$1903			BTFSC	STATUS, Z
;math.ppas,979 :: 		
$04D3	$0AF2			INCF	STACK_2, F
;math.ppas,980 :: 		
$04D4	$1903			BTFSC	STATUS, Z
;math.ppas,982 :: 		
$04D5	$0AF3			INCF	STACK_3, F
;math.ppas,983 :: 		
$04D6	$	C3232SX:
;math.ppas,984 :: 		
$04D6	$0873			MOVF	STACK_3, W
;math.ppas,985 :: 		
$04D7	$0477			IORWF	STACK_7, W
;math.ppas,986 :: 		
$04D8	$00A0			MOVWF	MATH___MATH_TEMPB
;math.ppas,987 :: 		
$04D9	$1BA0			BTFSC	MATH___MATH_TEMPB, 7
;math.ppas,988 :: 		
$04DA	$2CF7			GOTO	C3232SX1
;math.ppas,989 :: 		
$04DB	$	C3232S:
;math.ppas,992 :: 		
$04DB	$22B5			CALL	_sdiv3232l
;math.ppas,995 :: 		
$04DC	$	C3232S2:
;math.ppas,996 :: 		
$04DC	$1BFC			BTFSC	STACK_12, 7
;math.ppas,997 :: 		
$04DD	$2D14			GOTO	C3232SX4
;math.ppas,998 :: 		
$04DE	$	C3232SOK:
;math.ppas,999 :: 		
$04DE	$1FFD			BTFSS	STACK_13, 7
;math.ppas,1000 :: 		
$04DF	$2D3B			GOTO	END_ALL
;math.ppas,1001 :: 		
$04E0	$09F0			COMF	STACK_0, F
;math.ppas,1002 :: 		
$04E1	$09F1			COMF	STACK_1, F
;math.ppas,1003 :: 		
$04E2	$09F2			COMF	STACK_2, F
;math.ppas,1004 :: 		
$04E3	$09F3			COMF	STACK_3, F
;math.ppas,1005 :: 		
$04E4	$0AF0			INCF	STACK_0, F
;math.ppas,1006 :: 		
$04E5	$1903			BTFSC	STATUS, Z
;math.ppas,1007 :: 		
$04E6	$0AF1			INCF	STACK_1, F
;math.ppas,1008 :: 		
$04E7	$1903			BTFSC	STATUS, Z
;math.ppas,1009 :: 		
$04E8	$0AF2			INCF	STACK_2, F
;math.ppas,1010 :: 		
$04E9	$1903			BTFSC	STATUS, Z
;math.ppas,1012 :: 		
$04EA	$0AF3			INCF	STACK_3, F
;math.ppas,1013 :: 		
$04EB	$09F8			COMF	STACK_8, F
;math.ppas,1014 :: 		
$04EC	$09F9			COMF	STACK_9, F
;math.ppas,1015 :: 		
$04ED	$09FA			COMF	STACK_10, F
;math.ppas,1016 :: 		
$04EE	$09FB			COMF	STACK_11, F
;math.ppas,1017 :: 		
$04EF	$0AF8			INCF	STACK_8, F
;math.ppas,1018 :: 		
$04F0	$1903			BTFSC	STATUS, Z
;math.ppas,1019 :: 		
$04F1	$0AF9			INCF	STACK_9, F
;math.ppas,1020 :: 		
$04F2	$1903			BTFSC	STATUS, Z
;math.ppas,1021 :: 		
$04F3	$0AFA			INCF	STACK_10, F
;math.ppas,1022 :: 		
$04F4	$1903			BTFSC	STATUS, Z
;math.ppas,1024 :: 		
$04F5	$0AFB			INCF	STACK_11, F
;math.ppas,1025 :: 		
$04F6	$2D3B			GOTO	END_ALL
;math.ppas,1026 :: 		
$04F7	$	C3232SX1:
;math.ppas,1027 :: 		
$04F7	$1FF7			BTFSS	STACK_7, 7
;math.ppas,1028 :: 		
$04F8	$2D0E			GOTO	C3232SX3
;math.ppas,1029 :: 		
$04F9	$1BF3			BTFSC	STACK_3, 7
;math.ppas,1030 :: 		
$04FA	$2D08			GOTO	C3232SX2
;math.ppas,1031 :: 		
$04FB	$0873			MOVF	STACK_3, W
;math.ppas,1032 :: 		
$04FC	$00FB			MOVWF	STACK_11
;math.ppas,1033 :: 		
$04FD	$0872			MOVF	STACK_2, W
;math.ppas,1034 :: 		
$04FE	$00FA			MOVWF	STACK_10
;math.ppas,1035 :: 		
$04FF	$0871			MOVF	STACK_1, W
;math.ppas,1036 :: 		
$0500	$00F9			MOVWF	STACK_9
;math.ppas,1037 :: 		
$0501	$0870			MOVF	STACK_0, W
;math.ppas,1038 :: 		
$0502	$00F8			MOVWF	STACK_8
;math.ppas,1039 :: 		
$0503	$01F3			CLRF	STACK_3
;math.ppas,1040 :: 		
$0504	$01F2			CLRF	STACK_2
;math.ppas,1041 :: 		
$0505	$01F1			CLRF	STACK_1
;math.ppas,1042 :: 		
$0506	$01F0			CLRF	STACK_0
;math.ppas,1043 :: 		
$0507	$2CDE			GOTO	C3232SOK
;math.ppas,1044 :: 		
$0508	$	C3232SX2:
;math.ppas,1045 :: 		
$0508	$01F3			CLRF	STACK_3
;math.ppas,1046 :: 		
$0509	$01F2			CLRF	STACK_2
;math.ppas,1047 :: 		
$050A	$01F1			CLRF	STACK_1
;math.ppas,1048 :: 		
$050B	$01F0			CLRF	STACK_0
;math.ppas,1049 :: 		
$050C	$0AF0			INCF	STACK_0, F
;math.ppas,1051 :: 		
$050D	$3400			RETLW	0X00
;math.ppas,1052 :: 		
$050E	$	C3232SX3:
;math.ppas,1053 :: 		
$050E	$09F3			COMF	STACK_3, F
;math.ppas,1054 :: 		
$050F	$09F2			COMF	STACK_2, F
;math.ppas,1055 :: 		
$0510	$09F1			COMF	STACK_1, F
;math.ppas,1057 :: 		
$0511	$09F0			COMF	STACK_0, F
;math.ppas,1059 :: 		
$0512	$17FC			BSF	STACK_12, 7
;math.ppas,1060 :: 		
$0513	$2CDB			GOTO	C3232S
;math.ppas,1061 :: 		
$0514	$	C3232SX4:
;math.ppas,1062 :: 		
$0514	$0AF8			INCF	STACK_8, F
;math.ppas,1063 :: 		
$0515	$1903			BTFSC	STATUS, Z
;math.ppas,1064 :: 		
$0516	$0AF9			INCF	STACK_9, F
;math.ppas,1065 :: 		
$0517	$1903			BTFSC	STATUS, Z
;math.ppas,1066 :: 		
$0518	$0AFA			INCF	STACK_10, F
;math.ppas,1067 :: 		
$0519	$1903			BTFSC	STATUS, Z
;math.ppas,1068 :: 		
$051A	$0AFB			INCF	STACK_11, F
;math.ppas,1069 :: 		
$051B	$0874			MOVF	STACK_4, W
;math.ppas,1070 :: 		
$051C	$0278			SUBWF	STACK_8, W
;math.ppas,1071 :: 		
$051D	$1D03			BTFSS	STATUS, Z
;math.ppas,1072 :: 		
$051E	$2CDE			GOTO	C3232SOK
;math.ppas,1073 :: 		
$051F	$0875			MOVF	STACK_5, W
;math.ppas,1074 :: 		
$0520	$0279			SUBWF	STACK_9, W
;math.ppas,1075 :: 		
$0521	$1D03			BTFSS	STATUS, Z
;math.ppas,1076 :: 		
$0522	$2CDE			GOTO	C3232SOK
;math.ppas,1077 :: 		
$0523	$0876			MOVF	STACK_6, W
;math.ppas,1078 :: 		
$0524	$027A			SUBWF	STACK_10, W
;math.ppas,1079 :: 		
$0525	$1D03			BTFSS	STATUS, Z
;math.ppas,1080 :: 		
$0526	$2CDE			GOTO	C3232SOK
;math.ppas,1081 :: 		
$0527	$0877			MOVF	STACK_7, W
;math.ppas,1082 :: 		
$0528	$027B			SUBWF	STACK_11, W
;math.ppas,1083 :: 		
$0529	$1D03			BTFSS	STATUS, Z
;math.ppas,1084 :: 		
$052A	$2CDE			GOTO	C3232SOK
;math.ppas,1085 :: 		
$052B	$01FB			CLRF	STACK_11
;math.ppas,1086 :: 		
$052C	$01FA			CLRF	STACK_10
;math.ppas,1087 :: 		
$052D	$01F9			CLRF	STACK_9
;math.ppas,1088 :: 		
$052E	$01F8			CLRF	STACK_8
;math.ppas,1089 :: 		
$052F	$0AF0			INCF	STACK_0, F
;math.ppas,1090 :: 		
$0530	$1903			BTFSC	STATUS, Z
;math.ppas,1091 :: 		
$0531	$0AF1			INCF	STACK_1, F
;math.ppas,1092 :: 		
$0532	$1903			BTFSC	STATUS, Z
;math.ppas,1093 :: 		
$0533	$0AF2			INCF	STACK_2, F
;math.ppas,1094 :: 		
$0534	$1903			BTFSC	STATUS, Z
;math.ppas,1095 :: 		
$0535	$0AF3			INCF	STACK_3, F
;math.ppas,1096 :: 		
$0536	$1FF3			BTFSS	STACK_3, 7
;math.ppas,1097 :: 		
$0537	$2CDE			GOTO	C3232SOK
;math.ppas,1098 :: 		
$0538	$01A0			CLRF	MATH___MATH_TEMPB
;math.ppas,1099 :: 		
$0539	$1620			BSF	MATH___MATH_TEMPB, 4
;math.ppas,1100 :: 		
$053A	$34FF			RETLW	0XFF
;math.ppas,1101 :: 		
$053B	$	END_ALL:
;math.ppas,1102 :: 		
$053B	$01A0			CLRF	MATH___MATH_TEMPB
;math.ppas,1103 :: 		
$053C	$1C7C			BTFSS	STACK_12, 0
;math.ppas,1104 :: 		
$053D	$2D3F			GOTO	AVOID_COMFREM
;math.ppas,1106 :: 		
$053E	$2756			CALL	_comfrem
;math.ppas,1108 :: 		
$053F	$	AVOID_COMFREM:
;math.ppas,1109 :: 		
$053F	$3F00			ADDLW	0X00
;math.ppas,1110 :: 		
$0540	$	math_L_11:
;math.ppas,1111 :: 		
$0540	$0008			RETURN
$085B	$	_usart_write:
;USART_c67.ppas,40 :: 		
;USART_c67.ppas,42 :: 		
$085B	$	USART_c67_L_14:
$085B	$1303			BCF	STATUS, RP1
$085C	$1683			BSF	STATUS, RP0
$085D	$0818			MOVF	TXSTA, 0
$085E	$00F1			MOVWF	STACK_1
$085F	$3000			MOVLW	0
$0860	$18F1			BTFSC	STACK_1, 1
$0861	$3001			MOVLW	1
$0862	$00F1			MOVWF	STACK_1
$0863	$0871			MOVF	STACK_1, 0
$0864	$3A00			XORLW	0
$0865	$1D03			BTFSS	STATUS, Z
$0866	$2869			GOTO	USART_c67_L_15
;USART_c67.ppas,43 :: 		
$0867	$0000			NOP
$0868	$285B			GOTO	USART_c67_L_14
$0869	$	USART_c67_L_15:
;USART_c67.ppas,44 :: 		
$0869	$1283			BCF	STATUS, RP0
$086A	$0845			MOVF	FARG_USART_Write, 0
$086B	$0099			MOVWF	TXREG
$086C	$	USART_c67_L_12:
;USART_c67.ppas,45 :: 		
$086C	$0008			RETURN
$0737	$	_i2c_is_idle:
;I2C_c34.ppas,22 :: 		
;I2C_c34.ppas,23 :: 		
$0737	$1303			BCF	STATUS, RP1
$0738	$1283			BCF	STATUS, RP0
$0739	$01C5			CLRF	_i2c_is_idle_local_result, 1
;I2C_c34.ppas,24 :: 		
$073A	$1683			BSF	STATUS, RP0
$073B	$0814			MOVF	SSPSTAT, 0
$073C	$00F1			MOVWF	STACK_1
$073D	$3000			MOVLW	0
$073E	$1971			BTFSC	STACK_1, 2
$073F	$3001			MOVLW	1
$0740	$00F1			MOVWF	STACK_1
$0741	$0871			MOVF	STACK_1, 0
$0742	$3A00			XORLW	0
$0743	$1D03			BTFSS	STATUS, Z
$0744	$2F4F			GOTO	I2C_c34_L_11
$0745	$	I2C_c34_L_10:
;I2C_c34.ppas,25 :: 		
$0745	$301F			MOVLW	31
$0746	$0511			ANDWF	SSPCON2, 0
$0747	$00F1			MOVWF	STACK_1
$0748	$0871			MOVF	STACK_1, 0
$0749	$3A00			XORLW	0
$074A	$1D03			BTFSS	STATUS, Z
$074B	$2F4F			GOTO	I2C_c34_L_14
$074C	$	I2C_c34_L_13:
$074C	$30FF			MOVLW	255
$074D	$1283			BCF	STATUS, RP0
$074E	$00C5			MOVWF	_i2c_is_idle_local_result
$074F	$	I2C_c34_L_14:
$074F	$	I2C_c34_L_15:
$074F	$	I2C_c34_L_11:
$074F	$	I2C_c34_L_12:
$074F	$	I2C_c34_L_9:
;I2C_c34.ppas,26 :: 		
$074F	$1303			BCF	STATUS, RP1
$0750	$1283			BCF	STATUS, RP0
$0751	$1303			BCF	STATUS, RP1
$0752	$1283			BCF	STATUS, RP0
$0753	$0845			MOVF	_i2c_is_idle_local_result, 0
$0754	$00F0			MOVWF	STACK_0
$0755	$0008			RETURN
$070A	$	_div_16x16_s_l:
$070A	$1303			BCF	STATUS, RP1
$070B	$1283			BCF	STATUS, RP0
;math.ppas,291 :: 		
;math.ppas,293 :: 		
$070C	$0D71			RLF	STACK_1, W
;math.ppas,294 :: 		
$070D	$0DF8			RLF	STACK_8, F
;math.ppas,295 :: 		
$070E	$0DF9			RLF	STACK_9, F
;math.ppas,296 :: 		
$070F	$0874			MOVF	STACK_4, W
;math.ppas,297 :: 		
$0710	$02F8			SUBWF	STACK_8, F
;math.ppas,298 :: 		
$0711	$0875			MOVF	STACK_5, W
;math.ppas,299 :: 		
$0712	$1C03			BTFSS	STATUS, C
;math.ppas,300 :: 		
$0713	$0F75			INCFSZ	STACK_5, W
;math.ppas,301 :: 		
$0714	$02F9			SUBWF	STACK_9, F
;math.ppas,302 :: 		
$0715	$0DF0			RLF	STACK_0, F
;math.ppas,304 :: 		
$0716	$0DF1			RLF	STACK_1, F
;math.ppas,305 :: 		
$0717	$300F			MOVLW	15
;math.ppas,307 :: 		
$0718	$00FC			MOVWF	STACK_12
;math.ppas,308 :: 		
$0719	$0D71			RLF	STACK_1, W
;math.ppas,309 :: 		
$071A	$0DF8			RLF	STACK_8, F
;math.ppas,310 :: 		
$071B	$0DF9			RLF	STACK_9, F
;math.ppas,312 :: 		
$071C	$0874			MOVF	STACK_4, W
;math.ppas,313 :: 		
$071D	$1C70			BTFSS	STACK_0, 0
;math.ppas,314 :: 		
$071E	$2F25			GOTO	$+7
;math.ppas,315 :: 		
$071F	$02F8			SUBWF	STACK_8, F
;math.ppas,316 :: 		
$0720	$0875			MOVF	STACK_5, W
;math.ppas,317 :: 		
$0721	$1C03			BTFSS	STATUS, C
;math.ppas,318 :: 		
$0722	$0F75			INCFSZ	STACK_5, W
;math.ppas,319 :: 		
$0723	$02F9			SUBWF	STACK_9, F
;math.ppas,321 :: 		
$0724	$2F2A			GOTO	$+6
;math.ppas,322 :: 		
$0725	$07F8			ADDWF	STACK_8, F
;math.ppas,323 :: 		
$0726	$0875			MOVF	STACK_5, W
;math.ppas,324 :: 		
$0727	$1803			BTFSC	STATUS, C
;math.ppas,325 :: 		
$0728	$0F75			INCFSZ	STACK_5, W
;math.ppas,327 :: 		
$0729	$07F9			ADDWF	STACK_9, F
;math.ppas,328 :: 		
$072A	$0DF0			RLF	STACK_0, F
;math.ppas,330 :: 		
$072B	$0DF1			RLF	STACK_1, F
;math.ppas,331 :: 		
$072C	$0BFC			DECFSZ	STACK_12, F
;math.ppas,333 :: 		
$072D	$2F19			GOTO	$-20
;math.ppas,334 :: 		
$072E	$1870			BTFSC	STACK_0, 0
;math.ppas,335 :: 		
$072F	$2F36			GOTO	$+7
;math.ppas,336 :: 		
$0730	$0874			MOVF	STACK_4, W
;math.ppas,337 :: 		
$0731	$07F8			ADDWF	STACK_8, F
;math.ppas,338 :: 		
$0732	$0875			MOVF	STACK_5, W
;math.ppas,339 :: 		
$0733	$1803			BTFSC	STATUS, C
;math.ppas,340 :: 		
$0734	$0F75			INCFSZ	STACK_5, W
;math.ppas,341 :: 		
$0735	$07F9			ADDWF	STACK_9, F
;math.ppas,342 :: 		
$0736	$	math_L_6:
;math.ppas,343 :: 		
$0736	$0008			RETURN
$059B	$	_usart_read_text:
;USART_c67.ppas,78 :: 		
;USART_c67.ppas,79 :: 		
$059B	$1303			BCF	STATUS, RP1
$059C	$1283			BCF	STATUS, RP0
$059D	$01BA			CLRF	_usart_read_text_local_i, 1
;USART_c67.ppas,80 :: 		
$059E	$01BB			CLRF	_usart_read_text_local_j, 1
;USART_c67.ppas,81 :: 		
$059F	$01BE			CLRF	_usart_read_text_local_lasti, 1
;USART_c67.ppas,82 :: 		
$05A0	$0839			MOVF	FARG_Usart_Read_Text+1, 0
$05A1	$0084			MOVWF	FSR
$05A2	$0800			MOVF	INDF, 0
$05A3	$00BD			MOVWF	_usart_read_text_local_data2
;USART_c67.ppas,83 :: 		
$05A4	$	USART_c67_L_29:
;USART_c67.ppas,85 :: 		
$05A4	$158A			BSF	PCLATH, 3
$05A5	$206D			CALL	_usart_data_ready
$05A6	$118A			BCF	PCLATH, 3
$05A7	$0870			MOVF	STACK_0, 0
$05A8	$3A00			XORLW	0
$05A9	$1903			BTFSC	STATUS, Z
$05AA	$2DD8			GOTO	USART_c67_L_34
$05AB	$	USART_c67_L_33:
;USART_c67.ppas,87 :: 		
$05AB	$158A			BSF	PCLATH, 3
$05AC	$2048			CALL	_usart_read
$05AD	$118A			BCF	PCLATH, 3
$05AE	$0870			MOVF	STACK_0, 0
$05AF	$00BC			MOVWF	_usart_read_text_local_data
;USART_c67.ppas,88 :: 		
$05B0	$083A			MOVF	_usart_read_text_local_i, 0
$05B1	$0738			ADDWF	FARG_Usart_Read_Text, 0
$05B2	$00F1			MOVWF	STACK_1
$05B3	$0871			MOVF	STACK_1, 0
$05B4	$0084			MOVWF	FSR
$05B5	$0871			MOVF	STACK_1, 0
$05B6	$0084			MOVWF	FSR
$05B7	$0870			MOVF	STACK_0, 0
$05B8	$0080			MOVWF	INDF
;USART_c67.ppas,89 :: 		
$05B9	$083C			MOVF	_usart_read_text_local_data, 0
$05BA	$063D			XORWF	_usart_read_text_local_data2, 0
$05BB	$1D03			BTFSS	STATUS, Z
$05BC	$2DC2			GOTO	USART_c67_L_37
$05BD	$	USART_c67_L_36:
;USART_c67.ppas,91 :: 		
$05BD	$083B			MOVF	_usart_read_text_local_j, 0
$05BE	$023A			SUBWF	_usart_read_text_local_i, 0
$05BF	$00BE			MOVWF	_usart_read_text_local_lasti
;USART_c67.ppas,92 :: 		
$05C0	$0ABB			INCF	_usart_read_text_local_j, 1
;USART_c67.ppas,93 :: 		
$05C1	$2DC4			GOTO	USART_c67_L_38
;USART_c67.ppas,94 :: 		
$05C2	$	USART_c67_L_37:
;USART_c67.ppas,96 :: 		
$05C2	$01BB			CLRF	_usart_read_text_local_j, 1
;USART_c67.ppas,97 :: 		
$05C3	$01BE			CLRF	_usart_read_text_local_lasti, 1
;USART_c67.ppas,98 :: 		
$05C4	$	USART_c67_L_38:
;USART_c67.ppas,100 :: 		
$05C4	$083B			MOVF	_usart_read_text_local_j, 0
$05C5	$0739			ADDWF	FARG_Usart_Read_Text+1, 0
$05C6	$0084			MOVWF	FSR
$05C7	$0800			MOVF	INDF, 0
$05C8	$00F1			MOVWF	STACK_1
$05C9	$0871			MOVF	STACK_1, 0
$05CA	$00BD			MOVWF	_usart_read_text_local_data2
;USART_c67.ppas,102 :: 		
$05CB	$0871			MOVF	STACK_1, 0
$05CC	$3A00			XORLW	0
$05CD	$1D03			BTFSS	STATUS, Z
$05CE	$2DD0			GOTO	USART_c67_L_40
$05CF	$	USART_c67_L_39:
;USART_c67.ppas,103 :: 		
$05CF	$2DD9			GOTO	USART_c67_L_30
$05D0	$	USART_c67_L_40:
$05D0	$	USART_c67_L_41:
;USART_c67.ppas,105 :: 		
$05D0	$0ABA			INCF	_usart_read_text_local_i, 1
;USART_c67.ppas,106 :: 		
$05D1	$083A			MOVF	_usart_read_text_local_i, 0
$05D2	$3C14			SUBLW	20
$05D3	$1803			BTFSC	STATUS, C
$05D4	$2DD8			GOTO	USART_c67_L_43
$05D5	$	USART_c67_L_42:
;USART_c67.ppas,108 :: 		
$05D5	$3013			MOVLW	19
$05D6	$00BE			MOVWF	_usart_read_text_local_lasti
;USART_c67.ppas,109 :: 		
$05D7	$2DD9			GOTO	USART_c67_L_30
;USART_c67.ppas,110 :: 		
$05D8	$	USART_c67_L_43:
$05D8	$	USART_c67_L_44:
;USART_c67.ppas,111 :: 		
$05D8	$	USART_c67_L_34:
$05D8	$	USART_c67_L_35:
;USART_c67.ppas,112 :: 		
$05D8	$2DA4			GOTO	USART_c67_L_29
$05D9	$	USART_c67_L_30:
;USART_c67.ppas,113 :: 		
$05D9	$083E			MOVF	_usart_read_text_local_lasti, 0
$05DA	$0738			ADDWF	FARG_Usart_Read_Text, 0
$05DB	$00F0			MOVWF	STACK_0
$05DC	$0870			MOVF	STACK_0, 0
$05DD	$0084			MOVWF	FSR
$05DE	$0870			MOVF	STACK_0, 0
$05DF	$0084			MOVWF	FSR
$05E0	$0180			CLRF	INDF, 1
$05E1	$	USART_c67_L_27:
;USART_c67.ppas,114 :: 		
$05E1	$0008			RETURN
$03E3	$	_strtoint:
;conv.ppas,343 :: 		
;conv.ppas,345 :: 		
$03E3	$1303			BCF	STATUS, RP1
$03E4	$1283			BCF	STATUS, RP0
$03E5	$01B9			CLRF	_strtoint_local_result
$03E6	$01BA			CLRF	_strtoint_local_result+1
;conv.ppas,346 :: 		
$03E7	$3010			MOVLW	16
$03E8	$00BD			MOVWF	_strtoint_local_ep
$03E9	$3027			MOVLW	39
$03EA	$00BE			MOVWF	_strtoint_local_ep+1
;conv.ppas,347 :: 		
$03EB	$01BB			CLRF	_strtoint_local_i
$03EC	$01BC			CLRF	_strtoint_local_i+1
;conv.ppas,348 :: 		
$03ED	$01C1			CLRF	_strtoint_local_tmp
$03EE	$01C2			CLRF	_strtoint_local_tmp+1
$03EF	$01C3			CLRF	_strtoint_local_tmp+2
$03F0	$01C4			CLRF	_strtoint_local_tmp+3
;conv.ppas,349 :: 		
$03F1	$01BF			CLRF	_strtoint_local_negative
$03F2	$01C0			CLRF	_strtoint_local_negative+1
;conv.ppas,353 :: 		
$03F3	$	conv_L_172:
$03F3	$083B			MOVF	_strtoint_local_i, 0
$03F4	$0738			ADDWF	FARG_StrToInt, 0
$03F5	$0084			MOVWF	FSR
$03F6	$0800			MOVF	INDF, 0
$03F7	$00F4			MOVWF	STACK_4
$03F8	$0874			MOVF	STACK_4, 0
$03F9	$3A00			XORLW	0
$03FA	$1903			BTFSC	STATUS, Z
$03FB	$2C61			GOTO	conv_L_173
;conv.ppas,355 :: 		
$03FC	$083B			MOVF	_strtoint_local_i, 0
$03FD	$0738			ADDWF	FARG_StrToInt, 0
$03FE	$0084			MOVWF	FSR
$03FF	$0800			MOVF	INDF, 0
$0400	$00F4			MOVWF	STACK_4
$0401	$0874			MOVF	STACK_4, 0
$0402	$3A2D			XORLW	45
$0403	$1D03			BTFSS	STATUS, Z
$0404	$2C0C			GOTO	conv_L_177
$0405	$	conv_L_176:
;conv.ppas,357 :: 		
$0405	$30FF			MOVLW	255
$0406	$00BF			MOVWF	_strtoint_local_negative
$0407	$01C0			CLRF	_strtoint_local_negative+1
;conv.ppas,358 :: 		
$0408	$0ABB			INCF	_strtoint_local_i, 1
$0409	$1903			BTFSC	STATUS, Z
$040A	$0ABC			INCF	_strtoint_local_i+1, 1
;conv.ppas,359 :: 		
$040B	$2BF3			GOTO	conv_L_172
;conv.ppas,360 :: 		
$040C	$	conv_L_177:
$040C	$	conv_L_178:
;conv.ppas,361 :: 		
$040C	$083B			MOVF	_strtoint_local_i, 0
$040D	$0738			ADDWF	FARG_StrToInt, 0
$040E	$0084			MOVWF	FSR
$040F	$0800			MOVF	INDF, 0
$0410	$00F4			MOVWF	STACK_4
$0411	$0874			MOVF	STACK_4, 0
$0412	$3A20			XORLW	32
$0413	$1903			BTFSC	STATUS, Z
$0414	$2C4F			GOTO	conv_L_180
$0415	$	conv_L_179:
;conv.ppas,362 :: 		
$0415	$083B			MOVF	_strtoint_local_i, 0
$0416	$0738			ADDWF	FARG_StrToInt, 0
$0417	$0084			MOVWF	FSR
$0418	$0800			MOVF	INDF, 0
$0419	$00F0			MOVWF	STACK_0
$041A	$3030			MOVLW	48
$041B	$00F8			MOVWF	STACK_8
$041C	$01F9			CLRF	STACK_8+1
$041D	$01FA			CLRF	STACK_8+2
$041E	$01FB			CLRF	STACK_8+3
$041F	$0870			MOVF	STACK_0, 0
$0420	$00F4			MOVWF	STACK_4
$0421	$01F5			CLRF	STACK_4+1
$0422	$01F6			CLRF	STACK_4+2
$0423	$01F7			CLRF	STACK_4+3
$0424	$0874			MOVF	STACK_4, 0
$0425	$00F0			MOVWF	STACK_0
$0426	$0875			MOVF	STACK_4+1, 0
$0427	$00F1			MOVWF	STACK_0+1
$0428	$0876			MOVF	STACK_4+2, 0
$0429	$00F2			MOVWF	STACK_0+2
$042A	$0877			MOVF	STACK_4+3, 0
$042B	$00F3			MOVWF	STACK_0+3
$042C	$0878			MOVF	STACK_8, 0
$042D	$02F0			SUBWF	STACK_0, 1
$042E	$0879			MOVF	STACK_8+1, 0
$042F	$1C03			BTFSS	STATUS, C
$0430	$0F79			INCFSZ	STACK_8+1, 0
$0431	$02F1			SUBWF	STACK_0+1, 1
$0432	$087A			MOVF	STACK_8+2, 0
$0433	$1C03			BTFSS	STATUS, C
$0434	$0F7A			INCFSZ	STACK_8+2, 0
$0435	$02F2			SUBWF	STACK_0+2, 1
$0436	$087B			MOVF	STACK_8+3, 0
$0437	$1C03			BTFSS	STATUS, C
$0438	$0F7B			INCFSZ	STACK_8+3, 0
$0439	$02F3			SUBWF	STACK_0+3, 1
$043A	$083D			MOVF	_strtoint_local_ep, 0
$043B	$00F4			MOVWF	STACK_4
$043C	$083E			MOVF	_strtoint_local_ep+1, 0
$043D	$00F5			MOVWF	STACK_4+1
$043E	$01F6			CLRF	STACK_4+2
$043F	$01F7			CLRF	STACK_4+3
$0440	$262B			CALL	_mul_32x32_s
$0441	$0870			MOVF	STACK_0, 0
$0442	$07C1			ADDWF	_strtoint_local_tmp, 1
$0443	$0871			MOVF	STACK_0+1, 0
$0444	$1803			BTFSC	STATUS, C
$0445	$0F71			INCFSZ	STACK_0+1, 0
$0446	$07C2			ADDWF	_strtoint_local_tmp+1, 1
$0447	$0872			MOVF	STACK_0+2, 0
$0448	$1803			BTFSC	STATUS, C
$0449	$0F72			INCFSZ	STACK_0+2, 0
$044A	$07C3			ADDWF	_strtoint_local_tmp+2, 1
$044B	$0873			MOVF	STACK_0+3, 0
$044C	$1803			BTFSC	STATUS, C
$044D	$0F73			INCFSZ	STACK_0+3, 0
$044E	$07C4			ADDWF	_strtoint_local_tmp+3, 1
$044F	$	conv_L_180:
$044F	$	conv_L_181:
;conv.ppas,363 :: 		
$044F	$300A			MOVLW	10
$0450	$00F4			MOVWF	STACK_4
$0451	$01F5			CLRF	STACK_4+1
$0452	$083D			MOVF	_strtoint_local_ep, 0
$0453	$00F0			MOVWF	STACK_0
$0454	$083E			MOVF	_strtoint_local_ep+1, 0
$0455	$00F1			MOVWF	STACK_0+1
$0456	$158A			BSF	PCLATH, 3
$0457	$2000			CALL	_div_16x16_u
$0458	$118A			BCF	PCLATH, 3
$0459	$0870			MOVF	STACK_0, 0
$045A	$00BD			MOVWF	_strtoint_local_ep
$045B	$0871			MOVF	STACK_0+1, 0
$045C	$00BE			MOVWF	_strtoint_local_ep+1
;conv.ppas,365 :: 		
$045D	$0ABB			INCF	_strtoint_local_i, 1
$045E	$1903			BTFSC	STATUS, Z
$045F	$0ABC			INCF	_strtoint_local_i+1, 1
;conv.ppas,366 :: 		
$0460	$2BF3			GOTO	conv_L_172
$0461	$	conv_L_173:
;conv.ppas,370 :: 		
$0461	$083F			MOVF	_strtoint_local_negative, 0
$0462	$0440			IORWF	_strtoint_local_negative+1, 0
$0463	$1903			BTFSC	STATUS, Z
$0464	$2C69			GOTO	conv_L_183
$0465	$	conv_L_182:
$0465	$3006			MOVLW	6
$0466	$00BD			MOVWF	_strtoint_local_ep
$0467	$01BE			CLRF	_strtoint_local_ep+1
$0468	$2C6C			GOTO	conv_L_184
;conv.ppas,371 :: 		
$0469	$	conv_L_183:
$0469	$3005			MOVLW	5
$046A	$00BD			MOVWF	_strtoint_local_ep
$046B	$01BE			CLRF	_strtoint_local_ep+1
$046C	$	conv_L_184:
;conv.ppas,373 :: 		
$046C	$	conv_L_186:
$046C	$083C			MOVF	_strtoint_local_i+1, 0
$046D	$063E			XORWF	_strtoint_local_ep+1, 0
$046E	$1D03			BTFSS	STATUS, Z
$046F	$2C72			GOTO	L_StrToInt_20
$0470	$083D			MOVF	_strtoint_local_ep, 0
$0471	$063B			XORWF	_strtoint_local_i, 0
$0472	$	L_StrToInt_20:
$0472	$1903			BTFSC	STATUS, Z
$0473	$2C8E			GOTO	conv_L_187
;conv.ppas,375 :: 		
$0474	$300A			MOVLW	10
$0475	$00F4			MOVWF	STACK_4
$0476	$01F5			CLRF	STACK_4+1
$0477	$01F6			CLRF	STACK_4+2
$0478	$01F7			CLRF	STACK_4+3
$0479	$0841			MOVF	_strtoint_local_tmp, 0
$047A	$00F0			MOVWF	STACK_0
$047B	$0842			MOVF	_strtoint_local_tmp+1, 0
$047C	$00F1			MOVWF	STACK_0+1
$047D	$0843			MOVF	_strtoint_local_tmp+2, 0
$047E	$00F2			MOVWF	STACK_0+2
$047F	$0844			MOVF	_strtoint_local_tmp+3, 0
$0480	$00F3			MOVWF	STACK_0+3
$0481	$24A7			CALL	_div_32x32_s
$0482	$0870			MOVF	STACK_0, 0
$0483	$00C1			MOVWF	_strtoint_local_tmp
$0484	$0871			MOVF	STACK_0+1, 0
$0485	$00C2			MOVWF	_strtoint_local_tmp+1
$0486	$0872			MOVF	STACK_0+2, 0
$0487	$00C3			MOVWF	_strtoint_local_tmp+2
$0488	$0873			MOVF	STACK_0+3, 0
$0489	$00C4			MOVWF	_strtoint_local_tmp+3
;conv.ppas,376 :: 		
$048A	$0ABB			INCF	_strtoint_local_i, 1
$048B	$1903			BTFSC	STATUS, Z
$048C	$0ABC			INCF	_strtoint_local_i+1, 1
;conv.ppas,377 :: 		
$048D	$2C6C			GOTO	conv_L_186
$048E	$	conv_L_187:
;conv.ppas,380 :: 		
$048E	$0841			MOVF	_strtoint_local_tmp, 0
$048F	$00B9			MOVWF	_strtoint_local_result
$0490	$0842			MOVF	_strtoint_local_tmp+1, 0
$0491	$00BA			MOVWF	_strtoint_local_result+1
;conv.ppas,382 :: 		
$0492	$3000			MOVLW	0
$0493	$0640			XORWF	_strtoint_local_negative+1, 0
$0494	$1D03			BTFSS	STATUS, Z
$0495	$2C98			GOTO	L_StrToInt_21
$0496	$30FF			MOVLW	255
$0497	$063F			XORWF	_strtoint_local_negative, 0
$0498	$	L_StrToInt_21:
$0498	$1D03			BTFSS	STATUS, Z
$0499	$2CA2			GOTO	conv_L_191
$049A	$	conv_L_190:
;conv.ppas,383 :: 		
$049A	$0839			MOVF	_strtoint_local_result, 0
$049B	$3C00			SUBLW	0
$049C	$00B9			MOVWF	_strtoint_local_result
$049D	$083A			MOVF	_strtoint_local_result+1, 0
$049E	$1C03			BTFSS	STATUS, C
$049F	$3F01			ADDLW	1
$04A0	$01BA			CLRF	_strtoint_local_result+1
$04A1	$02BA			SUBWF	_strtoint_local_result+1, 1
$04A2	$	conv_L_191:
$04A2	$	conv_L_192:
$04A2	$	conv_L_170:
;conv.ppas,384 :: 		
$04A2	$0839			MOVF	_strtoint_local_result, 0
$04A3	$00F0			MOVWF	STACK_0
$04A4	$083A			MOVF	_strtoint_local_result+1, 0
$04A5	$00F1			MOVWF	STACK_0+1
$04A6	$0008			RETURN
$081D	$	_usart_write_text:
;USART_c67.ppas,121 :: 		
;USART_c67.ppas,122 :: 		
$081D	$1303			BCF	STATUS, RP1
$081E	$1283			BCF	STATUS, RP0
$081F	$01B9			CLRF	_usart_write_text_local_i, 1
;USART_c67.ppas,123 :: 		
$0820	$0838			MOVF	FARG_Usart_Write_Text, 0
$0821	$0084			MOVWF	FSR
$0822	$0800			MOVF	INDF, 0
$0823	$00BA			MOVWF	_usart_write_text_local_data
;USART_c67.ppas,124 :: 		
$0824	$	USART_c67_L_47:
$0824	$083A			MOVF	_usart_write_text_local_data, 0
$0825	$3A00			XORLW	0
$0826	$1903			BTFSC	STATUS, Z
$0827	$2832			GOTO	USART_c67_L_48
;USART_c67.ppas,126 :: 		
$0828	$083A			MOVF	_usart_write_text_local_data, 0
$0829	$00C5			MOVWF	FARG_USART_Write
$082A	$205B			CALL	_usart_write
;USART_c67.ppas,127 :: 		
$082B	$0AB9			INCF	_usart_write_text_local_i, 1
;USART_c67.ppas,128 :: 		
$082C	$0839			MOVF	_usart_write_text_local_i, 0
$082D	$0738			ADDWF	FARG_Usart_Write_Text, 0
$082E	$0084			MOVWF	FSR
$082F	$0800			MOVF	INDF, 0
$0830	$00BA			MOVWF	_usart_write_text_local_data
;USART_c67.ppas,129 :: 		
$0831	$2824			GOTO	USART_c67_L_47
$0832	$	USART_c67_L_48:
$0832	$	USART_c67_L_45:
;USART_c67.ppas,130 :: 		
$0832	$0008			RETURN
$0666	$	_i2c_start:
;I2C_c34.ppas,34 :: 		
;I2C_c34.ppas,35 :: 		
$0666	$1303			BCF	STATUS, RP1
$0667	$1283			BCF	STATUS, RP0
$0668	$01B9			CLRF	_i2c_start_local_j
$0669	$01BA			CLRF	_i2c_start_local_j+1
$066A	$	I2C_c34_L_17:
$066A	$083A			MOVF	_i2c_start_local_j+1, 0
$066B	$3C12			SUBLW	18
$066C	$1D03			BTFSS	STATUS, Z
$066D	$2E70			GOTO	L_I2C_Start_0
$066E	$0839			MOVF	_i2c_start_local_j, 0
$066F	$3C8E			SUBLW	142
$0670	$	L_I2C_Start_0:
$0670	$1C03			BTFSS	STATUS, C
$0671	$2E84			GOTO	I2C_c34_L_20
;I2C_c34.ppas,36 :: 		
$0672	$2737			CALL	_i2c_is_idle
$0673	$0870			MOVF	STACK_0, 0
$0674	$3A00			XORLW	0
$0675	$1903			BTFSC	STATUS, Z
$0676	$2E78			GOTO	I2C_c34_L_22
$0677	$	I2C_c34_L_21:
;I2C_c34.ppas,37 :: 		
$0677	$2E84			GOTO	I2C_c34_L_20
$0678	$	I2C_c34_L_22:
$0678	$	I2C_c34_L_23:
$0678	$083A			MOVF	_i2c_start_local_j+1, 0
$0679	$3A12			XORLW	18
$067A	$1D03			BTFSS	STATUS, Z
$067B	$2E7E			GOTO	L_I2C_Start_1
$067C	$308E			MOVLW	142
$067D	$0639			XORWF	_i2c_start_local_j, 0
$067E	$	L_I2C_Start_1:
$067E	$1903			BTFSC	STATUS, Z
$067F	$2E84			GOTO	I2C_c34_L_20
$0680	$	I2C_c34_L_18:
$0680	$0AB9			INCF	_i2c_start_local_j, 1
$0681	$1903			BTFSC	STATUS, Z
$0682	$0ABA			INCF	_i2c_start_local_j+1, 1
$0683	$2E6A			GOTO	I2C_c34_L_17
$0684	$	I2C_c34_L_20:
;I2C_c34.ppas,39 :: 		
$0684	$3012			MOVLW	18
$0685	$023A			SUBWF	_i2c_start_local_j+1, 0
$0686	$1D03			BTFSS	STATUS, Z
$0687	$2E8A			GOTO	L_I2C_Start_2
$0688	$308F			MOVLW	143
$0689	$0239			SUBWF	_i2c_start_local_j, 0
$068A	$	L_I2C_Start_2:
$068A	$1C03			BTFSS	STATUS, C
$068B	$2E8F			GOTO	I2C_c34_L_25
$068C	$	I2C_c34_L_24:
;I2C_c34.ppas,40 :: 		
$068C	$307B			MOVLW	123
$068D	$00B8			MOVWF	_i2c_start_local_result
$068E	$2E9D			GOTO	I2C_c34_L_26
;I2C_c34.ppas,41 :: 		
$068F	$	I2C_c34_L_25:
;I2C_c34.ppas,42 :: 		
$068F	$	I2C_c34_L_27:
$068F	$1683			BSF	STATUS, RP0
$0690	$1411			BSF	SSPCON2, 0
$0691	$	I2C_c34_L_28:
;I2C_c34.ppas,43 :: 		
$0691	$	I2C_c34_L_30:
$0691	$0811			MOVF	SSPCON2, 0
$0692	$00F1			MOVWF	STACK_1
$0693	$3001			MOVLW	1
$0694	$05F1			ANDWF	STACK_1, 1
$0695	$0871			MOVF	STACK_1, 0
$0696	$3A00			XORLW	0
$0697	$1903			BTFSC	STATUS, Z
$0698	$2E9B			GOTO	I2C_c34_L_31
;I2C_c34.ppas,44 :: 		
$0699	$0000			NOP
$069A	$2E91			GOTO	I2C_c34_L_30
$069B	$	I2C_c34_L_31:
;I2C_c34.ppas,45 :: 		
$069B	$1283			BCF	STATUS, RP0
$069C	$01B8			CLRF	_i2c_start_local_result, 1
;I2C_c34.ppas,46 :: 		
$069D	$	I2C_c34_L_26:
$069D	$	I2C_c34_L_16:
;I2C_c34.ppas,47 :: 		
$069D	$0838			MOVF	_i2c_start_local_result, 0
$069E	$00F0			MOVWF	STACK_0
$069F	$0008			RETURN
$06D7	$	_i2c_wr:
;I2C_c34.ppas,81 :: 		
;I2C_c34.ppas,82 :: 		
$06D7	$1303			BCF	STATUS, RP1
$06D8	$1283			BCF	STATUS, RP0
$06D9	$0838			MOVF	FARG_I2C_Wr, 0
$06DA	$0093			MOVWF	SSPBUF
;I2C_c34.ppas,83 :: 		
$06DB	$118C			BCF	PIR1, 3
$06DC	$	I2C_c34_L_70:
;I2C_c34.ppas,84 :: 		
$06DC	$	I2C_c34_L_72:
$06DC	$1683			BSF	STATUS, RP0
$06DD	$0814			MOVF	SSPSTAT, 0
$06DE	$00F1			MOVWF	STACK_1
$06DF	$3000			MOVLW	0
$06E0	$1971			BTFSC	STACK_1, 2
$06E1	$3001			MOVLW	1
$06E2	$00F1			MOVWF	STACK_1
$06E3	$0871			MOVF	STACK_1, 0
$06E4	$3A00			XORLW	0
$06E5	$1D03			BTFSS	STATUS, Z
$06E6	$2EDC			GOTO	I2C_c34_L_72
$06E7	$	I2C_c34_L_73:
;I2C_c34.ppas,85 :: 		
$06E7	$	I2C_c34_L_77:
$06E7	$1283			BCF	STATUS, RP0
$06E8	$080C			MOVF	PIR1, 0
$06E9	$00F1			MOVWF	STACK_1
$06EA	$3000			MOVLW	0
$06EB	$19F1			BTFSC	STACK_1, 3
$06EC	$3001			MOVLW	1
$06ED	$00F1			MOVWF	STACK_1
$06EE	$0871			MOVF	STACK_1, 0
$06EF	$3A00			XORLW	0
$06F0	$1903			BTFSC	STATUS, Z
$06F1	$2EE7			GOTO	I2C_c34_L_77
$06F2	$	I2C_c34_L_78:
;I2C_c34.ppas,86 :: 		
$06F2	$1683			BSF	STATUS, RP0
$06F3	$0811			MOVF	SSPCON2, 0
$06F4	$00F1			MOVWF	STACK_1
$06F5	$3000			MOVLW	0
$06F6	$1B71			BTFSC	STACK_1, 6
$06F7	$3001			MOVLW	1
$06F8	$00F1			MOVWF	STACK_1
$06F9	$0871			MOVF	STACK_1, 0
$06FA	$3A00			XORLW	0
$06FB	$1D03			BTFSS	STATUS, Z
$06FC	$2F00			GOTO	I2C_c34_L_82
$06FD	$	I2C_c34_L_81:
$06FD	$1283			BCF	STATUS, RP0
$06FE	$01B9			CLRF	_i2c_wr_local_result, 1
$06FF	$2F07			GOTO	I2C_c34_L_83
;I2C_c34.ppas,87 :: 		
$0700	$	I2C_c34_L_82:
;I2C_c34.ppas,88 :: 		
$0700	$	I2C_c34_L_84:
$0700	$1303			BCF	STATUS, RP1
$0701	$1283			BCF	STATUS, RP0
$0702	$1683			BSF	STATUS, RP0
$0703	$1511			BSF	SSPCON2, 2
$0704	$	I2C_c34_L_85:
;I2C_c34.ppas,89 :: 		
$0704	$3002			MOVLW	2
$0705	$1283			BCF	STATUS, RP0
$0706	$00B9			MOVWF	_i2c_wr_local_result
;I2C_c34.ppas,90 :: 		
$0707	$	I2C_c34_L_83:
$0707	$	I2C_c34_L_68:
;I2C_c34.ppas,91 :: 		
$0707	$0839			MOVF	_i2c_wr_local_result, 0
$0708	$00F0			MOVWF	STACK_0
$0709	$0008			RETURN
$0884	$	_i2c_stop:
;I2C_c34.ppas,97 :: 		
;I2C_c34.ppas,98 :: 		
$0884	$	I2C_c34_L_87:
$0884	$1303			BCF	STATUS, RP1
$0885	$1683			BSF	STATUS, RP0
$0886	$1511			BSF	SSPCON2, 2
$0887	$	I2C_c34_L_88:
$0887	$	I2C_c34_L_86:
;I2C_c34.ppas,99 :: 		
$0887	$0008			RETURN
$0833	$	_usart_init:
;USART_c67.ppas,22 :: 		
;USART_c67.ppas,24 :: 		
$0833	$	USART_c67_L_1:
$0833	$1303			BCF	STATUS, RP1
$0834	$1683			BSF	STATUS, RP0
$0835	$1698			BSF	TXSTA, 5
$0836	$	USART_c67_L_2:
;USART_c67.ppas,25 :: 		
$0836	$3090			MOVLW	144
$0837	$1283			BCF	STATUS, RP0
$0838	$0098			MOVWF	RCSTA
;USART_c67.ppas,31 :: 		
$0839	$	USART_c67_L_3:
$0839	$1683			BSF	STATUS, RP0
$083A	$1787			BSF	TRISC, 7
$083B	$	USART_c67_L_4:
;USART_c67.ppas,32 :: 		
$083B	$1307			BCF	TRISC, 6
$083C	$	USART_c67_L_6:
;USART_c67.ppas,35 :: 		
$083C	$	USART_c67_L_8:
$083C	$1283			BCF	STATUS, RP0
$083D	$080C			MOVF	PIR1, 0
$083E	$00F1			MOVWF	STACK_1
$083F	$3000			MOVLW	0
$0840	$1AF1			BTFSC	STACK_1, 5
$0841	$3001			MOVLW	1
$0842	$00F1			MOVWF	STACK_1
$0843	$0871			MOVF	STACK_1, 0
$0844	$3A01			XORLW	1
$0845	$1903			BTFSC	STATUS, Z
$0846	$283C			GOTO	USART_c67_L_8
;USART_c67.ppas,36 :: 		
$0847	$	USART_c67_L_9:
$0847	$	USART_c67_L_0:
;USART_c67.ppas,37 :: 		
$0847	$0008			RETURN
$087A	$	_i2c_init:
;I2C_c34.ppas,8 :: 		
;I2C_c34.ppas,9 :: 		
$087A	$1303			BCF	STATUS, RP1
$087B	$1683			BSF	STATUS, RP0
$087C	$1314			BCF	SSPSTAT, 6
$087D	$	I2C_c34_L_2:
;I2C_c34.ppas,10 :: 		
$087D	$1394			BCF	SSPSTAT, 7
$087E	$	I2C_c34_L_4:
;I2C_c34.ppas,11 :: 		
$087E	$	I2C_c34_L_5:
$087E	$1607			BSF	TRISC, 4
$087F	$	I2C_c34_L_6:
;I2C_c34.ppas,12 :: 		
$087F	$	I2C_c34_L_7:
$087F	$1587			BSF	TRISC, 3
$0880	$	I2C_c34_L_8:
;I2C_c34.ppas,13 :: 		
$0880	$3038			MOVLW	56
$0881	$1283			BCF	STATUS, RP0
$0882	$0094			MOVWF	SSPCON
$0883	$	I2C_c34_L_0:
;I2C_c34.ppas,15 :: 		
$0883	$0008			RETURN
$05E2	$	_mul_16x16_s:
$05E2	$1303			BCF	STATUS, RP1
$05E3	$1283			BCF	STATUS, RP0
;math.ppas,203 :: 		
;math.ppas,205 :: 		
$05E4	$01FB			CLRF	STACK_11
;math.ppas,206 :: 		
$05E5	$01FA			CLRF	STACK_10
;math.ppas,207 :: 		
$05E6	$01F9			CLRF	STACK_9
;math.ppas,208 :: 		
$05E7	$3080			MOVLW	128
;math.ppas,210 :: 		
$05E8	$00F8			MOVWF	STACK_8
;math.ppas,212 :: 		
$05E9	$01FD			CLRF	STACK_13
;math.ppas,213 :: 		
$05EA	$1FF1			BTFSS	STACK_1, 7
;math.ppas,214 :: 		
$05EB	$2DF2			GOTO	$+7
;math.ppas,215 :: 		
$05EC	$09F1			COMF	STACK_1, F
;math.ppas,216 :: 		
$05ED	$09F0			COMF	STACK_0, F
;math.ppas,217 :: 		
$05EE	$0AF0			INCF	STACK_0, F
;math.ppas,218 :: 		
$05EF	$1903			BTFSC	STATUS, Z
;math.ppas,219 :: 		
$05F0	$0AF1			INCF	STACK_1, F
;math.ppas,221 :: 		
$05F1	$0AFD			INCF	STACK_13, F
;math.ppas,222 :: 		
$05F2	$1FF5			BTFSS	STACK_5, 7
;math.ppas,223 :: 		
$05F3	$2DFA			GOTO	$+7
;math.ppas,224 :: 		
$05F4	$09F5			COMF	STACK_5, F
;math.ppas,225 :: 		
$05F5	$09F4			COMF	STACK_4, F
;math.ppas,226 :: 		
$05F6	$0AF4			INCF	STACK_4, F
;math.ppas,227 :: 		
$05F7	$1903			BTFSC	STATUS, Z
;math.ppas,228 :: 		
$05F8	$0AF5			INCF	STACK_5, F
;math.ppas,230 :: 		
$05F9	$0AFD			INCF	STACK_13, F
;math.ppas,231 :: 		
$05FA	$0CF1			RRF	STACK_1, F
;math.ppas,233 :: 		
$05FB	$0CF0			RRF	STACK_0, F
;math.ppas,234 :: 		
$05FC	$1C03			BTFSS	STATUS, C
;math.ppas,235 :: 		
$05FD	$2E07			GOTO	$+10
;math.ppas,236 :: 		
$05FE	$0874			MOVF	STACK_4, W
;math.ppas,238 :: 		
$05FF	$07F9			ADDWF	STACK_9, F
;math.ppas,239 :: 		
$0600	$0875			MOVF	STACK_5, W
;math.ppas,240 :: 		
$0601	$1803			BTFSC	STATUS, C
;math.ppas,241 :: 		
$0602	$0F75			INCFSZ	STACK_5, W
;math.ppas,242 :: 		
$0603	$07FA			ADDWF	STACK_10, F
;math.ppas,243 :: 		
$0604	$1803			BTFSC	STATUS, C
;math.ppas,244 :: 		
$0605	$0AFB			INCF	STACK_11, F
;math.ppas,246 :: 		
$0606	$1003			BCF	STATUS, C
;math.ppas,247 :: 		
$0607	$1FF0			BTFSS	STACK_0, 7
;math.ppas,248 :: 		
$0608	$2E0F			GOTO	$+7
;math.ppas,249 :: 		
$0609	$0874			MOVF	STACK_4, W
;math.ppas,250 :: 		
$060A	$07FA			ADDWF	STACK_10, F
;math.ppas,251 :: 		
$060B	$1803			BTFSC	STATUS, C
;math.ppas,252 :: 		
$060C	$0AFB			INCF	STACK_11, F
;math.ppas,253 :: 		
$060D	$0875			MOVF	STACK_5, W
;math.ppas,255 :: 		
$060E	$07FB			ADDWF	STACK_11, F
;math.ppas,256 :: 		
$060F	$0CFB			RRF	STACK_11, F
;math.ppas,257 :: 		
$0610	$0CFA			RRF	STACK_10, F
;math.ppas,258 :: 		
$0611	$0CF9			RRF	STACK_9, F
;math.ppas,260 :: 		
$0612	$0CF8			RRF	STACK_8, F
;math.ppas,261 :: 		
$0613	$1C03			BTFSS	STATUS, C
;math.ppas,262 :: 		
$0614	$2DFA			GOTO	$-26
;math.ppas,263 :: 		
$0615	$1C7D			BTFSS	STACK_13, 0
;math.ppas,265 :: 		
$0616	$2E22			GOTO	$+12
;math.ppas,266 :: 		
$0617	$09FB			COMF	STACK_11, F
;math.ppas,267 :: 		
$0618	$09FA			COMF	STACK_10, F
;math.ppas,268 :: 		
$0619	$09F9			COMF	STACK_9, F
;math.ppas,270 :: 		
$061A	$09F8			COMF	STACK_8, F
;math.ppas,271 :: 		
$061B	$0AF8			INCF	STACK_8, F
;math.ppas,272 :: 		
$061C	$1903			BTFSC	STATUS, Z
;math.ppas,273 :: 		
$061D	$0AF9			INCF	STACK_9, F
;math.ppas,274 :: 		
$061E	$1903			BTFSC	STATUS, Z
;math.ppas,275 :: 		
$061F	$0AFA			INCF	STACK_10, F
;math.ppas,276 :: 		
$0620	$1903			BTFSC	STATUS, Z
;math.ppas,278 :: 		
$0621	$0AFB			INCF	STACK_11, F
;math.ppas,279 :: 		
$0622	$087B			MOVF	STACK_11, W
;math.ppas,280 :: 		
$0623	$00F3			MOVWF	STACK_3
;math.ppas,281 :: 		
$0624	$087A			MOVF	STACK_10, W
;math.ppas,282 :: 		
$0625	$00F2			MOVWF	STACK_2
;math.ppas,283 :: 		
$0626	$0879			MOVF	STACK_9, W
;math.ppas,284 :: 		
$0627	$00F1			MOVWF	STACK_1
;math.ppas,285 :: 		
$0628	$0878			MOVF	STACK_8, W
;math.ppas,286 :: 		
$0629	$00F0			MOVWF	STACK_0
;math.ppas,287 :: 		
$062A	$	math_L_5:
;math.ppas,288 :: 		
$062A	$0008			RETURN
$0541	$	_div_16x16_s:
$0541	$1303			BCF	STATUS, RP1
$0542	$1283			BCF	STATUS, RP0
;math.ppas,346 :: 		
;math.ppas,348 :: 		
$0543	$01FD			CLRF	STACK_13
;math.ppas,349 :: 		
$0544	$01F9			CLRF	STACK_9
;math.ppas,350 :: 		
$0545	$01F8			CLRF	STACK_8
;math.ppas,351 :: 		
$0546	$0871			MOVF	STACK_1, W
;math.ppas,352 :: 		
$0547	$0470			IORWF	STACK_0, W
;math.ppas,353 :: 		
$0548	$1903			BTFSC	STATUS, Z
;math.ppas,355 :: 		
$0549	$3400			RETLW	0
;math.ppas,356 :: 		
$054A	$0871			MOVF	STACK_1, W
;math.ppas,357 :: 		
$054B	$0675			XORWF	STACK_5, W
;math.ppas,358 :: 		
$054C	$00FA			MOVWF	STACK_10
;math.ppas,359 :: 		
$054D	$1BFA			BTFSC	STACK_10, 7
;math.ppas,361 :: 		
$054E	$09FD			COMF	STACK_13, F
;math.ppas,363 :: 		
$054F	$01FB			CLRF	STACK_11
;math.ppas,364 :: 		
$0550	$1FF5			BTFSS	STACK_5, 7
;math.ppas,366 :: 		
$0551	$2D57			GOTO	$+6
;math.ppas,367 :: 		
$0552	$09F4			COMF	STACK_4, F
;math.ppas,368 :: 		
$0553	$09F5			COMF	STACK_5, F
;math.ppas,369 :: 		
$0554	$0AF4			INCF	STACK_4, F
;math.ppas,370 :: 		
$0555	$1903			BTFSC	STATUS, Z
;math.ppas,372 :: 		
$0556	$0AF5			INCF	STACK_5, F
;math.ppas,373 :: 		
$0557	$1FF1			BTFSS	STACK_1, 7
;math.ppas,375 :: 		
$0558	$2D5E			GOTO	$+6
;math.ppas,376 :: 		
$0559	$09F0			COMF	STACK_0, F
;math.ppas,377 :: 		
$055A	$09F1			COMF	STACK_1, F
;math.ppas,378 :: 		
$055B	$0AF0			INCF	STACK_0, F
;math.ppas,379 :: 		
$055C	$1903			BTFSC	STATUS, Z
;math.ppas,381 :: 		
$055D	$0AF1			INCF	STACK_1, F
;math.ppas,382 :: 		
$055E	$0871			MOVF	STACK_1, W
;math.ppas,383 :: 		
$055F	$0475			IORWF	STACK_5, W
;math.ppas,384 :: 		
$0560	$00FA			MOVWF	STACK_10
;math.ppas,385 :: 		
$0561	$1BFA			BTFSC	STACK_10, 7
;math.ppas,386 :: 		
$0562	$2D73			GOTO	$+17
;math.ppas,388 :: 		
$0563	$270A			CALL	_div_16x16_s_l
;math.ppas,390 :: 		
$0564	$187B			BTFSC	STACK_11, 0
;math.ppas,392 :: 		
$0565	$2D86			GOTO	$+33
;math.ppas,393 :: 		
$0566	$1FFD			BTFSS	STACK_13, 7
;math.ppas,395 :: 		
$0567	$3400			RETLW	0
;math.ppas,396 :: 		
$0568	$09F0			COMF	STACK_0, F
;math.ppas,397 :: 		
$0569	$09F1			COMF	STACK_1, F
;math.ppas,398 :: 		
$056A	$0AF0			INCF	STACK_0, F
;math.ppas,399 :: 		
$056B	$1903			BTFSC	STATUS, Z
;math.ppas,401 :: 		
$056C	$0AF1			INCF	STACK_1, F
;math.ppas,402 :: 		
$056D	$09F8			COMF	STACK_8, F
;math.ppas,403 :: 		
$056E	$09F9			COMF	STACK_9, F
;math.ppas,404 :: 		
$056F	$0AF8			INCF	STACK_8, F
;math.ppas,405 :: 		
$0570	$1903			BTFSC	STATUS, Z
;math.ppas,407 :: 		
$0571	$0AF9			INCF	STACK_9, F
;math.ppas,409 :: 		
$0572	$3400			RETLW	0
;math.ppas,410 :: 		
$0573	$1FF5			BTFSS	STACK_5, 7
;math.ppas,411 :: 		
$0574	$2D82			GOTO	$+14
;math.ppas,412 :: 		
$0575	$1BF1			BTFSC	STACK_1, 7
;math.ppas,413 :: 		
$0576	$2D7E			GOTO	$+8
;math.ppas,414 :: 		
$0577	$0871			MOVF	STACK_1, W
;math.ppas,415 :: 		
$0578	$00F9			MOVWF	STACK_9
;math.ppas,416 :: 		
$0579	$0870			MOVF	STACK_0, W
;math.ppas,417 :: 		
$057A	$00F8			MOVWF	STACK_8
;math.ppas,418 :: 		
$057B	$01F1			CLRF	STACK_1
;math.ppas,419 :: 		
$057C	$01F0			CLRF	STACK_0
;math.ppas,420 :: 		
$057D	$2D66			GOTO	$-23
;math.ppas,421 :: 		
$057E	$01F1			CLRF	STACK_1
;math.ppas,422 :: 		
$057F	$01F0			CLRF	STACK_0
;math.ppas,423 :: 		
$0580	$0AF0			INCF	STACK_0, F
;math.ppas,425 :: 		
$0581	$3400			RETLW	0
;math.ppas,426 :: 		
$0582	$09F1			COMF	STACK_1, F
;math.ppas,427 :: 		
$0583	$09F0			COMF	STACK_0, F
;math.ppas,428 :: 		
$0584	$0AFB			INCF	STACK_11, F
;math.ppas,430 :: 		
$0585	$2D63			GOTO	$-34
;math.ppas,431 :: 		
$0586	$0AF8			INCF	STACK_8, F
;math.ppas,432 :: 		
$0587	$1903			BTFSC	STATUS, Z
;math.ppas,433 :: 		
$0588	$0AF9			INCF	STACK_9, F
;math.ppas,434 :: 		
$0589	$0874			MOVF	STACK_4, W
;math.ppas,435 :: 		
$058A	$0278			SUBWF	STACK_8, W
;math.ppas,436 :: 		
$058B	$1D03			BTFSS	STATUS, Z
;math.ppas,437 :: 		
$058C	$2D66			GOTO	$-38
;math.ppas,438 :: 		
$058D	$0875			MOVF	STACK_5, W
;math.ppas,439 :: 		
$058E	$0279			SUBWF	STACK_9, W
;math.ppas,440 :: 		
$058F	$1D03			BTFSS	STATUS, Z
;math.ppas,441 :: 		
$0590	$2D66			GOTO	$-42
;math.ppas,442 :: 		
$0591	$01F9			CLRF	STACK_9
;math.ppas,443 :: 		
$0592	$01F8			CLRF	STACK_8
;math.ppas,444 :: 		
$0593	$0AF0			INCF	STACK_0, F
;math.ppas,445 :: 		
$0594	$1903			BTFSC	STATUS, Z
;math.ppas,446 :: 		
$0595	$0AF1			INCF	STACK_1, F
;math.ppas,447 :: 		
$0596	$1FF1			BTFSS	STACK_1, 7
;math.ppas,448 :: 		
$0597	$2D66			GOTO	$-49
;math.ppas,449 :: 		
$0598	$0000			NOP
;math.ppas,450 :: 		
$0599	$34FF			RETLW	255
;math.ppas,451 :: 		
$059A	$	math_L_7:
;math.ppas,452 :: 		
$059A	$0008			RETURN
$0004	$	_main:
;displays.pbas,12 :: 		main:
$0004	$	_main_main:
;displays.pbas,13 :: 		TRISA=%11111000
$0004	$30F8			MOVLW	248
$0005	$1303			BCF	STATUS, RP1
$0006	$1683			BSF	STATUS, RP0
$0007	$0085			MOVWF	TRISA
;displays.pbas,14 :: 		TRISB=%11111111
$0008	$30FF			MOVLW	255
$0009	$0086			MOVWF	TRISB
;displays.pbas,15 :: 		TRISC=%10000001
$000A	$3081			MOVLW	129
$000B	$0087			MOVWF	TRISC
;displays.pbas,16 :: 		INTCON=%00000000
$000C	$018B			CLRF	INTCON, 1
;displays.pbas,17 :: 		ANSEL=%00000000
$000D	$1703			BSF	STATUS, RP1
$000E	$0188			CLRF	ANSEL, 1
;displays.pbas,18 :: 		ANSELH=%00000000
$000F	$0189			CLRF	ANSELH, 1
;displays.pbas,19 :: 		portA=0
$0010	$1303			BCF	STATUS, RP1
$0011	$1283			BCF	STATUS, RP0
$0012	$0185			CLRF	PORTA, 1
;displays.pbas,20 :: 		portB=0
$0013	$0186			CLRF	PORTB, 1
;displays.pbas,22 :: 		USART_INIT(9600)
$0014	$3019			MOVLW	25
$0015	$1683			BSF	STATUS, RP0
$0016	$0099			MOVWF	SPBRG
$0017	$1518			BSF	TXSTA, BRGH
$0018	$158A			BSF	PCLATH, 3
$0019	$2033			CALL	_usart_init
$001A	$118A			BCF	PCLATH, 3
;displays.pbas,24 :: 		I2C_INIT(100000)
$001B	$300A			MOVLW	10
$001C	$1683			BSF	STATUS, RP0
$001D	$0093			MOVWF	SSPADD
$001E	$158A			BSF	PCLATH, 3
$001F	$207A			CALL	_i2c_init
$0020	$118A			BCF	PCLATH, 3
;displays.pbas,26 :: 		executa:
$0021	$	_main_executa:
;displays.pbas,28 :: 		if Usart_Data_Ready() > 0 then
$0021	$158A			BSF	PCLATH, 3
$0022	$206D			CALL	_usart_data_ready
$0023	$118A			BCF	PCLATH, 3
$0024	$0870			MOVF	STACK_0, 0
$0025	$3C00			SUBLW	0
$0026	$1803			BTFSC	STATUS, C
$0027	$2A99			GOTO	displays_L_2
$0028	$	displays_L_1:
;displays.pbas,29 :: 		Usart_Read_Text(recebe,"/")
$0028	$3021			MOVLW	_recebe
$0029	$00B8			MOVWF	FARG_Usart_Read_Text
$002A	$302F			MOVLW	47
$002B	$00B4			MOVWF	?main_Local_Text+0
$002C	$01B5			CLRF	?main_Local_Text+1
$002D	$3034			MOVLW	?main_Local_Text
$002E	$00B9			MOVWF	FARG_Usart_Read_Text+1
$002F	$259B			CALL	_usart_read_text
;displays.pbas,30 :: 		valorRecebido = StrToInt(recebe)
$0030	$3021			MOVLW	_recebe
$0031	$00B8			MOVWF	FARG_StrToInt
$0032	$23E3			CALL	_strtoint
$0033	$0870			MOVF	STACK_0, 0
$0034	$00A8			MOVWF	_valorrecebido
$0035	$0871			MOVF	STACK_0+1, 0
$0036	$00A9			MOVWF	_valorrecebido+1
;displays.pbas,32 :: 		if (valorRecebido > 999) and (valorRecebido < 4256) then
$0037	$3080			MOVLW	128
$0038	$3A03			XORLW	3
$0039	$00F3			MOVWF	STACK_3
$003A	$3080			MOVLW	128
$003B	$0671			XORWF	STACK_0+1, 0
$003C	$0273			SUBWF	STACK_3, 0
$003D	$1D03			BTFSS	STATUS, Z
$003E	$2841			GOTO	L_main_0
$003F	$0870			MOVF	STACK_0, 0
$0040	$3CE7			SUBLW	231
$0041	$	L_main_0:
$0041	$30FF			MOVLW	255
$0042	$1803			BTFSC	STATUS, C
$0043	$3000			MOVLW	0
$0044	$00F3			MOVWF	STACK_3
$0045	$3080			MOVLW	128
$0046	$0671			XORWF	STACK_0+1, 0
$0047	$00F2			MOVWF	STACK_2
$0048	$3080			MOVLW	128
$0049	$3A10			XORLW	16
$004A	$0272			SUBWF	STACK_2, 0
$004B	$1D03			BTFSS	STATUS, Z
$004C	$284F			GOTO	L_main_1
$004D	$30A0			MOVLW	160
$004E	$0270			SUBWF	STACK_0, 0
$004F	$	L_main_1:
$004F	$30FF			MOVLW	255
$0050	$1803			BTFSC	STATUS, C
$0051	$3000			MOVLW	0
$0052	$00F2			MOVWF	STACK_2
$0053	$0872			MOVF	STACK_2, 0
$0054	$0573			ANDWF	STACK_3, 0
$0055	$00F0			MOVWF	STACK_0
$0056	$1903			BTFSC	STATUS, Z
$0057	$2A6A			GOTO	displays_L_5
$0058	$	displays_L_4:
;displays.pbas,33 :: 		if (valorRecebido >= 1000) And (valorRecebido < 1256) then
$0058	$3080			MOVLW	128
$0059	$0629			XORWF	_valorrecebido+1, 0
$005A	$00F2			MOVWF	STACK_2
$005B	$3080			MOVLW	128
$005C	$3A03			XORLW	3
$005D	$0272			SUBWF	STACK_2, 0
$005E	$1D03			BTFSS	STATUS, Z
$005F	$2862			GOTO	L_main_2
$0060	$30E8			MOVLW	232
$0061	$0228			SUBWF	_valorrecebido, 0
$0062	$	L_main_2:
$0062	$30FF			MOVLW	255
$0063	$1C03			BTFSS	STATUS, C
$0064	$3000			MOVLW	0
$0065	$00F2			MOVWF	STACK_2
$0066	$3080			MOVLW	128
$0067	$0629			XORWF	_valorrecebido+1, 0
$0068	$00F0			MOVWF	STACK_0
$0069	$3080			MOVLW	128
$006A	$3A04			XORLW	4
$006B	$0270			SUBWF	STACK_0, 0
$006C	$1D03			BTFSS	STATUS, Z
$006D	$2870			GOTO	L_main_3
$006E	$30E8			MOVLW	232
$006F	$0228			SUBWF	_valorrecebido, 0
$0070	$	L_main_3:
$0070	$30FF			MOVLW	255
$0071	$1803			BTFSC	STATUS, C
$0072	$3000			MOVLW	0
$0073	$00F0			MOVWF	STACK_0
$0074	$0872			MOVF	STACK_2, 0
$0075	$05F0			ANDWF	STACK_0, 1
$0076	$1903			BTFSC	STATUS, Z
$0077	$28D8			GOTO	displays_L_8
$0078	$	displays_L_7:
;displays.pbas,34 :: 		valorRecebido = valorRecebido - 1000
$0078	$30E8			MOVLW	232
$0079	$0228			SUBWF	_valorrecebido, 0
$007A	$00F0			MOVWF	STACK_0
$007B	$3003			MOVLW	3
$007C	$1C03			BTFSS	STATUS, C
$007D	$3F01			ADDLW	1
$007E	$0229			SUBWF	_valorrecebido+1, 0
$007F	$00F1			MOVWF	STACK_0+1
$0080	$0870			MOVF	STACK_0, 0
$0081	$00A8			MOVWF	_valorrecebido
$0082	$0871			MOVF	STACK_0+1, 0
$0083	$00A9			MOVWF	_valorrecebido+1
;displays.pbas,35 :: 		valorPorcent = ((valorRecebido * 100) / 255)
$0084	$3064			MOVLW	100
$0085	$00F4			MOVWF	STACK_4
$0086	$01F5			CLRF	STACK_4+1
$0087	$25E2			CALL	_mul_16x16_s
$0088	$30FF			MOVLW	255
$0089	$00F4			MOVWF	STACK_4
$008A	$01F5			CLRF	STACK_4+1
$008B	$2541			CALL	_div_16x16_s
$008C	$0870			MOVF	STACK_0, 0
$008D	$00AA			MOVWF	_valorporcent
$008E	$0871			MOVF	STACK_0+1, 0
$008F	$00AB			MOVWF	_valorporcent+1
;displays.pbas,37 :: 		if valorPorcent > 99 then
$0090	$3080			MOVLW	128
$0091	$00F2			MOVWF	STACK_2
$0092	$3080			MOVLW	128
$0093	$0671			XORWF	STACK_0+1, 0
$0094	$0272			SUBWF	STACK_2, 0
$0095	$1D03			BTFSS	STATUS, Z
$0096	$2899			GOTO	L_main_4
$0097	$0870			MOVF	STACK_0, 0
$0098	$3C63			SUBLW	99
$0099	$	L_main_4:
$0099	$1803			BTFSC	STATUS, C
$009A	$289E			GOTO	displays_L_11
$009B	$	displays_L_10:
;displays.pbas,38 :: 		valorPorcent = 99
$009B	$3063			MOVLW	99
$009C	$00AA			MOVWF	_valorporcent
$009D	$01AB			CLRF	_valorporcent+1
$009E	$	displays_L_11:
;displays.pbas,39 :: 		end if
$009E	$	displays_L_12:
;displays.pbas,40 :: 		dez = valorPorcent div 10
$009E	$300A			MOVLW	10
$009F	$00F4			MOVWF	STACK_4
$00A0	$01F5			CLRF	STACK_4+1
$00A1	$082A			MOVF	_valorporcent, 0
$00A2	$00F0			MOVWF	STACK_0
$00A3	$082B			MOVF	_valorporcent+1, 0
$00A4	$00F1			MOVWF	STACK_0+1
$00A5	$2541			CALL	_div_16x16_s
$00A6	$0870			MOVF	STACK_0, 0
$00A7	$00B6			MOVWF	FLOC_main+2
$00A8	$0871			MOVF	STACK_0+1, 0
$00A9	$00B7			MOVWF	FLOC_main+3
$00AA	$0836			MOVF	FLOC_main+2, 0
$00AB	$00AC			MOVWF	_dez
$00AC	$0837			MOVF	FLOC_main+3, 0
$00AD	$00AD			MOVWF	_dez+1
;displays.pbas,41 :: 		uni = valorPorcent - (dez * 10)
$00AE	$0836			MOVF	FLOC_main+2, 0
$00AF	$00F0			MOVWF	STACK_0
$00B0	$0837			MOVF	FLOC_main+3, 0
$00B1	$00F1			MOVWF	STACK_0+1
$00B2	$300A			MOVLW	10
$00B3	$00F4			MOVWF	STACK_4
$00B4	$01F5			CLRF	STACK_4+1
$00B5	$25E2			CALL	_mul_16x16_s
$00B6	$0870			MOVF	STACK_0, 0
$00B7	$022A			SUBWF	_valorporcent, 0
$00B8	$00F0			MOVWF	STACK_0
$00B9	$0871			MOVF	STACK_0+1, 0
$00BA	$1C03			BTFSS	STATUS, C
$00BB	$3F01			ADDLW	1
$00BC	$022B			SUBWF	_valorporcent+1, 0
$00BD	$00F1			MOVWF	STACK_0+1
$00BE	$0870			MOVF	STACK_0, 0
$00BF	$00AE			MOVWF	_uni
$00C0	$0871			MOVF	STACK_0+1, 0
$00C1	$00AF			MOVWF	_uni+1
;displays.pbas,42 :: 		valorPortas = dez + (uni  * 16)
$00C2	$3004			MOVLW	4
$00C3	$00F4			MOVWF	STACK_4
$00C4	$0874			MOVF	STACK_4, 0
$00C5	$	L_main_5:
$00C5	$1903			BTFSC	STATUS, Z
$00C6	$28CC			GOTO	L_main_6
$00C7	$0DF0			RLF	STACK_0, 1
$00C8	$0DF1			RLF	STACK_0+1, 1
$00C9	$1070			BCF	STACK_0, 0
$00CA	$3FFF			ADDLW	255
$00CB	$28C5			GOTO	L_main_5
$00CC	$	L_main_6:
$00CC	$0870			MOVF	STACK_0, 0
$00CD	$0736			ADDWF	FLOC_main+2, 0
$00CE	$00B0			MOVWF	_valorportas
$00CF	$0837			MOVF	FLOC_main+3, 0
$00D0	$1803			BTFSC	STATUS, C
$00D1	$3F01			ADDLW	1
$00D2	$0771			ADDWF	STACK_0+1, 0
$00D3	$00B1			MOVWF	_valorportas+1
;displays.pbas,43 :: 		escrita = 0x42
$00D4	$3042			MOVLW	66
$00D5	$00B2			MOVWF	_escrita
$00D6	$01B3			CLRF	_escrita+1
;displays.pbas,44 :: 		gosub escreve_I2C
$00D7	$229A			CALL	_main_escreve_i2c
$00D8	$	displays_L_8:
;displays.pbas,45 :: 		end if
$00D8	$	displays_L_9:
;displays.pbas,46 :: 		if (valorRecebido >= 2000) And (valorRecebido < 2256) then
$00D8	$3080			MOVLW	128
$00D9	$1303			BCF	STATUS, RP1
$00DA	$1283			BCF	STATUS, RP0
$00DB	$0629			XORWF	_valorrecebido+1, 0
$00DC	$00F2			MOVWF	STACK_2
$00DD	$3080			MOVLW	128
$00DE	$3A07			XORLW	7
$00DF	$0272			SUBWF	STACK_2, 0
$00E0	$1D03			BTFSS	STATUS, Z
$00E1	$28E4			GOTO	L_main_7
$00E2	$30D0			MOVLW	208
$00E3	$0228			SUBWF	_valorrecebido, 0
$00E4	$	L_main_7:
$00E4	$30FF			MOVLW	255
$00E5	$1C03			BTFSS	STATUS, C
$00E6	$3000			MOVLW	0
$00E7	$00F2			MOVWF	STACK_2
$00E8	$3080			MOVLW	128
$00E9	$0629			XORWF	_valorrecebido+1, 0
$00EA	$00F0			MOVWF	STACK_0
$00EB	$3080			MOVLW	128
$00EC	$3A08			XORLW	8
$00ED	$0270			SUBWF	STACK_0, 0
$00EE	$1D03			BTFSS	STATUS, Z
$00EF	$28F2			GOTO	L_main_8
$00F0	$30D0			MOVLW	208
$00F1	$0228			SUBWF	_valorrecebido, 0
$00F2	$	L_main_8:
$00F2	$30FF			MOVLW	255
$00F3	$1803			BTFSC	STATUS, C
$00F4	$3000			MOVLW	0
$00F5	$00F0			MOVWF	STACK_0
$00F6	$0872			MOVF	STACK_2, 0
$00F7	$05F0			ANDWF	STACK_0, 1
$00F8	$1903			BTFSC	STATUS, Z
$00F9	$295A			GOTO	displays_L_14
$00FA	$	displays_L_13:
;displays.pbas,47 :: 		valorRecebido = valorRecebido - 2000
$00FA	$30D0			MOVLW	208
$00FB	$0228			SUBWF	_valorrecebido, 0
$00FC	$00F0			MOVWF	STACK_0
$00FD	$3007			MOVLW	7
$00FE	$1C03			BTFSS	STATUS, C
$00FF	$3F01			ADDLW	1
$0100	$0229			SUBWF	_valorrecebido+1, 0
$0101	$00F1			MOVWF	STACK_0+1
$0102	$0870			MOVF	STACK_0, 0
$0103	$00A8			MOVWF	_valorrecebido
$0104	$0871			MOVF	STACK_0+1, 0
$0105	$00A9			MOVWF	_valorrecebido+1
;displays.pbas,48 :: 		valorPorcent = ((valorRecebido * 100) / 255)
$0106	$3064			MOVLW	100
$0107	$00F4			MOVWF	STACK_4
$0108	$01F5			CLRF	STACK_4+1
$0109	$25E2			CALL	_mul_16x16_s
$010A	$30FF			MOVLW	255
$010B	$00F4			MOVWF	STACK_4
$010C	$01F5			CLRF	STACK_4+1
$010D	$2541			CALL	_div_16x16_s
$010E	$0870			MOVF	STACK_0, 0
$010F	$00AA			MOVWF	_valorporcent
$0110	$0871			MOVF	STACK_0+1, 0
$0111	$00AB			MOVWF	_valorporcent+1
;displays.pbas,50 :: 		if valorPorcent > 99 then
$0112	$3080			MOVLW	128
$0113	$00F2			MOVWF	STACK_2
$0114	$3080			MOVLW	128
$0115	$0671			XORWF	STACK_0+1, 0
$0116	$0272			SUBWF	STACK_2, 0
$0117	$1D03			BTFSS	STATUS, Z
$0118	$291B			GOTO	L_main_9
$0119	$0870			MOVF	STACK_0, 0
$011A	$3C63			SUBLW	99
$011B	$	L_main_9:
$011B	$1803			BTFSC	STATUS, C
$011C	$2920			GOTO	displays_L_17
$011D	$	displays_L_16:
;displays.pbas,51 :: 		valorPorcent = 99
$011D	$3063			MOVLW	99
$011E	$00AA			MOVWF	_valorporcent
$011F	$01AB			CLRF	_valorporcent+1
$0120	$	displays_L_17:
;displays.pbas,52 :: 		end if
$0120	$	displays_L_18:
;displays.pbas,54 :: 		dez = valorPorcent div 10
$0120	$300A			MOVLW	10
$0121	$00F4			MOVWF	STACK_4
$0122	$01F5			CLRF	STACK_4+1
$0123	$082A			MOVF	_valorporcent, 0
$0124	$00F0			MOVWF	STACK_0
$0125	$082B			MOVF	_valorporcent+1, 0
$0126	$00F1			MOVWF	STACK_0+1
$0127	$2541			CALL	_div_16x16_s
$0128	$0870			MOVF	STACK_0, 0
$0129	$00B6			MOVWF	FLOC_main+2
$012A	$0871			MOVF	STACK_0+1, 0
$012B	$00B7			MOVWF	FLOC_main+3
$012C	$0836			MOVF	FLOC_main+2, 0
$012D	$00AC			MOVWF	_dez
$012E	$0837			MOVF	FLOC_main+3, 0
$012F	$00AD			MOVWF	_dez+1
;displays.pbas,55 :: 		uni = valorPorcent - (dez * 10)
$0130	$0836			MOVF	FLOC_main+2, 0
$0131	$00F0			MOVWF	STACK_0
$0132	$0837			MOVF	FLOC_main+3, 0
$0133	$00F1			MOVWF	STACK_0+1
$0134	$300A			MOVLW	10
$0135	$00F4			MOVWF	STACK_4
$0136	$01F5			CLRF	STACK_4+1
$0137	$25E2			CALL	_mul_16x16_s
$0138	$0870			MOVF	STACK_0, 0
$0139	$022A			SUBWF	_valorporcent, 0
$013A	$00F0			MOVWF	STACK_0
$013B	$0871			MOVF	STACK_0+1, 0
$013C	$1C03			BTFSS	STATUS, C
$013D	$3F01			ADDLW	1
$013E	$022B			SUBWF	_valorporcent+1, 0
$013F	$00F1			MOVWF	STACK_0+1
$0140	$0870			MOVF	STACK_0, 0
$0141	$00AE			MOVWF	_uni
$0142	$0871			MOVF	STACK_0+1, 0
$0143	$00AF			MOVWF	_uni+1
;displays.pbas,56 :: 		valorPortas = dez + (uni  * 16)
$0144	$3004			MOVLW	4
$0145	$00F4			MOVWF	STACK_4
$0146	$0874			MOVF	STACK_4, 0
$0147	$	L_main_10:
$0147	$1903			BTFSC	STATUS, Z
$0148	$294E			GOTO	L_main_11
$0149	$0DF0			RLF	STACK_0, 1
$014A	$0DF1			RLF	STACK_0+1, 1
$014B	$1070			BCF	STACK_0, 0
$014C	$3FFF			ADDLW	255
$014D	$2947			GOTO	L_main_10
$014E	$	L_main_11:
$014E	$0870			MOVF	STACK_0, 0
$014F	$0736			ADDWF	FLOC_main+2, 0
$0150	$00B0			MOVWF	_valorportas
$0151	$0837			MOVF	FLOC_main+3, 0
$0152	$1803			BTFSC	STATUS, C
$0153	$3F01			ADDLW	1
$0154	$0771			ADDWF	STACK_0+1, 0
$0155	$00B1			MOVWF	_valorportas+1
;displays.pbas,57 :: 		escrita = 0x44
$0156	$3044			MOVLW	68
$0157	$00B2			MOVWF	_escrita
$0158	$01B3			CLRF	_escrita+1
;displays.pbas,58 :: 		gosub escreve_I2C
$0159	$229A			CALL	_main_escreve_i2c
$015A	$	displays_L_14:
;displays.pbas,59 :: 		end if
$015A	$	displays_L_15:
;displays.pbas,60 :: 		if (valorRecebido >= 3000) And (valorRecebido < 3256) then
$015A	$3080			MOVLW	128
$015B	$1303			BCF	STATUS, RP1
$015C	$1283			BCF	STATUS, RP0
$015D	$0629			XORWF	_valorrecebido+1, 0
$015E	$00F2			MOVWF	STACK_2
$015F	$3080			MOVLW	128
$0160	$3A0B			XORLW	11
$0161	$0272			SUBWF	STACK_2, 0
$0162	$1D03			BTFSS	STATUS, Z
$0163	$2966			GOTO	L_main_12
$0164	$30B8			MOVLW	184
$0165	$0228			SUBWF	_valorrecebido, 0
$0166	$	L_main_12:
$0166	$30FF			MOVLW	255
$0167	$1C03			BTFSS	STATUS, C
$0168	$3000			MOVLW	0
$0169	$00F2			MOVWF	STACK_2
$016A	$3080			MOVLW	128
$016B	$0629			XORWF	_valorrecebido+1, 0
$016C	$00F0			MOVWF	STACK_0
$016D	$3080			MOVLW	128
$016E	$3A0C			XORLW	12
$016F	$0270			SUBWF	STACK_0, 0
$0170	$1D03			BTFSS	STATUS, Z
$0171	$2974			GOTO	L_main_13
$0172	$30B8			MOVLW	184
$0173	$0228			SUBWF	_valorrecebido, 0
$0174	$	L_main_13:
$0174	$30FF			MOVLW	255
$0175	$1803			BTFSC	STATUS, C
$0176	$3000			MOVLW	0
$0177	$00F0			MOVWF	STACK_0
$0178	$0872			MOVF	STACK_2, 0
$0179	$05F0			ANDWF	STACK_0, 1
$017A	$1903			BTFSC	STATUS, Z
$017B	$29DC			GOTO	displays_L_20
$017C	$	displays_L_19:
;displays.pbas,61 :: 		valorRecebido = valorRecebido - 3000
$017C	$30B8			MOVLW	184
$017D	$0228			SUBWF	_valorrecebido, 0
$017E	$00F0			MOVWF	STACK_0
$017F	$300B			MOVLW	11
$0180	$1C03			BTFSS	STATUS, C
$0181	$3F01			ADDLW	1
$0182	$0229			SUBWF	_valorrecebido+1, 0
$0183	$00F1			MOVWF	STACK_0+1
$0184	$0870			MOVF	STACK_0, 0
$0185	$00A8			MOVWF	_valorrecebido
$0186	$0871			MOVF	STACK_0+1, 0
$0187	$00A9			MOVWF	_valorrecebido+1
;displays.pbas,62 :: 		valorPorcent = ((valorRecebido * 100) / 255)
$0188	$3064			MOVLW	100
$0189	$00F4			MOVWF	STACK_4
$018A	$01F5			CLRF	STACK_4+1
$018B	$25E2			CALL	_mul_16x16_s
$018C	$30FF			MOVLW	255
$018D	$00F4			MOVWF	STACK_4
$018E	$01F5			CLRF	STACK_4+1
$018F	$2541			CALL	_div_16x16_s
$0190	$0870			MOVF	STACK_0, 0
$0191	$00AA			MOVWF	_valorporcent
$0192	$0871			MOVF	STACK_0+1, 0
$0193	$00AB			MOVWF	_valorporcent+1
;displays.pbas,64 :: 		if valorPorcent > 99 then
$0194	$3080			MOVLW	128
$0195	$00F2			MOVWF	STACK_2
$0196	$3080			MOVLW	128
$0197	$0671			XORWF	STACK_0+1, 0
$0198	$0272			SUBWF	STACK_2, 0
$0199	$1D03			BTFSS	STATUS, Z
$019A	$299D			GOTO	L_main_14
$019B	$0870			MOVF	STACK_0, 0
$019C	$3C63			SUBLW	99
$019D	$	L_main_14:
$019D	$1803			BTFSC	STATUS, C
$019E	$29A2			GOTO	displays_L_23
$019F	$	displays_L_22:
;displays.pbas,65 :: 		valorPorcent = 99
$019F	$3063			MOVLW	99
$01A0	$00AA			MOVWF	_valorporcent
$01A1	$01AB			CLRF	_valorporcent+1
$01A2	$	displays_L_23:
;displays.pbas,66 :: 		end if
$01A2	$	displays_L_24:
;displays.pbas,68 :: 		dez = valorPorcent div 10
$01A2	$300A			MOVLW	10
$01A3	$00F4			MOVWF	STACK_4
$01A4	$01F5			CLRF	STACK_4+1
$01A5	$082A			MOVF	_valorporcent, 0
$01A6	$00F0			MOVWF	STACK_0
$01A7	$082B			MOVF	_valorporcent+1, 0
$01A8	$00F1			MOVWF	STACK_0+1
$01A9	$2541			CALL	_div_16x16_s
$01AA	$0870			MOVF	STACK_0, 0
$01AB	$00B6			MOVWF	FLOC_main+2
$01AC	$0871			MOVF	STACK_0+1, 0
$01AD	$00B7			MOVWF	FLOC_main+3
$01AE	$0836			MOVF	FLOC_main+2, 0
$01AF	$00AC			MOVWF	_dez
$01B0	$0837			MOVF	FLOC_main+3, 0
$01B1	$00AD			MOVWF	_dez+1
;displays.pbas,69 :: 		uni = valorPorcent - (dez * 10)
$01B2	$0836			MOVF	FLOC_main+2, 0
$01B3	$00F0			MOVWF	STACK_0
$01B4	$0837			MOVF	FLOC_main+3, 0
$01B5	$00F1			MOVWF	STACK_0+1
$01B6	$300A			MOVLW	10
$01B7	$00F4			MOVWF	STACK_4
$01B8	$01F5			CLRF	STACK_4+1
$01B9	$25E2			CALL	_mul_16x16_s
$01BA	$0870			MOVF	STACK_0, 0
$01BB	$022A			SUBWF	_valorporcent, 0
$01BC	$00F0			MOVWF	STACK_0
$01BD	$0871			MOVF	STACK_0+1, 0
$01BE	$1C03			BTFSS	STATUS, C
$01BF	$3F01			ADDLW	1
$01C0	$022B			SUBWF	_valorporcent+1, 0
$01C1	$00F1			MOVWF	STACK_0+1
$01C2	$0870			MOVF	STACK_0, 0
$01C3	$00AE			MOVWF	_uni
$01C4	$0871			MOVF	STACK_0+1, 0
$01C5	$00AF			MOVWF	_uni+1
;displays.pbas,70 :: 		valorPortas = dez + (uni  * 16)
$01C6	$3004			MOVLW	4
$01C7	$00F4			MOVWF	STACK_4
$01C8	$0874			MOVF	STACK_4, 0
$01C9	$	L_main_15:
$01C9	$1903			BTFSC	STATUS, Z
$01CA	$29D0			GOTO	L_main_16
$01CB	$0DF0			RLF	STACK_0, 1
$01CC	$0DF1			RLF	STACK_0+1, 1
$01CD	$1070			BCF	STACK_0, 0
$01CE	$3FFF			ADDLW	255
$01CF	$29C9			GOTO	L_main_15
$01D0	$	L_main_16:
$01D0	$0870			MOVF	STACK_0, 0
$01D1	$0736			ADDWF	FLOC_main+2, 0
$01D2	$00B0			MOVWF	_valorportas
$01D3	$0837			MOVF	FLOC_main+3, 0
$01D4	$1803			BTFSC	STATUS, C
$01D5	$3F01			ADDLW	1
$01D6	$0771			ADDWF	STACK_0+1, 0
$01D7	$00B1			MOVWF	_valorportas+1
;displays.pbas,71 :: 		escrita = 0x46
$01D8	$3046			MOVLW	70
$01D9	$00B2			MOVWF	_escrita
$01DA	$01B3			CLRF	_escrita+1
;displays.pbas,72 :: 		gosub escreve_I2C
$01DB	$229A			CALL	_main_escreve_i2c
$01DC	$	displays_L_20:
;displays.pbas,73 :: 		end if
$01DC	$	displays_L_21:
;displays.pbas,74 :: 		if (valorRecebido >= 4000) And (valorRecebido < 4256) then
$01DC	$3080			MOVLW	128
$01DD	$1303			BCF	STATUS, RP1
$01DE	$1283			BCF	STATUS, RP0
$01DF	$0629			XORWF	_valorrecebido+1, 0
$01E0	$00F2			MOVWF	STACK_2
$01E1	$3080			MOVLW	128
$01E2	$3A0F			XORLW	15
$01E3	$0272			SUBWF	STACK_2, 0
$01E4	$1D03			BTFSS	STATUS, Z
$01E5	$29E8			GOTO	L_main_17
$01E6	$30A0			MOVLW	160
$01E7	$0228			SUBWF	_valorrecebido, 0
$01E8	$	L_main_17:
$01E8	$30FF			MOVLW	255
$01E9	$1C03			BTFSS	STATUS, C
$01EA	$3000			MOVLW	0
$01EB	$00F2			MOVWF	STACK_2
$01EC	$3080			MOVLW	128
$01ED	$0629			XORWF	_valorrecebido+1, 0
$01EE	$00F0			MOVWF	STACK_0
$01EF	$3080			MOVLW	128
$01F0	$3A10			XORLW	16
$01F1	$0270			SUBWF	STACK_0, 0
$01F2	$1D03			BTFSS	STATUS, Z
$01F3	$29F6			GOTO	L_main_18
$01F4	$30A0			MOVLW	160
$01F5	$0228			SUBWF	_valorrecebido, 0
$01F6	$	L_main_18:
$01F6	$30FF			MOVLW	255
$01F7	$1803			BTFSC	STATUS, C
$01F8	$3000			MOVLW	0
$01F9	$00F0			MOVWF	STACK_0
$01FA	$0872			MOVF	STACK_2, 0
$01FB	$05F0			ANDWF	STACK_0, 1
$01FC	$1903			BTFSC	STATUS, Z
$01FD	$2A6A			GOTO	displays_L_26
$01FE	$	displays_L_25:
;displays.pbas,75 :: 		valorRecebido = valorRecebido - 4000
$01FE	$30A0			MOVLW	160
$01FF	$0228			SUBWF	_valorrecebido, 0
$0200	$00F0			MOVWF	STACK_0
$0201	$300F			MOVLW	15
$0202	$1C03			BTFSS	STATUS, C
$0203	$3F01			ADDLW	1
$0204	$0229			SUBWF	_valorrecebido+1, 0
$0205	$00F1			MOVWF	STACK_0+1
$0206	$0870			MOVF	STACK_0, 0
$0207	$00A8			MOVWF	_valorrecebido
$0208	$0871			MOVF	STACK_0+1, 0
$0209	$00A9			MOVWF	_valorrecebido+1
;displays.pbas,76 :: 		valorPorcent = ((valorRecebido * 100) / 255)
$020A	$3064			MOVLW	100
$020B	$00F4			MOVWF	STACK_4
$020C	$01F5			CLRF	STACK_4+1
$020D	$25E2			CALL	_mul_16x16_s
$020E	$30FF			MOVLW	255
$020F	$00F4			MOVWF	STACK_4
$0210	$01F5			CLRF	STACK_4+1
$0211	$2541			CALL	_div_16x16_s
$0212	$0870			MOVF	STACK_0, 0
$0213	$00AA			MOVWF	_valorporcent
$0214	$0871			MOVF	STACK_0+1, 0
$0215	$00AB			MOVWF	_valorporcent+1
;displays.pbas,78 :: 		if valorPorcent > 99 then
$0216	$3080			MOVLW	128
$0217	$00F2			MOVWF	STACK_2
$0218	$3080			MOVLW	128
$0219	$0671			XORWF	STACK_0+1, 0
$021A	$0272			SUBWF	STACK_2, 0
$021B	$1D03			BTFSS	STATUS, Z
$021C	$2A1F			GOTO	L_main_19
$021D	$0870			MOVF	STACK_0, 0
$021E	$3C63			SUBLW	99
$021F	$	L_main_19:
$021F	$1803			BTFSC	STATUS, C
$0220	$2A24			GOTO	displays_L_29
$0221	$	displays_L_28:
;displays.pbas,79 :: 		valorPorcent = 99
$0221	$3063			MOVLW	99
$0222	$00AA			MOVWF	_valorporcent
$0223	$01AB			CLRF	_valorporcent+1
$0224	$	displays_L_29:
;displays.pbas,80 :: 		end if
$0224	$	displays_L_30:
;displays.pbas,82 :: 		dez = valorPorcent div 10
$0224	$300A			MOVLW	10
$0225	$00F4			MOVWF	STACK_4
$0226	$01F5			CLRF	STACK_4+1
$0227	$082A			MOVF	_valorporcent, 0
$0228	$00F0			MOVWF	STACK_0
$0229	$082B			MOVF	_valorporcent+1, 0
$022A	$00F1			MOVWF	STACK_0+1
$022B	$2541			CALL	_div_16x16_s
$022C	$0870			MOVF	STACK_0, 0
$022D	$00B6			MOVWF	FLOC_main+2
$022E	$0871			MOVF	STACK_0+1, 0
$022F	$00B7			MOVWF	FLOC_main+3
$0230	$0836			MOVF	FLOC_main+2, 0
$0231	$00AC			MOVWF	_dez
$0232	$0837			MOVF	FLOC_main+3, 0
$0233	$00AD			MOVWF	_dez+1
;displays.pbas,83 :: 		uni = valorPorcent - (dez * 10)
$0234	$0836			MOVF	FLOC_main+2, 0
$0235	$00F0			MOVWF	STACK_0
$0236	$0837			MOVF	FLOC_main+3, 0
$0237	$00F1			MOVWF	STACK_0+1
$0238	$300A			MOVLW	10
$0239	$00F4			MOVWF	STACK_4
$023A	$01F5			CLRF	STACK_4+1
$023B	$25E2			CALL	_mul_16x16_s
$023C	$0870			MOVF	STACK_0, 0
$023D	$022A			SUBWF	_valorporcent, 0
$023E	$00F0			MOVWF	STACK_0
$023F	$0871			MOVF	STACK_0+1, 0
$0240	$1C03			BTFSS	STATUS, C
$0241	$3F01			ADDLW	1
$0242	$022B			SUBWF	_valorporcent+1, 0
$0243	$00F1			MOVWF	STACK_0+1
$0244	$0870			MOVF	STACK_0, 0
$0245	$00AE			MOVWF	_uni
$0246	$0871			MOVF	STACK_0+1, 0
$0247	$00AF			MOVWF	_uni+1
;displays.pbas,84 :: 		valorPortas = dez + (uni  * 16)
$0248	$3004			MOVLW	4
$0249	$00F4			MOVWF	STACK_4
$024A	$0874			MOVF	STACK_4, 0
$024B	$	L_main_20:
$024B	$1903			BTFSC	STATUS, Z
$024C	$2A52			GOTO	L_main_21
$024D	$0DF0			RLF	STACK_0, 1
$024E	$0DF1			RLF	STACK_0+1, 1
$024F	$1070			BCF	STACK_0, 0
$0250	$3FFF			ADDLW	255
$0251	$2A4B			GOTO	L_main_20
$0252	$	L_main_21:
$0252	$0870			MOVF	STACK_0, 0
$0253	$0736			ADDWF	FLOC_main+2, 0
$0254	$00B0			MOVWF	_valorportas
$0255	$0837			MOVF	FLOC_main+3, 0
$0256	$1803			BTFSC	STATUS, C
$0257	$3F01			ADDLW	1
$0258	$0771			ADDWF	STACK_0+1, 0
$0259	$00B1			MOVWF	_valorportas+1
;displays.pbas,85 :: 		escrita = 0x42
$025A	$3042			MOVLW	66
$025B	$00B2			MOVWF	_escrita
$025C	$01B3			CLRF	_escrita+1
;displays.pbas,86 :: 		gosub escreve_I2C
$025D	$229A			CALL	_main_escreve_i2c
;displays.pbas,87 :: 		escrita = 0x44
$025E	$3044			MOVLW	68
$025F	$1303			BCF	STATUS, RP1
$0260	$1283			BCF	STATUS, RP0
$0261	$00B2			MOVWF	_escrita
$0262	$01B3			CLRF	_escrita+1
;displays.pbas,88 :: 		gosub escreve_I2C
$0263	$229A			CALL	_main_escreve_i2c
;displays.pbas,89 :: 		escrita = 0x46
$0264	$3046			MOVLW	70
$0265	$1303			BCF	STATUS, RP1
$0266	$1283			BCF	STATUS, RP0
$0267	$00B2			MOVWF	_escrita
$0268	$01B3			CLRF	_escrita+1
;displays.pbas,90 :: 		gosub escreve_I2C
$0269	$229A			CALL	_main_escreve_i2c
$026A	$	displays_L_26:
;displays.pbas,91 :: 		end if
$026A	$	displays_L_27:
$026A	$	displays_L_5:
;displays.pbas,92 :: 		end if
$026A	$	displays_L_6:
;displays.pbas,94 :: 		Usart_Write_Text(recebe)
$026A	$3021			MOVLW	_recebe
$026B	$1303			BCF	STATUS, RP1
$026C	$1283			BCF	STATUS, RP0
$026D	$00B8			MOVWF	FARG_Usart_Write_Text
$026E	$158A			BSF	PCLATH, 3
$026F	$201D			CALL	_usart_write_text
$0270	$118A			BCF	PCLATH, 3
;displays.pbas,95 :: 		delay_ms(5)
$0271	$3007			MOVLW	7
$0272	$00FB			MOVWF	STACK_11
$0273	$30FF			MOVLW	255
$0274	$00FA			MOVWF	STACK_10
$0275	$0BFB			DECFSZ	STACK_11, F
$0276	$2A78			GOTO	$+2
$0277	$2A7B			GOTO	$+4
$0278	$0BFA			DECFSZ	STACK_10, F
$0279	$2A78			GOTO	$-1
$027A	$2A75			GOTO	$-5
$027B	$3078			MOVLW	120
$027C	$00FA			MOVWF	STACK_10
$027D	$0BFA			DECFSZ	STACK_10, F
$027E	$2A7D			GOTO	$-1
$027F	$0000			NOP
$0280	$0000			NOP
;displays.pbas,96 :: 		USART_Write_Text("/")
$0281	$302F			MOVLW	47
$0282	$00B4			MOVWF	?main_Local_Text+0
$0283	$01B5			CLRF	?main_Local_Text+1
$0284	$3034			MOVLW	?main_Local_Text
$0285	$00B8			MOVWF	FARG_Usart_Write_Text
$0286	$158A			BSF	PCLATH, 3
$0287	$201D			CALL	_usart_write_text
$0288	$118A			BCF	PCLATH, 3
;displays.pbas,97 :: 		delay_ms(5)
$0289	$3007			MOVLW	7
$028A	$00FB			MOVWF	STACK_11
$028B	$30FF			MOVLW	255
$028C	$00FA			MOVWF	STACK_10
$028D	$0BFB			DECFSZ	STACK_11, F
$028E	$2A90			GOTO	$+2
$028F	$2A93			GOTO	$+4
$0290	$0BFA			DECFSZ	STACK_10, F
$0291	$2A90			GOTO	$-1
$0292	$2A8D			GOTO	$-5
$0293	$3078			MOVLW	120
$0294	$00FA			MOVWF	STACK_10
$0295	$0BFA			DECFSZ	STACK_10, F
$0296	$2A95			GOTO	$-1
$0297	$0000			NOP
$0298	$0000			NOP
$0299	$	displays_L_2:
;displays.pbas,98 :: 		end if
$0299	$	displays_L_3:
;displays.pbas,101 :: 		goto executa
$0299	$2821			GOTO	_main_executa
;displays.pbas,103 :: 		escreve_I2C:
$029A	$	_main_escreve_i2c:
;displays.pbas,105 :: 		I2C_Start
$029A	$2666			CALL	_i2c_start
;displays.pbas,106 :: 		I2C_Wr(escrita)
$029B	$0832			MOVF	_escrita, 0
$029C	$00B8			MOVWF	FARG_I2C_Wr
$029D	$26D7			CALL	_i2c_wr
;displays.pbas,107 :: 		I2C_Wr(valorPortas)
$029E	$0830			MOVF	_valorportas, 0
$029F	$00B8			MOVWF	FARG_I2C_Wr
$02A0	$26D7			CALL	_i2c_wr
;displays.pbas,108 :: 		I2C_Stop
$02A1	$158A			BSF	PCLATH, 3
$02A2	$2084			CALL	_i2c_stop
$02A3	$118A			BCF	PCLATH, 3
;displays.pbas,109 :: 		delay_ms(10)
$02A4	$300D			MOVLW	13
$02A5	$00FB			MOVWF	STACK_11
$02A6	$30FF			MOVLW	255
$02A7	$00FA			MOVWF	STACK_10
$02A8	$0BFB			DECFSZ	STACK_11, F
$02A9	$2AAB			GOTO	$+2
$02AA	$2AAE			GOTO	$+4
$02AB	$0BFA			DECFSZ	STACK_10, F
$02AC	$2AAB			GOTO	$-1
$02AD	$2AA8			GOTO	$-5
$02AE	$30F3			MOVLW	243
$02AF	$00FA			MOVWF	STACK_10
$02B0	$0BFA			DECFSZ	STACK_10, F
$02B1	$2AB0			GOTO	$-1
$02B2	$0000			NOP
;displays.pbas,111 :: 		return
$02B3	$0008			RETURN
$02B4	$	displays_L_0:
$02B4	$2AB4			GOTO	$
