;  Assembly code generated by mikroVirtualMachine - V. 5.0.0.3
;  Date/Time: 28/08/2020 23:14:19
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2804			GOTO	_main
$0004	$	_main:
;motores.pbas,3 :: 		main:
$0004	$	_main_main:
;motores.pbas,6 :: 		executa:
$0004	$	_main_executa:
;motores.pbas,8 :: 		goto executa
$0004	$2804			GOTO	_main_executa
$0005	$2805			GOTO	$
