;  Assembly code generated by mikroVirtualMachine - V. 5.0.0.3
;  Date/Time: 04/09/2020 22:33:57
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2804			GOTO	_main
$0456	$	_mul_32x32_u:
$0456	$1303			BCF	STATUS, RP1
$0457	$1283			BCF	STATUS, RP0
;math.ppas,1570 :: 		
;math.ppas,1578 :: 		
$0458	$3022			MOVLW	34
;math.ppas,1579 :: 		
$0459	$00FC			MOVWF	STACK_12
;math.ppas,1580 :: 		
$045A	$01F8			CLRF	STACK_8
;math.ppas,1581 :: 		
$045B	$01F9			CLRF	STACK_9
;math.ppas,1582 :: 		
$045C	$01FA			CLRF	STACK_10
;math.ppas,1584 :: 		
$045D	$01FB			CLRF	STACK_11
;math.ppas,1588 :: 		
$045E	$	_NEXT:
;math.ppas,1589 :: 		
$045E	$03FC			DECF	STACK_12, F
;math.ppas,1590 :: 		
$045F	$1903			BTFSC	STATUS, Z
;math.ppas,1591 :: 		
$0460	$2C8C			GOTO	_EXIT2
;math.ppas,1593 :: 		
$0461	$1003			BCF	STATUS, C
;math.ppas,1602 :: 		
$0462	$	_LOOP:
;math.ppas,1603 :: 		
$0462	$0CFB			RRF	STACK_11, F
;math.ppas,1604 :: 		
$0463	$0CFA			RRF	STACK_10, F
;math.ppas,1605 :: 		
$0464	$0CF9			RRF	STACK_9, F
;math.ppas,1606 :: 		
$0465	$0CF8			RRF	STACK_8, F
;math.ppas,1607 :: 		
$0466	$0CF3			RRF	STACK_3, F
;math.ppas,1608 :: 		
$0467	$0CF2			RRF	STACK_2, F
;math.ppas,1609 :: 		
$0468	$0CF1			RRF	STACK_1, F
;math.ppas,1614 :: 		
$0469	$0CF0			RRF	STACK_0, F
;math.ppas,1615 :: 		
$046A	$1C03			BTFSS	STATUS, C
;math.ppas,1616 :: 		
$046B	$2C5E			GOTO	_NEXT
;math.ppas,1617 :: 		
$046C	$03FC			DECF	STACK_12, F
;math.ppas,1618 :: 		
$046D	$1903			BTFSC	STATUS, Z
;math.ppas,1625 :: 		
$046E	$2C7E			GOTO	_EXIT1
;math.ppas,1626 :: 		
$046F	$0874			MOVF	STACK_4, W
;math.ppas,1627 :: 		
$0470	$07F8			ADDWF	STACK_8, F
;math.ppas,1628 :: 		
$0471	$0875			MOVF	STACK_5, W
;math.ppas,1629 :: 		
$0472	$1803			BTFSC	STATUS, C
;math.ppas,1630 :: 		
$0473	$0F75			INCFSZ	STACK_5, W
;math.ppas,1631 :: 		
$0474	$07F9			ADDWF	STACK_9, F
;math.ppas,1632 :: 		
$0475	$0876			MOVF	STACK_6, W
;math.ppas,1633 :: 		
$0476	$1803			BTFSC	STATUS, C
;math.ppas,1634 :: 		
$0477	$0F76			INCFSZ	STACK_6, W
;math.ppas,1635 :: 		
$0478	$07FA			ADDWF	STACK_10, F
;math.ppas,1636 :: 		
$0479	$0877			MOVF	STACK_7, W
;math.ppas,1637 :: 		
$047A	$1803			BTFSC	STATUS, C
;math.ppas,1638 :: 		
$047B	$0F77			INCFSZ	STACK_7, W
;math.ppas,1640 :: 		
$047C	$07FB			ADDWF	STACK_11, F
;math.ppas,1642 :: 		
$047D	$2C62			GOTO	_LOOP
;math.ppas,1647 :: 		
$047E	$	_EXIT1:
;math.ppas,1648 :: 		
$047E	$0874			MOVF	STACK_4, W
;math.ppas,1649 :: 		
$047F	$07F8			ADDWF	STACK_8, F
;math.ppas,1650 :: 		
$0480	$0875			MOVF	STACK_5, W
;math.ppas,1651 :: 		
$0481	$1803			BTFSC	STATUS, C
;math.ppas,1652 :: 		
$0482	$0F75			INCFSZ	STACK_5, W
;math.ppas,1653 :: 		
$0483	$07F9			ADDWF	STACK_9, F
;math.ppas,1654 :: 		
$0484	$0876			MOVF	STACK_6, W
;math.ppas,1655 :: 		
$0485	$1803			BTFSC	STATUS, C
;math.ppas,1656 :: 		
$0486	$0F76			INCFSZ	STACK_6, W
;math.ppas,1657 :: 		
$0487	$07FA			ADDWF	STACK_10, F
;math.ppas,1658 :: 		
$0488	$0877			MOVF	STACK_7, W
;math.ppas,1659 :: 		
$0489	$1803			BTFSC	STATUS, C
;math.ppas,1660 :: 		
$048A	$0F77			INCFSZ	STACK_7, W
;math.ppas,1663 :: 		
$048B	$07FB			ADDWF	STACK_11, F
;math.ppas,1664 :: 		
$048C	$	_EXIT2:
;math.ppas,1665 :: 		
$048C	$	math_L_13:
;math.ppas,1666 :: 		
$048C	$0008			RETURN
$014E	$	_sdiv3232l:
$014E	$1303			BCF	STATUS, RP1
$014F	$1283			BCF	STATUS, RP0
;math.ppas,539 :: 		
;math.ppas,541 :: 		
$0150	$0874			MOVF	STACK_4, W
;math.ppas,542 :: 		
$0151	$02F8			SUBWF	STACK_8, F
;math.ppas,543 :: 		
$0152	$0875			MOVF	STACK_5, W
;math.ppas,544 :: 		
$0153	$1C03			BTFSS	STATUS, C
;math.ppas,545 :: 		
$0154	$0F75			INCFSZ	STACK_5, W
;math.ppas,546 :: 		
$0155	$02F9			SUBWF	STACK_9, F
;math.ppas,547 :: 		
$0156	$0876			MOVF	STACK_6, W
;math.ppas,548 :: 		
$0157	$1C03			BTFSS	STATUS, C
;math.ppas,549 :: 		
$0158	$0F76			INCFSZ	STACK_6, W
;math.ppas,550 :: 		
$0159	$02FA			SUBWF	STACK_10, F
;math.ppas,551 :: 		
$015A	$0877			MOVF	STACK_7, W
;math.ppas,552 :: 		
$015B	$1C03			BTFSS	STATUS, C
;math.ppas,553 :: 		
$015C	$0F77			INCFSZ	STACK_7, W
;math.ppas,554 :: 		
$015D	$02FB			SUBWF	STACK_11, F
;math.ppas,556 :: 		
$015E	$0DF3			RLF	STACK_3, F
;math.ppas,557 :: 		
$015F	$3007			MOVLW	7
;math.ppas,559 :: 		
$0160	$00FC			MOVWF	STACK_12
;math.ppas,560 :: 		
$0161	$	LOOPS3232A:
;math.ppas,561 :: 		
$0161	$0D73			RLF	STACK_3, W
;math.ppas,562 :: 		
$0162	$0DF8			RLF	STACK_8, F
;math.ppas,563 :: 		
$0163	$0DF9			RLF	STACK_9, F
;math.ppas,564 :: 		
$0164	$0DFA			RLF	STACK_10, F
;math.ppas,565 :: 		
$0165	$0DFB			RLF	STACK_11, F
;math.ppas,566 :: 		
$0166	$0874			MOVF	STACK_4, W
;math.ppas,567 :: 		
$0167	$1C73			BTFSS	STACK_3, 0
;math.ppas,569 :: 		
$0168	$2977			GOTO	SADD22LA
;math.ppas,570 :: 		
$0169	$02F8			SUBWF	STACK_8, F
;math.ppas,571 :: 		
$016A	$0875			MOVF	STACK_5, W
;math.ppas,572 :: 		
$016B	$1C03			BTFSS	STATUS, C
;math.ppas,573 :: 		
$016C	$0F75			INCFSZ	STACK_5, W
;math.ppas,574 :: 		
$016D	$02F9			SUBWF	STACK_9, F
;math.ppas,575 :: 		
$016E	$0876			MOVF	STACK_6, W
;math.ppas,576 :: 		
$016F	$1C03			BTFSS	STATUS, C
;math.ppas,577 :: 		
$0170	$0F76			INCFSZ	STACK_6, W
;math.ppas,578 :: 		
$0171	$02FA			SUBWF	STACK_10, F
;math.ppas,579 :: 		
$0172	$0877			MOVF	STACK_7, W
;math.ppas,580 :: 		
$0173	$1C03			BTFSS	STATUS, C
;math.ppas,581 :: 		
$0174	$0F77			INCFSZ	STACK_7, W
;math.ppas,582 :: 		
$0175	$02FB			SUBWF	STACK_11, F
;math.ppas,584 :: 		
$0176	$2984			GOTO	SOK22LA
;math.ppas,585 :: 		
$0177	$	SADD22LA:
;math.ppas,586 :: 		
$0177	$07F8			ADDWF	STACK_8, F
;math.ppas,587 :: 		
$0178	$0875			MOVF	STACK_5, W
;math.ppas,588 :: 		
$0179	$1803			BTFSC	STATUS, C
;math.ppas,589 :: 		
$017A	$0F75			INCFSZ	STACK_5, W
;math.ppas,590 :: 		
$017B	$07F9			ADDWF	STACK_9, F
;math.ppas,591 :: 		
$017C	$0876			MOVF	STACK_6, W
;math.ppas,592 :: 		
$017D	$1803			BTFSC	STATUS, C
;math.ppas,593 :: 		
$017E	$0F76			INCFSZ	STACK_6, W
;math.ppas,594 :: 		
$017F	$07FA			ADDWF	STACK_10, F
;math.ppas,595 :: 		
$0180	$0877			MOVF	STACK_7, W
;math.ppas,596 :: 		
$0181	$1803			BTFSC	STATUS, C
;math.ppas,597 :: 		
$0182	$0F77			INCFSZ	STACK_7, W
;math.ppas,599 :: 		
$0183	$07FB			ADDWF	STACK_11, F
;math.ppas,600 :: 		
$0184	$	SOK22LA:
;math.ppas,602 :: 		
$0184	$0DF3			RLF	STACK_3, F
;math.ppas,603 :: 		
$0185	$0BFC			DECFSZ	STACK_12, F
;math.ppas,605 :: 		
$0186	$2961			GOTO	LOOPS3232A
;math.ppas,606 :: 		
$0187	$0D72			RLF	STACK_2, W
;math.ppas,607 :: 		
$0188	$0DF8			RLF	STACK_8, F
;math.ppas,608 :: 		
$0189	$0DF9			RLF	STACK_9, F
;math.ppas,609 :: 		
$018A	$0DFA			RLF	STACK_10, F
;math.ppas,610 :: 		
$018B	$0DFB			RLF	STACK_11, F
;math.ppas,611 :: 		
$018C	$0874			MOVF	STACK_4, W
;math.ppas,612 :: 		
$018D	$1C73			BTFSS	STACK_3, 0
;math.ppas,614 :: 		
$018E	$299D			GOTO	SADD22L8
;math.ppas,615 :: 		
$018F	$02F8			SUBWF	STACK_8, F
;math.ppas,616 :: 		
$0190	$0875			MOVF	STACK_5, W
;math.ppas,617 :: 		
$0191	$1C03			BTFSS	STATUS, C
;math.ppas,618 :: 		
$0192	$0F75			INCFSZ	STACK_5, W
;math.ppas,619 :: 		
$0193	$02F9			SUBWF	STACK_9, F
;math.ppas,620 :: 		
$0194	$0876			MOVF	STACK_6, W
;math.ppas,621 :: 		
$0195	$1C03			BTFSS	STATUS, C
;math.ppas,622 :: 		
$0196	$0F76			INCFSZ	STACK_6, W
;math.ppas,623 :: 		
$0197	$02FA			SUBWF	STACK_10, F
;math.ppas,624 :: 		
$0198	$0877			MOVF	STACK_7, W
;math.ppas,625 :: 		
$0199	$1C03			BTFSS	STATUS, C
;math.ppas,626 :: 		
$019A	$0F77			INCFSZ	STACK_7, W
;math.ppas,627 :: 		
$019B	$02FB			SUBWF	STACK_11, F
;math.ppas,629 :: 		
$019C	$29AA			GOTO	SOK22L8
;math.ppas,630 :: 		
$019D	$	SADD22L8:
;math.ppas,631 :: 		
$019D	$07F8			ADDWF	STACK_8, F
;math.ppas,632 :: 		
$019E	$0875			MOVF	STACK_5, W
;math.ppas,633 :: 		
$019F	$1803			BTFSC	STATUS, C
;math.ppas,634 :: 		
$01A0	$0F75			INCFSZ	STACK_5, W
;math.ppas,635 :: 		
$01A1	$07F9			ADDWF	STACK_9, F
;math.ppas,636 :: 		
$01A2	$0876			MOVF	STACK_6, W
;math.ppas,637 :: 		
$01A3	$1803			BTFSC	STATUS, C
;math.ppas,638 :: 		
$01A4	$0F76			INCFSZ	STACK_6, W
;math.ppas,639 :: 		
$01A5	$07FA			ADDWF	STACK_10, F
;math.ppas,640 :: 		
$01A6	$0877			MOVF	STACK_7, W
;math.ppas,641 :: 		
$01A7	$1803			BTFSC	STATUS, C
;math.ppas,642 :: 		
$01A8	$0F77			INCFSZ	STACK_7, W
;math.ppas,644 :: 		
$01A9	$07FB			ADDWF	STACK_11, F
;math.ppas,645 :: 		
$01AA	$	SOK22L8:
;math.ppas,647 :: 		
$01AA	$0DF2			RLF	STACK_2, F
;math.ppas,648 :: 		
$01AB	$3007			MOVLW	7
;math.ppas,650 :: 		
$01AC	$00FC			MOVWF	STACK_12
;math.ppas,651 :: 		
$01AD	$	LOOPS3232B:
;math.ppas,652 :: 		
$01AD	$0D72			RLF	STACK_2, W
;math.ppas,653 :: 		
$01AE	$0DF8			RLF	STACK_8, F
;math.ppas,654 :: 		
$01AF	$0DF9			RLF	STACK_9, F
;math.ppas,655 :: 		
$01B0	$0DFA			RLF	STACK_10, F
;math.ppas,656 :: 		
$01B1	$0DFB			RLF	STACK_11, F
;math.ppas,657 :: 		
$01B2	$0874			MOVF	STACK_4, W
;math.ppas,658 :: 		
$01B3	$1C72			BTFSS	STACK_2, 0
;math.ppas,660 :: 		
$01B4	$29C3			GOTO	SADD22LB
;math.ppas,661 :: 		
$01B5	$02F8			SUBWF	STACK_8, F
;math.ppas,662 :: 		
$01B6	$0875			MOVF	STACK_5, W
;math.ppas,663 :: 		
$01B7	$1C03			BTFSS	STATUS, C
;math.ppas,664 :: 		
$01B8	$0F75			INCFSZ	STACK_5, W
;math.ppas,665 :: 		
$01B9	$02F9			SUBWF	STACK_9, F
;math.ppas,666 :: 		
$01BA	$0876			MOVF	STACK_6, W
;math.ppas,667 :: 		
$01BB	$1C03			BTFSS	STATUS, C
;math.ppas,668 :: 		
$01BC	$0F76			INCFSZ	STACK_6, W
;math.ppas,669 :: 		
$01BD	$02FA			SUBWF	STACK_10, F
;math.ppas,670 :: 		
$01BE	$0877			MOVF	STACK_7, W
;math.ppas,671 :: 		
$01BF	$1C03			BTFSS	STATUS, C
;math.ppas,672 :: 		
$01C0	$0F77			INCFSZ	STACK_7, W
;math.ppas,673 :: 		
$01C1	$02FB			SUBWF	STACK_11, F
;math.ppas,675 :: 		
$01C2	$29D0			GOTO	SOK22LB
;math.ppas,676 :: 		
$01C3	$	SADD22LB:
;math.ppas,677 :: 		
$01C3	$07F8			ADDWF	STACK_8, F
;math.ppas,678 :: 		
$01C4	$0875			MOVF	STACK_5, W
;math.ppas,679 :: 		
$01C5	$1803			BTFSC	STATUS, C
;math.ppas,680 :: 		
$01C6	$0F75			INCFSZ	STACK_5, W
;math.ppas,681 :: 		
$01C7	$07F9			ADDWF	STACK_9, F
;math.ppas,682 :: 		
$01C8	$0876			MOVF	STACK_6, W
;math.ppas,683 :: 		
$01C9	$1803			BTFSC	STATUS, C
;math.ppas,684 :: 		
$01CA	$0F76			INCFSZ	STACK_6, W
;math.ppas,685 :: 		
$01CB	$07FA			ADDWF	STACK_10, F
;math.ppas,686 :: 		
$01CC	$0877			MOVF	STACK_7, W
;math.ppas,687 :: 		
$01CD	$1803			BTFSC	STATUS, C
;math.ppas,688 :: 		
$01CE	$0F77			INCFSZ	STACK_7, W
;math.ppas,690 :: 		
$01CF	$07FB			ADDWF	STACK_11, F
;math.ppas,691 :: 		
$01D0	$	SOK22LB:
;math.ppas,693 :: 		
$01D0	$0DF2			RLF	STACK_2, F
;math.ppas,694 :: 		
$01D1	$0BFC			DECFSZ	STACK_12, F
;math.ppas,696 :: 		
$01D2	$29AD			GOTO	LOOPS3232B
;math.ppas,697 :: 		
$01D3	$0D71			RLF	STACK_1, W
;math.ppas,698 :: 		
$01D4	$0DF8			RLF	STACK_8, F
;math.ppas,699 :: 		
$01D5	$0DF9			RLF	STACK_9, F
;math.ppas,700 :: 		
$01D6	$0DFA			RLF	STACK_10, F
;math.ppas,701 :: 		
$01D7	$0DFB			RLF	STACK_11, F
;math.ppas,702 :: 		
$01D8	$0874			MOVF	STACK_4, W
;math.ppas,703 :: 		
$01D9	$1C72			BTFSS	STACK_2, 0
;math.ppas,705 :: 		
$01DA	$29E9			GOTO	SADD22L16
;math.ppas,706 :: 		
$01DB	$02F8			SUBWF	STACK_8, F
;math.ppas,707 :: 		
$01DC	$0875			MOVF	STACK_5, W
;math.ppas,708 :: 		
$01DD	$1C03			BTFSS	STATUS, C
;math.ppas,709 :: 		
$01DE	$0F75			INCFSZ	STACK_5, W
;math.ppas,710 :: 		
$01DF	$02F9			SUBWF	STACK_9, F
;math.ppas,711 :: 		
$01E0	$0876			MOVF	STACK_6, W
;math.ppas,712 :: 		
$01E1	$1C03			BTFSS	STATUS, C
;math.ppas,713 :: 		
$01E2	$0F76			INCFSZ	STACK_6, W
;math.ppas,714 :: 		
$01E3	$02FA			SUBWF	STACK_10, F
;math.ppas,715 :: 		
$01E4	$0877			MOVF	STACK_7, W
;math.ppas,716 :: 		
$01E5	$1C03			BTFSS	STATUS, C
;math.ppas,717 :: 		
$01E6	$0F77			INCFSZ	STACK_7, W
;math.ppas,718 :: 		
$01E7	$02FB			SUBWF	STACK_11, F
;math.ppas,720 :: 		
$01E8	$29F6			GOTO	SOK22L16
;math.ppas,721 :: 		
$01E9	$	SADD22L16:
;math.ppas,722 :: 		
$01E9	$07F8			ADDWF	STACK_8, F
;math.ppas,723 :: 		
$01EA	$0875			MOVF	STACK_5, W
;math.ppas,724 :: 		
$01EB	$1803			BTFSC	STATUS, C
;math.ppas,725 :: 		
$01EC	$0F75			INCFSZ	STACK_5, W
;math.ppas,726 :: 		
$01ED	$07F9			ADDWF	STACK_9, F
;math.ppas,727 :: 		
$01EE	$0876			MOVF	STACK_6, W
;math.ppas,728 :: 		
$01EF	$1803			BTFSC	STATUS, C
;math.ppas,729 :: 		
$01F0	$0F76			INCFSZ	STACK_6, W
;math.ppas,730 :: 		
$01F1	$07FA			ADDWF	STACK_10, F
;math.ppas,731 :: 		
$01F2	$0877			MOVF	STACK_7, W
;math.ppas,732 :: 		
$01F3	$1803			BTFSC	STATUS, C
;math.ppas,733 :: 		
$01F4	$0F77			INCFSZ	STACK_7, W
;math.ppas,735 :: 		
$01F5	$07FB			ADDWF	STACK_11, F
;math.ppas,736 :: 		
$01F6	$	SOK22L16:
;math.ppas,738 :: 		
$01F6	$0DF1			RLF	STACK_1, F
;math.ppas,739 :: 		
$01F7	$3007			MOVLW	7
;math.ppas,741 :: 		
$01F8	$00FC			MOVWF	STACK_12
;math.ppas,742 :: 		
$01F9	$	LOOPS3232C:
;math.ppas,743 :: 		
$01F9	$0D71			RLF	STACK_1, W
;math.ppas,744 :: 		
$01FA	$0DF8			RLF	STACK_8, F
;math.ppas,745 :: 		
$01FB	$0DF9			RLF	STACK_9, F
;math.ppas,746 :: 		
$01FC	$0DFA			RLF	STACK_10, F
;math.ppas,747 :: 		
$01FD	$0DFB			RLF	STACK_11, F
;math.ppas,748 :: 		
$01FE	$0874			MOVF	STACK_4, W
;math.ppas,749 :: 		
$01FF	$1C71			BTFSS	STACK_1, 0
;math.ppas,751 :: 		
$0200	$2A0F			GOTO	SADD22LC
;math.ppas,752 :: 		
$0201	$02F8			SUBWF	STACK_8, F
;math.ppas,753 :: 		
$0202	$0875			MOVF	STACK_5, W
;math.ppas,754 :: 		
$0203	$1C03			BTFSS	STATUS, C
;math.ppas,755 :: 		
$0204	$0F75			INCFSZ	STACK_5, W
;math.ppas,756 :: 		
$0205	$02F9			SUBWF	STACK_9, F
;math.ppas,757 :: 		
$0206	$0876			MOVF	STACK_6, W
;math.ppas,758 :: 		
$0207	$1C03			BTFSS	STATUS, C
;math.ppas,759 :: 		
$0208	$0F76			INCFSZ	STACK_6, W
;math.ppas,760 :: 		
$0209	$02FA			SUBWF	STACK_10, F
;math.ppas,761 :: 		
$020A	$0877			MOVF	STACK_7, W
;math.ppas,762 :: 		
$020B	$1C03			BTFSS	STATUS, C
;math.ppas,763 :: 		
$020C	$0F77			INCFSZ	STACK_7, W
;math.ppas,764 :: 		
$020D	$02FB			SUBWF	STACK_11, F
;math.ppas,766 :: 		
$020E	$2A1C			GOTO	SOK22LC
;math.ppas,767 :: 		
$020F	$	SADD22LC:
;math.ppas,768 :: 		
$020F	$07F8			ADDWF	STACK_8, F
;math.ppas,769 :: 		
$0210	$0875			MOVF	STACK_5, W
;math.ppas,770 :: 		
$0211	$1803			BTFSC	STATUS, C
;math.ppas,771 :: 		
$0212	$0F75			INCFSZ	STACK_5, W
;math.ppas,772 :: 		
$0213	$07F9			ADDWF	STACK_9, F
;math.ppas,773 :: 		
$0214	$0876			MOVF	STACK_6, W
;math.ppas,774 :: 		
$0215	$1803			BTFSC	STATUS, C
;math.ppas,775 :: 		
$0216	$0F76			INCFSZ	STACK_6, W
;math.ppas,776 :: 		
$0217	$07FA			ADDWF	STACK_10, F
;math.ppas,777 :: 		
$0218	$0877			MOVF	STACK_7, W
;math.ppas,778 :: 		
$0219	$1803			BTFSC	STATUS, C
;math.ppas,779 :: 		
$021A	$0F77			INCFSZ	STACK_7, W
;math.ppas,781 :: 		
$021B	$07FB			ADDWF	STACK_11, F
;math.ppas,782 :: 		
$021C	$	SOK22LC:
;math.ppas,784 :: 		
$021C	$0DF1			RLF	STACK_1, F
;math.ppas,785 :: 		
$021D	$0BFC			DECFSZ	STACK_12, F
;math.ppas,787 :: 		
$021E	$29F9			GOTO	LOOPS3232C
;math.ppas,788 :: 		
$021F	$0D70			RLF	STACK_0, W
;math.ppas,789 :: 		
$0220	$0DF8			RLF	STACK_8, F
;math.ppas,790 :: 		
$0221	$0DF9			RLF	STACK_9, F
;math.ppas,791 :: 		
$0222	$0DFA			RLF	STACK_10, F
;math.ppas,792 :: 		
$0223	$0DFB			RLF	STACK_11, F
;math.ppas,793 :: 		
$0224	$0874			MOVF	STACK_4, W
;math.ppas,794 :: 		
$0225	$1C71			BTFSS	STACK_1, 0
;math.ppas,796 :: 		
$0226	$2A35			GOTO	SADD22L24
;math.ppas,797 :: 		
$0227	$02F8			SUBWF	STACK_8, F
;math.ppas,798 :: 		
$0228	$0875			MOVF	STACK_5, W
;math.ppas,799 :: 		
$0229	$1C03			BTFSS	STATUS, C
;math.ppas,800 :: 		
$022A	$0F75			INCFSZ	STACK_5, W
;math.ppas,801 :: 		
$022B	$02F9			SUBWF	STACK_9, F
;math.ppas,802 :: 		
$022C	$0876			MOVF	STACK_6, W
;math.ppas,803 :: 		
$022D	$1C03			BTFSS	STATUS, C
;math.ppas,804 :: 		
$022E	$0F76			INCFSZ	STACK_6, W
;math.ppas,805 :: 		
$022F	$02FA			SUBWF	STACK_10, F
;math.ppas,806 :: 		
$0230	$0877			MOVF	STACK_7, W
;math.ppas,807 :: 		
$0231	$1C03			BTFSS	STATUS, C
;math.ppas,808 :: 		
$0232	$0F77			INCFSZ	STACK_7, W
;math.ppas,809 :: 		
$0233	$02FB			SUBWF	STACK_11, F
;math.ppas,811 :: 		
$0234	$2A42			GOTO	SOK22L24
;math.ppas,812 :: 		
$0235	$	SADD22L24:
;math.ppas,813 :: 		
$0235	$07F8			ADDWF	STACK_8, F
;math.ppas,814 :: 		
$0236	$0875			MOVF	STACK_5, W
;math.ppas,815 :: 		
$0237	$1803			BTFSC	STATUS, C
;math.ppas,816 :: 		
$0238	$0F75			INCFSZ	STACK_5, W
;math.ppas,817 :: 		
$0239	$07F9			ADDWF	STACK_9, F
;math.ppas,818 :: 		
$023A	$0876			MOVF	STACK_6, W
;math.ppas,819 :: 		
$023B	$1803			BTFSC	STATUS, C
;math.ppas,820 :: 		
$023C	$0F76			INCFSZ	STACK_6, W
;math.ppas,821 :: 		
$023D	$07FA			ADDWF	STACK_10, F
;math.ppas,822 :: 		
$023E	$0877			MOVF	STACK_7, W
;math.ppas,823 :: 		
$023F	$1803			BTFSC	STATUS, C
;math.ppas,824 :: 		
$0240	$0F77			INCFSZ	STACK_7, W
;math.ppas,826 :: 		
$0241	$07FB			ADDWF	STACK_11, F
;math.ppas,827 :: 		
$0242	$	SOK22L24:
;math.ppas,829 :: 		
$0242	$0DF0			RLF	STACK_0, F
;math.ppas,830 :: 		
$0243	$3007			MOVLW	7
;math.ppas,832 :: 		
$0244	$00FC			MOVWF	STACK_12
;math.ppas,833 :: 		
$0245	$	LOOPS3232D:
;math.ppas,834 :: 		
$0245	$0D70			RLF	STACK_0, W
;math.ppas,835 :: 		
$0246	$0DF8			RLF	STACK_8, F
;math.ppas,836 :: 		
$0247	$0DF9			RLF	STACK_9, F
;math.ppas,837 :: 		
$0248	$0DFA			RLF	STACK_10, F
;math.ppas,838 :: 		
$0249	$0DFB			RLF	STACK_11, F
;math.ppas,839 :: 		
$024A	$0874			MOVF	STACK_4, W
;math.ppas,840 :: 		
$024B	$1C70			BTFSS	STACK_0, 0
;math.ppas,842 :: 		
$024C	$2A5B			GOTO	SADD22LD
;math.ppas,843 :: 		
$024D	$02F8			SUBWF	STACK_8, F
;math.ppas,844 :: 		
$024E	$0875			MOVF	STACK_5, W
;math.ppas,845 :: 		
$024F	$1C03			BTFSS	STATUS, C
;math.ppas,846 :: 		
$0250	$0F75			INCFSZ	STACK_5, W
;math.ppas,847 :: 		
$0251	$02F9			SUBWF	STACK_9, F
;math.ppas,848 :: 		
$0252	$0876			MOVF	STACK_6, W
;math.ppas,849 :: 		
$0253	$1C03			BTFSS	STATUS, C
;math.ppas,850 :: 		
$0254	$0F76			INCFSZ	STACK_6, W
;math.ppas,851 :: 		
$0255	$02FA			SUBWF	STACK_10, F
;math.ppas,852 :: 		
$0256	$0877			MOVF	STACK_7, W
;math.ppas,853 :: 		
$0257	$1C03			BTFSS	STATUS, C
;math.ppas,854 :: 		
$0258	$0F77			INCFSZ	STACK_7, W
;math.ppas,855 :: 		
$0259	$02FB			SUBWF	STACK_11, F
;math.ppas,857 :: 		
$025A	$2A68			GOTO	SOK22LD
;math.ppas,858 :: 		
$025B	$	SADD22LD:
;math.ppas,859 :: 		
$025B	$07F8			ADDWF	STACK_8, F
;math.ppas,860 :: 		
$025C	$0875			MOVF	STACK_5, W
;math.ppas,861 :: 		
$025D	$1803			BTFSC	STATUS, C
;math.ppas,862 :: 		
$025E	$0F75			INCFSZ	STACK_5, W
;math.ppas,863 :: 		
$025F	$07F9			ADDWF	STACK_9, F
;math.ppas,864 :: 		
$0260	$0876			MOVF	STACK_6, W
;math.ppas,865 :: 		
$0261	$1803			BTFSC	STATUS, C
;math.ppas,866 :: 		
$0262	$0F76			INCFSZ	STACK_6, W
;math.ppas,867 :: 		
$0263	$07FA			ADDWF	STACK_10, F
;math.ppas,868 :: 		
$0264	$0877			MOVF	STACK_7, W
;math.ppas,870 :: 		
$0265	$1803			BTFSC	STATUS, C
;math.ppas,871 :: 		
$0266	$0F77			INCFSZ	STACK_7, W
;math.ppas,873 :: 		
$0267	$07FB			ADDWF	STACK_11, F
;math.ppas,874 :: 		
$0268	$	SOK22LD:
;math.ppas,876 :: 		
$0268	$0DF0			RLF	STACK_0, F
;math.ppas,877 :: 		
$0269	$0BFC			DECFSZ	STACK_12, F
;math.ppas,879 :: 		
$026A	$2A45			GOTO	LOOPS3232D
;math.ppas,880 :: 		
$026B	$1870			BTFSC	STACK_0, 0
;math.ppas,881 :: 		
$026C	$2A7B			GOTO	SOK22L
;math.ppas,882 :: 		
$026D	$0874			MOVF	STACK_4, W
;math.ppas,883 :: 		
$026E	$07F8			ADDWF	STACK_8, F
;math.ppas,884 :: 		
$026F	$0875			MOVF	STACK_5, W
;math.ppas,885 :: 		
$0270	$1803			BTFSC	STATUS, C
;math.ppas,886 :: 		
$0271	$0F75			INCFSZ	STACK_5, W
;math.ppas,887 :: 		
$0272	$07F9			ADDWF	STACK_9, F
;math.ppas,888 :: 		
$0273	$0876			MOVF	STACK_6, W
;math.ppas,889 :: 		
$0274	$1803			BTFSC	STATUS, C
;math.ppas,890 :: 		
$0275	$0F76			INCFSZ	STACK_6, W
;math.ppas,891 :: 		
$0276	$07FA			ADDWF	STACK_10, F
;math.ppas,892 :: 		
$0277	$0877			MOVF	STACK_7, W
;math.ppas,893 :: 		
$0278	$1803			BTFSC	STATUS, C
;math.ppas,894 :: 		
$0279	$0F77			INCFSZ	STACK_7, W
;math.ppas,895 :: 		
$027A	$07FB			ADDWF	STACK_11, F
;math.ppas,896 :: 		
$027B	$	SOK22L:
;math.ppas,897 :: 		
$027B	$	math_L_9:
;math.ppas,898 :: 		
$027B	$0008			RETURN
$050D	$	_comfrem:
$050D	$1303			BCF	STATUS, RP1
$050E	$1283			BCF	STATUS, RP0
;math.ppas,901 :: 		
;math.ppas,903 :: 		
$050F	$09FB			COMF	STACK_11, F
;math.ppas,904 :: 		
$0510	$09FA			COMF	STACK_10, F
;math.ppas,905 :: 		
$0511	$09F9			COMF	STACK_9, F
;math.ppas,906 :: 		
$0512	$09F8			COMF	STACK_8, F
;math.ppas,907 :: 		
$0513	$0AF8			INCF	STACK_8, F
;math.ppas,908 :: 		
$0514	$1903			BTFSC	STATUS, Z
;math.ppas,909 :: 		
$0515	$0AF9			INCF	STACK_9, F
;math.ppas,910 :: 		
$0516	$1903			BTFSC	STATUS, Z
;math.ppas,911 :: 		
$0517	$0AFA			INCF	STACK_10, F
;math.ppas,912 :: 		
$0518	$1903			BTFSC	STATUS, Z
;math.ppas,913 :: 		
$0519	$0AFB			INCF	STACK_11, F
;math.ppas,914 :: 		
$051A	$	math_L_10:
;math.ppas,915 :: 		
$051A	$0008			RETURN
$0528	$	_usart_data_ready:
;USART_b75.ppas,48 :: 		
;USART_b75.ppas,50 :: 		
$0528	$1303			BCF	STATUS, RP1
$0529	$1283			BCF	STATUS, RP0
$052A	$080C			MOVF	PIR1, 0
$052B	$00F1			MOVWF	STACK_1
$052C	$3000			MOVLW	0
$052D	$1AF1			BTFSC	STACK_1, 5
$052E	$3001			MOVLW	1
$052F	$00F1			MOVWF	STACK_1
$0530	$0871			MOVF	STACK_1, 0
$0531	$00BB			MOVWF	_usart_data_ready_local_result
$0532	$	USART_b75_L_18:
;USART_b75.ppas,51 :: 		
$0532	$083B			MOVF	_usart_data_ready_local_result, 0
$0533	$00F0			MOVWF	STACK_0
$0534	$0008			RETURN
$04D5	$	_usart_read:
;USART_b75.ppas,54 :: 		
;USART_b75.ppas,55 :: 		
$04D5	$1303			BCF	STATUS, RP1
$04D6	$1283			BCF	STATUS, RP0
$04D7	$081A			MOVF	RCREG, 0
$04D8	$00BB			MOVWF	_usart_read_local_result
;USART_b75.ppas,61 :: 		
$04D9	$0818			MOVF	RCSTA, 0
$04DA	$00F1			MOVWF	STACK_1
$04DB	$3000			MOVLW	0
$04DC	$18F1			BTFSC	STACK_1, 1
$04DD	$3001			MOVLW	1
$04DE	$00F1			MOVWF	STACK_1
$04DF	$0871			MOVF	STACK_1, 0
$04E0	$3A01			XORLW	1
$04E1	$1D03			BTFSS	STATUS, Z
$04E2	$2CE5			GOTO	USART_b75_L_21
$04E3	$	USART_b75_L_20:
;USART_b75.ppas,63 :: 		
$04E3	$1218			BCF	RCSTA, 4
$04E4	$	USART_b75_L_24:
;USART_b75.ppas,64 :: 		
$04E4	$	USART_b75_L_25:
$04E4	$1618			BSF	RCSTA, 4
$04E5	$	USART_b75_L_26:
;USART_b75.ppas,65 :: 		
$04E5	$	USART_b75_L_21:
$04E5	$	USART_b75_L_22:
$04E5	$	USART_b75_L_19:
;USART_b75.ppas,66 :: 		
$04E5	$083B			MOVF	_usart_read_local_result, 0
$04E6	$00F0			MOVWF	STACK_0
$04E7	$0008			RETURN
$041B	$	_mul_32x32_s:
$041B	$1303			BCF	STATUS, RP1
$041C	$1283			BCF	STATUS, RP0
;math.ppas,1675 :: 		
;math.ppas,1680 :: 		
$041D	$01FD			CLRF	STACK_13
;math.ppas,1683 :: 		
$041E	$	_IF_FIRST:
;math.ppas,1684 :: 		
$041E	$1FF3			BTFSS	STACK_3, 7
;math.ppas,1686 :: 		
$041F	$2C2D			GOTO	_IF_SECOND
;math.ppas,1691 :: 		
$0420	$	_INVERCE_FIRST:
;math.ppas,1692 :: 		
$0420	$09F0			COMF	STACK_0, F
;math.ppas,1693 :: 		
$0421	$09F1			COMF	STACK_1, F
;math.ppas,1694 :: 		
$0422	$09F2			COMF	STACK_2, F
;math.ppas,1701 :: 		
$0423	$09F3			COMF	STACK_3, F
;math.ppas,1702 :: 		
$0424	$0AF0			INCF	STACK_0, F
;math.ppas,1703 :: 		
$0425	$1903			BTFSC	STATUS, Z
;math.ppas,1704 :: 		
$0426	$0AF1			INCF	STACK_1, F
;math.ppas,1705 :: 		
$0427	$1903			BTFSC	STATUS, Z
;math.ppas,1706 :: 		
$0428	$0AF2			INCF	STACK_2, F
;math.ppas,1707 :: 		
$0429	$1903			BTFSC	STATUS, Z
;math.ppas,1708 :: 		
$042A	$0AF3			INCF	STACK_3, F
;math.ppas,1709 :: 		
$042B	$3081			MOVLW	129
;math.ppas,1711 :: 		
$042C	$07FD			ADDWF	STACK_13, F
;math.ppas,1714 :: 		
$042D	$	_IF_SECOND:
;math.ppas,1715 :: 		
$042D	$1FF7			BTFSS	STACK_7, 7
;math.ppas,1717 :: 		
$042E	$2C3B			GOTO	_MULT
;math.ppas,1722 :: 		
$042F	$	_INBERSE_SECOND:
;math.ppas,1723 :: 		
$042F	$09F4			COMF	STACK_4, F
;math.ppas,1724 :: 		
$0430	$09F5			COMF	STACK_5, F
;math.ppas,1725 :: 		
$0431	$09F6			COMF	STACK_6, F
;math.ppas,1732 :: 		
$0432	$09F7			COMF	STACK_7, F
;math.ppas,1733 :: 		
$0433	$0AF4			INCF	STACK_4, F
;math.ppas,1734 :: 		
$0434	$1903			BTFSC	STATUS, Z
;math.ppas,1735 :: 		
$0435	$0AF5			INCF	STACK_5, F
;math.ppas,1736 :: 		
$0436	$1903			BTFSC	STATUS, Z
;math.ppas,1737 :: 		
$0437	$0AF6			INCF	STACK_6, F
;math.ppas,1738 :: 		
$0438	$1903			BTFSC	STATUS, Z
;math.ppas,1739 :: 		
$0439	$0AF7			INCF	STACK_7, F
;math.ppas,1741 :: 		
$043A	$0AFD			INCF	STACK_13, F
;math.ppas,1742 :: 		
$043B	$	_MULT:
;math.ppas,1744 :: 		
$043B	$2456			CALL	_mul_32x32_u
;math.ppas,1748 :: 		
$043C	$1C7D			BTFSS	STACK_13, 0
;math.ppas,1754 :: 		
$043D	$2C55			GOTO	_EXIT
;math.ppas,1755 :: 		
$043E	$09F0			COMF	STACK_0, F
;math.ppas,1756 :: 		
$043F	$09F1			COMF	STACK_1, F
;math.ppas,1757 :: 		
$0440	$09F2			COMF	STACK_2, F
;math.ppas,1763 :: 		
$0441	$09F3			COMF	STACK_3, F
;math.ppas,1764 :: 		
$0442	$09F8			COMF	STACK_8, F
;math.ppas,1765 :: 		
$0443	$09F9			COMF	STACK_9, F
;math.ppas,1766 :: 		
$0444	$09FA			COMF	STACK_10, F
;math.ppas,1776 :: 		
$0445	$09FB			COMF	STACK_11, F
;math.ppas,1777 :: 		
$0446	$0AF0			INCF	STACK_0, F
;math.ppas,1778 :: 		
$0447	$1903			BTFSC	STATUS, Z
;math.ppas,1779 :: 		
$0448	$0AF1			INCF	STACK_1, F
;math.ppas,1780 :: 		
$0449	$1903			BTFSC	STATUS, Z
;math.ppas,1781 :: 		
$044A	$0AF2			INCF	STACK_2, F
;math.ppas,1782 :: 		
$044B	$1903			BTFSC	STATUS, Z
;math.ppas,1783 :: 		
$044C	$0AF3			INCF	STACK_3, F
;math.ppas,1784 :: 		
$044D	$1903			BTFSC	STATUS, Z
;math.ppas,1785 :: 		
$044E	$0AF8			INCF	STACK_8, F
;math.ppas,1786 :: 		
$044F	$1903			BTFSC	STATUS, Z
;math.ppas,1787 :: 		
$0450	$0AF9			INCF	STACK_9, F
;math.ppas,1788 :: 		
$0451	$1903			BTFSC	STATUS, Z
;math.ppas,1789 :: 		
$0452	$0AFA			INCF	STACK_10, F
;math.ppas,1790 :: 		
$0453	$1903			BTFSC	STATUS, Z
;math.ppas,1791 :: 		
$0454	$0AFB			INCF	STACK_11, F
;math.ppas,1792 :: 		
$0455	$	_EXIT:
;math.ppas,1793 :: 		
$0455	$	math_L_14:
;math.ppas,1794 :: 		
$0455	$0008			RETURN
$048D	$	_div_16x16_u:
$048D	$1303			BCF	STATUS, RP1
$048E	$1283			BCF	STATUS, RP0
;math.ppas,108 :: 		
;math.ppas,110 :: 		
$048F	$01F8			CLRF	STACK_8
;math.ppas,111 :: 		
$0490	$01F9			CLRF	STACK_9
;math.ppas,112 :: 		
$0491	$3010			MOVLW	16
;math.ppas,113 :: 		
$0492	$00FC			MOVWF	STACK_12
;math.ppas,114 :: 		
$0493	$0D71			RLF	STACK_1, W
;math.ppas,115 :: 		
$0494	$0DF8			RLF	STACK_8, F
;math.ppas,116 :: 		
$0495	$0DF9			RLF	STACK_9, F
;math.ppas,117 :: 		
$0496	$0874			MOVF	STACK_4, W
;math.ppas,118 :: 		
$0497	$02F8			SUBWF	STACK_8, F
;math.ppas,119 :: 		
$0498	$0875			MOVF	STACK_5, W
;math.ppas,120 :: 		
$0499	$1C03			BTFSS	STATUS, C
;math.ppas,121 :: 		
$049A	$0F75			INCFSZ	STACK_5, W
;math.ppas,122 :: 		
$049B	$02F9			SUBWF	STACK_9, F
;math.ppas,123 :: 		
$049C	$1803			BTFSC	STATUS, C
;math.ppas,124 :: 		
$049D	$2CA5			GOTO	$+8
;math.ppas,125 :: 		
$049E	$0874			MOVF	STACK_4, W
;math.ppas,126 :: 		
$049F	$07F8			ADDWF	STACK_8, F
;math.ppas,127 :: 		
$04A0	$0875			MOVF	STACK_5, W
;math.ppas,128 :: 		
$04A1	$1803			BTFSC	STATUS, C
;math.ppas,129 :: 		
$04A2	$0F75			INCFSZ	STACK_5, W
;math.ppas,130 :: 		
$04A3	$07F9			ADDWF	STACK_9, F
;math.ppas,131 :: 		
$04A4	$1003			BCF	STATUS, C
;math.ppas,132 :: 		
$04A5	$0DF0			RLF	STACK_0, F
;math.ppas,133 :: 		
$04A6	$0DF1			RLF	STACK_1, F
;math.ppas,134 :: 		
$04A7	$0BFC			DECFSZ	STACK_12, F
;math.ppas,135 :: 		
$04A8	$2C93			GOTO	$-21
;math.ppas,136 :: 		
$04A9	$	math_L_3:
;math.ppas,137 :: 		
$04A9	$0008			RETURN
$033E	$	_div_32x32_s:
$033E	$1303			BCF	STATUS, RP1
$033F	$1283			BCF	STATUS, RP0
;math.ppas,925 :: 		
;math.ppas,928 :: 		
$0340	$	FXD3232S:
;math.ppas,929 :: 		
$0340	$01FC			CLRF	STACK_12
;math.ppas,930 :: 		
$0341	$1BF7			BTFSC	STACK_7, 7
;math.ppas,932 :: 		
$0342	$0AFC			INCF	STACK_12, F
;math.ppas,933 :: 		
$0343	$01FD			CLRF	STACK_13
;math.ppas,934 :: 		
$0344	$01FB			CLRF	STACK_11
;math.ppas,935 :: 		
$0345	$01FA			CLRF	STACK_10
;math.ppas,936 :: 		
$0346	$01F9			CLRF	STACK_9
;math.ppas,937 :: 		
$0347	$01F8			CLRF	STACK_8
;math.ppas,938 :: 		
$0348	$0873			MOVF	STACK_3, W
;math.ppas,939 :: 		
$0349	$0472			IORWF	STACK_2, W
;math.ppas,940 :: 		
$034A	$0471			IORWF	STACK_1, W
;math.ppas,941 :: 		
$034B	$0470			IORWF	STACK_0, W
;math.ppas,942 :: 		
$034C	$1903			BTFSC	STATUS, Z
;math.ppas,943 :: 		
$034D	$2BD2			GOTO	END_ALL
;math.ppas,944 :: 		
$034E	$0873			MOVF	STACK_3, W
;math.ppas,945 :: 		
$034F	$0677			XORWF	STACK_7, W
;math.ppas,946 :: 		
$0350	$00A0			MOVWF	MATH___MATH_TEMPB
;math.ppas,947 :: 		
$0351	$1BA0			BTFSC	MATH___MATH_TEMPB, 7
;math.ppas,951 :: 		
$0352	$09FD			COMF	STACK_13, F
;math.ppas,952 :: 		
$0353	$1FF7			BTFSS	STACK_7, 7
;math.ppas,954 :: 		
$0354	$2B60			GOTO	CA3232S
;math.ppas,955 :: 		
$0355	$09F4			COMF	STACK_4, F
;math.ppas,956 :: 		
$0356	$09F5			COMF	STACK_5, F
;math.ppas,957 :: 		
$0357	$09F6			COMF	STACK_6, F
;math.ppas,958 :: 		
$0358	$09F7			COMF	STACK_7, F
;math.ppas,959 :: 		
$0359	$0AF4			INCF	STACK_4, F
;math.ppas,960 :: 		
$035A	$1903			BTFSC	STATUS, Z
;math.ppas,961 :: 		
$035B	$0AF5			INCF	STACK_5, F
;math.ppas,962 :: 		
$035C	$1903			BTFSC	STATUS, Z
;math.ppas,963 :: 		
$035D	$0AF6			INCF	STACK_6, F
;math.ppas,964 :: 		
$035E	$1903			BTFSC	STATUS, Z
;math.ppas,966 :: 		
$035F	$0AF7			INCF	STACK_7, F
;math.ppas,967 :: 		
$0360	$	CA3232S:
;math.ppas,968 :: 		
$0360	$1FF3			BTFSS	STACK_3, 7
;math.ppas,970 :: 		
$0361	$2B6D			GOTO	C3232SX
;math.ppas,971 :: 		
$0362	$09F0			COMF	STACK_0, F
;math.ppas,972 :: 		
$0363	$09F1			COMF	STACK_1, F
;math.ppas,973 :: 		
$0364	$09F2			COMF	STACK_2, F
;math.ppas,974 :: 		
$0365	$09F3			COMF	STACK_3, F
;math.ppas,975 :: 		
$0366	$0AF0			INCF	STACK_0, F
;math.ppas,976 :: 		
$0367	$1903			BTFSC	STATUS, Z
;math.ppas,977 :: 		
$0368	$0AF1			INCF	STACK_1, F
;math.ppas,978 :: 		
$0369	$1903			BTFSC	STATUS, Z
;math.ppas,979 :: 		
$036A	$0AF2			INCF	STACK_2, F
;math.ppas,980 :: 		
$036B	$1903			BTFSC	STATUS, Z
;math.ppas,982 :: 		
$036C	$0AF3			INCF	STACK_3, F
;math.ppas,983 :: 		
$036D	$	C3232SX:
;math.ppas,984 :: 		
$036D	$0873			MOVF	STACK_3, W
;math.ppas,985 :: 		
$036E	$0477			IORWF	STACK_7, W
;math.ppas,986 :: 		
$036F	$00A0			MOVWF	MATH___MATH_TEMPB
;math.ppas,987 :: 		
$0370	$1BA0			BTFSC	MATH___MATH_TEMPB, 7
;math.ppas,988 :: 		
$0371	$2B8E			GOTO	C3232SX1
;math.ppas,989 :: 		
$0372	$	C3232S:
;math.ppas,992 :: 		
$0372	$214E			CALL	_sdiv3232l
;math.ppas,995 :: 		
$0373	$	C3232S2:
;math.ppas,996 :: 		
$0373	$1BFC			BTFSC	STACK_12, 7
;math.ppas,997 :: 		
$0374	$2BAB			GOTO	C3232SX4
;math.ppas,998 :: 		
$0375	$	C3232SOK:
;math.ppas,999 :: 		
$0375	$1FFD			BTFSS	STACK_13, 7
;math.ppas,1000 :: 		
$0376	$2BD2			GOTO	END_ALL
;math.ppas,1001 :: 		
$0377	$09F0			COMF	STACK_0, F
;math.ppas,1002 :: 		
$0378	$09F1			COMF	STACK_1, F
;math.ppas,1003 :: 		
$0379	$09F2			COMF	STACK_2, F
;math.ppas,1004 :: 		
$037A	$09F3			COMF	STACK_3, F
;math.ppas,1005 :: 		
$037B	$0AF0			INCF	STACK_0, F
;math.ppas,1006 :: 		
$037C	$1903			BTFSC	STATUS, Z
;math.ppas,1007 :: 		
$037D	$0AF1			INCF	STACK_1, F
;math.ppas,1008 :: 		
$037E	$1903			BTFSC	STATUS, Z
;math.ppas,1009 :: 		
$037F	$0AF2			INCF	STACK_2, F
;math.ppas,1010 :: 		
$0380	$1903			BTFSC	STATUS, Z
;math.ppas,1012 :: 		
$0381	$0AF3			INCF	STACK_3, F
;math.ppas,1013 :: 		
$0382	$09F8			COMF	STACK_8, F
;math.ppas,1014 :: 		
$0383	$09F9			COMF	STACK_9, F
;math.ppas,1015 :: 		
$0384	$09FA			COMF	STACK_10, F
;math.ppas,1016 :: 		
$0385	$09FB			COMF	STACK_11, F
;math.ppas,1017 :: 		
$0386	$0AF8			INCF	STACK_8, F
;math.ppas,1018 :: 		
$0387	$1903			BTFSC	STATUS, Z
;math.ppas,1019 :: 		
$0388	$0AF9			INCF	STACK_9, F
;math.ppas,1020 :: 		
$0389	$1903			BTFSC	STATUS, Z
;math.ppas,1021 :: 		
$038A	$0AFA			INCF	STACK_10, F
;math.ppas,1022 :: 		
$038B	$1903			BTFSC	STATUS, Z
;math.ppas,1024 :: 		
$038C	$0AFB			INCF	STACK_11, F
;math.ppas,1025 :: 		
$038D	$2BD2			GOTO	END_ALL
;math.ppas,1026 :: 		
$038E	$	C3232SX1:
;math.ppas,1027 :: 		
$038E	$1FF7			BTFSS	STACK_7, 7
;math.ppas,1028 :: 		
$038F	$2BA5			GOTO	C3232SX3
;math.ppas,1029 :: 		
$0390	$1BF3			BTFSC	STACK_3, 7
;math.ppas,1030 :: 		
$0391	$2B9F			GOTO	C3232SX2
;math.ppas,1031 :: 		
$0392	$0873			MOVF	STACK_3, W
;math.ppas,1032 :: 		
$0393	$00FB			MOVWF	STACK_11
;math.ppas,1033 :: 		
$0394	$0872			MOVF	STACK_2, W
;math.ppas,1034 :: 		
$0395	$00FA			MOVWF	STACK_10
;math.ppas,1035 :: 		
$0396	$0871			MOVF	STACK_1, W
;math.ppas,1036 :: 		
$0397	$00F9			MOVWF	STACK_9
;math.ppas,1037 :: 		
$0398	$0870			MOVF	STACK_0, W
;math.ppas,1038 :: 		
$0399	$00F8			MOVWF	STACK_8
;math.ppas,1039 :: 		
$039A	$01F3			CLRF	STACK_3
;math.ppas,1040 :: 		
$039B	$01F2			CLRF	STACK_2
;math.ppas,1041 :: 		
$039C	$01F1			CLRF	STACK_1
;math.ppas,1042 :: 		
$039D	$01F0			CLRF	STACK_0
;math.ppas,1043 :: 		
$039E	$2B75			GOTO	C3232SOK
;math.ppas,1044 :: 		
$039F	$	C3232SX2:
;math.ppas,1045 :: 		
$039F	$01F3			CLRF	STACK_3
;math.ppas,1046 :: 		
$03A0	$01F2			CLRF	STACK_2
;math.ppas,1047 :: 		
$03A1	$01F1			CLRF	STACK_1
;math.ppas,1048 :: 		
$03A2	$01F0			CLRF	STACK_0
;math.ppas,1049 :: 		
$03A3	$0AF0			INCF	STACK_0, F
;math.ppas,1051 :: 		
$03A4	$3400			RETLW	0X00
;math.ppas,1052 :: 		
$03A5	$	C3232SX3:
;math.ppas,1053 :: 		
$03A5	$09F3			COMF	STACK_3, F
;math.ppas,1054 :: 		
$03A6	$09F2			COMF	STACK_2, F
;math.ppas,1055 :: 		
$03A7	$09F1			COMF	STACK_1, F
;math.ppas,1057 :: 		
$03A8	$09F0			COMF	STACK_0, F
;math.ppas,1059 :: 		
$03A9	$17FC			BSF	STACK_12, 7
;math.ppas,1060 :: 		
$03AA	$2B72			GOTO	C3232S
;math.ppas,1061 :: 		
$03AB	$	C3232SX4:
;math.ppas,1062 :: 		
$03AB	$0AF8			INCF	STACK_8, F
;math.ppas,1063 :: 		
$03AC	$1903			BTFSC	STATUS, Z
;math.ppas,1064 :: 		
$03AD	$0AF9			INCF	STACK_9, F
;math.ppas,1065 :: 		
$03AE	$1903			BTFSC	STATUS, Z
;math.ppas,1066 :: 		
$03AF	$0AFA			INCF	STACK_10, F
;math.ppas,1067 :: 		
$03B0	$1903			BTFSC	STATUS, Z
;math.ppas,1068 :: 		
$03B1	$0AFB			INCF	STACK_11, F
;math.ppas,1069 :: 		
$03B2	$0874			MOVF	STACK_4, W
;math.ppas,1070 :: 		
$03B3	$0278			SUBWF	STACK_8, W
;math.ppas,1071 :: 		
$03B4	$1D03			BTFSS	STATUS, Z
;math.ppas,1072 :: 		
$03B5	$2B75			GOTO	C3232SOK
;math.ppas,1073 :: 		
$03B6	$0875			MOVF	STACK_5, W
;math.ppas,1074 :: 		
$03B7	$0279			SUBWF	STACK_9, W
;math.ppas,1075 :: 		
$03B8	$1D03			BTFSS	STATUS, Z
;math.ppas,1076 :: 		
$03B9	$2B75			GOTO	C3232SOK
;math.ppas,1077 :: 		
$03BA	$0876			MOVF	STACK_6, W
;math.ppas,1078 :: 		
$03BB	$027A			SUBWF	STACK_10, W
;math.ppas,1079 :: 		
$03BC	$1D03			BTFSS	STATUS, Z
;math.ppas,1080 :: 		
$03BD	$2B75			GOTO	C3232SOK
;math.ppas,1081 :: 		
$03BE	$0877			MOVF	STACK_7, W
;math.ppas,1082 :: 		
$03BF	$027B			SUBWF	STACK_11, W
;math.ppas,1083 :: 		
$03C0	$1D03			BTFSS	STATUS, Z
;math.ppas,1084 :: 		
$03C1	$2B75			GOTO	C3232SOK
;math.ppas,1085 :: 		
$03C2	$01FB			CLRF	STACK_11
;math.ppas,1086 :: 		
$03C3	$01FA			CLRF	STACK_10
;math.ppas,1087 :: 		
$03C4	$01F9			CLRF	STACK_9
;math.ppas,1088 :: 		
$03C5	$01F8			CLRF	STACK_8
;math.ppas,1089 :: 		
$03C6	$0AF0			INCF	STACK_0, F
;math.ppas,1090 :: 		
$03C7	$1903			BTFSC	STATUS, Z
;math.ppas,1091 :: 		
$03C8	$0AF1			INCF	STACK_1, F
;math.ppas,1092 :: 		
$03C9	$1903			BTFSC	STATUS, Z
;math.ppas,1093 :: 		
$03CA	$0AF2			INCF	STACK_2, F
;math.ppas,1094 :: 		
$03CB	$1903			BTFSC	STATUS, Z
;math.ppas,1095 :: 		
$03CC	$0AF3			INCF	STACK_3, F
;math.ppas,1096 :: 		
$03CD	$1FF3			BTFSS	STACK_3, 7
;math.ppas,1097 :: 		
$03CE	$2B75			GOTO	C3232SOK
;math.ppas,1098 :: 		
$03CF	$01A0			CLRF	MATH___MATH_TEMPB
;math.ppas,1099 :: 		
$03D0	$1620			BSF	MATH___MATH_TEMPB, 4
;math.ppas,1100 :: 		
$03D1	$34FF			RETLW	0XFF
;math.ppas,1101 :: 		
$03D2	$	END_ALL:
;math.ppas,1102 :: 		
$03D2	$01A0			CLRF	MATH___MATH_TEMPB
;math.ppas,1103 :: 		
$03D3	$1C7C			BTFSS	STACK_12, 0
;math.ppas,1104 :: 		
$03D4	$2BD6			GOTO	AVOID_COMFREM
;math.ppas,1106 :: 		
$03D5	$250D			CALL	_comfrem
;math.ppas,1108 :: 		
$03D6	$	AVOID_COMFREM:
;math.ppas,1109 :: 		
$03D6	$3F00			ADDLW	0X00
;math.ppas,1110 :: 		
$03D7	$	math_L_11:
;math.ppas,1111 :: 		
$03D7	$0008			RETURN
$04FB	$	_usart_write:
;USART_b75.ppas,40 :: 		
;USART_b75.ppas,42 :: 		
$04FB	$	USART_b75_L_14:
$04FB	$1303			BCF	STATUS, RP1
$04FC	$1683			BSF	STATUS, RP0
$04FD	$0818			MOVF	TXSTA, 0
$04FE	$00F1			MOVWF	STACK_1
$04FF	$3000			MOVLW	0
$0500	$18F1			BTFSC	STACK_1, 1
$0501	$3001			MOVLW	1
$0502	$00F1			MOVWF	STACK_1
$0503	$0871			MOVF	STACK_1, 0
$0504	$3A00			XORLW	0
$0505	$1D03			BTFSS	STATUS, Z
$0506	$2D09			GOTO	USART_b75_L_15
;USART_b75.ppas,43 :: 		
$0507	$0000			NOP
$0508	$2CFB			GOTO	USART_b75_L_14
$0509	$	USART_b75_L_15:
;USART_b75.ppas,44 :: 		
$0509	$1283			BCF	STATUS, RP0
$050A	$083B			MOVF	FARG_USART_Write, 0
$050B	$0099			MOVWF	TXREG
$050C	$	USART_b75_L_12:
;USART_b75.ppas,45 :: 		
$050C	$0008			RETURN
$051B	$	_spi_init:
;SPI_b64c7.ppas,49 :: 		
;SPI_b64c7.ppas,53 :: 		
$051B	$1303			BCF	STATUS, RP1
$051C	$1683			BSF	STATUS, RP0
$051D	$1387			BCF	TRISC, 7
$051E	$	SPI_b64c7_L_18:
;SPI_b64c7.ppas,54 :: 		
$051E	$1306			BCF	TRISB, 6
$051F	$	SPI_b64c7_L_20:
;SPI_b64c7.ppas,55 :: 		
$051F	$	SPI_b64c7_L_21:
$051F	$1606			BSF	TRISB, 4
$0520	$	SPI_b64c7_L_22:
;SPI_b64c7.ppas,57 :: 		
$0520	$1283			BCF	STATUS, RP0
$0521	$0194			CLRF	SSPCON, 1
;SPI_b64c7.ppas,58 :: 		
$0522	$3040			MOVLW	64
$0523	$1683			BSF	STATUS, RP0
$0524	$0094			MOVWF	SSPSTAT
;SPI_b64c7.ppas,59 :: 		
$0525	$1283			BCF	STATUS, RP0
$0526	$1694			BSF	SSPCON, 5
$0527	$	SPI_b64c7_L_16:
;SPI_b64c7.ppas,60 :: 		
$0527	$0008			RETURN
$04E8	$	_spi_write:
;SPI_b64c7.ppas,65 :: 		
;SPI_b64c7.ppas,66 :: 		
$04E8	$1303			BCF	STATUS, RP1
$04E9	$1283			BCF	STATUS, RP0
$04EA	$082E			MOVF	FARG_SPI_write, 0
$04EB	$0093			MOVWF	SSPBUF
;SPI_b64c7.ppas,67 :: 		
$04EC	$	SPI_b64c7_L_25:
$04EC	$1683			BSF	STATUS, RP0
$04ED	$0814			MOVF	SSPSTAT, 0
$04EE	$00F1			MOVWF	STACK_1
$04EF	$3001			MOVLW	1
$04F0	$05F1			ANDWF	STACK_1, 1
$04F1	$0871			MOVF	STACK_1, 0
$04F2	$3A00			XORLW	0
$04F3	$1D03			BTFSS	STATUS, Z
$04F4	$2CF7			GOTO	SPI_b64c7_L_26
;SPI_b64c7.ppas,68 :: 		
$04F5	$0000			NOP
$04F6	$2CEC			GOTO	SPI_b64c7_L_25
$04F7	$	SPI_b64c7_L_26:
;SPI_b64c7.ppas,69 :: 		
$04F7	$1283			BCF	STATUS, RP0
$04F8	$0813			MOVF	SSPBUF, 0
$04F9	$00AF			MOVWF	_spi_write_local_temp
$04FA	$	SPI_b64c7_L_23:
;SPI_b64c7.ppas,70 :: 		
$04FA	$0008			RETURN
$03D8	$	_usart_read_text:
;USART_b75.ppas,78 :: 		
;USART_b75.ppas,79 :: 		
$03D8	$1303			BCF	STATUS, RP1
$03D9	$1283			BCF	STATUS, RP0
$03DA	$01B0			CLRF	_usart_read_text_local_i, 1
;USART_b75.ppas,80 :: 		
$03DB	$01B1			CLRF	_usart_read_text_local_j, 1
;USART_b75.ppas,81 :: 		
$03DC	$01B4			CLRF	_usart_read_text_local_lasti, 1
;USART_b75.ppas,82 :: 		
$03DD	$082F			MOVF	FARG_Usart_Read_Text+1, 0
$03DE	$0084			MOVWF	FSR
$03DF	$0800			MOVF	INDF, 0
$03E0	$00B3			MOVWF	_usart_read_text_local_data2
;USART_b75.ppas,83 :: 		
$03E1	$	USART_b75_L_29:
;USART_b75.ppas,85 :: 		
$03E1	$2528			CALL	_usart_data_ready
$03E2	$0870			MOVF	STACK_0, 0
$03E3	$3A00			XORLW	0
$03E4	$1903			BTFSC	STATUS, Z
$03E5	$2C11			GOTO	USART_b75_L_34
$03E6	$	USART_b75_L_33:
;USART_b75.ppas,87 :: 		
$03E6	$24D5			CALL	_usart_read
$03E7	$0870			MOVF	STACK_0, 0
$03E8	$00B2			MOVWF	_usart_read_text_local_data
;USART_b75.ppas,88 :: 		
$03E9	$0830			MOVF	_usart_read_text_local_i, 0
$03EA	$072E			ADDWF	FARG_Usart_Read_Text, 0
$03EB	$00F1			MOVWF	STACK_1
$03EC	$0871			MOVF	STACK_1, 0
$03ED	$0084			MOVWF	FSR
$03EE	$0871			MOVF	STACK_1, 0
$03EF	$0084			MOVWF	FSR
$03F0	$0870			MOVF	STACK_0, 0
$03F1	$0080			MOVWF	INDF
;USART_b75.ppas,89 :: 		
$03F2	$0832			MOVF	_usart_read_text_local_data, 0
$03F3	$0633			XORWF	_usart_read_text_local_data2, 0
$03F4	$1D03			BTFSS	STATUS, Z
$03F5	$2BFB			GOTO	USART_b75_L_37
$03F6	$	USART_b75_L_36:
;USART_b75.ppas,91 :: 		
$03F6	$0831			MOVF	_usart_read_text_local_j, 0
$03F7	$0230			SUBWF	_usart_read_text_local_i, 0
$03F8	$00B4			MOVWF	_usart_read_text_local_lasti
;USART_b75.ppas,92 :: 		
$03F9	$0AB1			INCF	_usart_read_text_local_j, 1
;USART_b75.ppas,93 :: 		
$03FA	$2BFD			GOTO	USART_b75_L_38
;USART_b75.ppas,94 :: 		
$03FB	$	USART_b75_L_37:
;USART_b75.ppas,96 :: 		
$03FB	$01B1			CLRF	_usart_read_text_local_j, 1
;USART_b75.ppas,97 :: 		
$03FC	$01B4			CLRF	_usart_read_text_local_lasti, 1
;USART_b75.ppas,98 :: 		
$03FD	$	USART_b75_L_38:
;USART_b75.ppas,100 :: 		
$03FD	$0831			MOVF	_usart_read_text_local_j, 0
$03FE	$072F			ADDWF	FARG_Usart_Read_Text+1, 0
$03FF	$0084			MOVWF	FSR
$0400	$0800			MOVF	INDF, 0
$0401	$00F1			MOVWF	STACK_1
$0402	$0871			MOVF	STACK_1, 0
$0403	$00B3			MOVWF	_usart_read_text_local_data2
;USART_b75.ppas,102 :: 		
$0404	$0871			MOVF	STACK_1, 0
$0405	$3A00			XORLW	0
$0406	$1D03			BTFSS	STATUS, Z
$0407	$2C09			GOTO	USART_b75_L_40
$0408	$	USART_b75_L_39:
;USART_b75.ppas,103 :: 		
$0408	$2C12			GOTO	USART_b75_L_30
$0409	$	USART_b75_L_40:
$0409	$	USART_b75_L_41:
;USART_b75.ppas,105 :: 		
$0409	$0AB0			INCF	_usart_read_text_local_i, 1
;USART_b75.ppas,106 :: 		
$040A	$0830			MOVF	_usart_read_text_local_i, 0
$040B	$3C14			SUBLW	20
$040C	$1803			BTFSC	STATUS, C
$040D	$2C11			GOTO	USART_b75_L_43
$040E	$	USART_b75_L_42:
;USART_b75.ppas,108 :: 		
$040E	$3013			MOVLW	19
$040F	$00B4			MOVWF	_usart_read_text_local_lasti
;USART_b75.ppas,109 :: 		
$0410	$2C12			GOTO	USART_b75_L_30
;USART_b75.ppas,110 :: 		
$0411	$	USART_b75_L_43:
$0411	$	USART_b75_L_44:
;USART_b75.ppas,111 :: 		
$0411	$	USART_b75_L_34:
$0411	$	USART_b75_L_35:
;USART_b75.ppas,112 :: 		
$0411	$2BE1			GOTO	USART_b75_L_29
$0412	$	USART_b75_L_30:
;USART_b75.ppas,113 :: 		
$0412	$0834			MOVF	_usart_read_text_local_lasti, 0
$0413	$072E			ADDWF	FARG_Usart_Read_Text, 0
$0414	$00F0			MOVWF	STACK_0
$0415	$0870			MOVF	STACK_0, 0
$0416	$0084			MOVWF	FSR
$0417	$0870			MOVF	STACK_0, 0
$0418	$0084			MOVWF	FSR
$0419	$0180			CLRF	INDF, 1
$041A	$	USART_b75_L_27:
;USART_b75.ppas,114 :: 		
$041A	$0008			RETURN
$027C	$	_strtoint:
;conv.ppas,343 :: 		
;conv.ppas,345 :: 		
$027C	$1303			BCF	STATUS, RP1
$027D	$1283			BCF	STATUS, RP0
$027E	$01AF			CLRF	_strtoint_local_result
$027F	$01B0			CLRF	_strtoint_local_result+1
;conv.ppas,346 :: 		
$0280	$3010			MOVLW	16
$0281	$00B3			MOVWF	_strtoint_local_ep
$0282	$3027			MOVLW	39
$0283	$00B4			MOVWF	_strtoint_local_ep+1
;conv.ppas,347 :: 		
$0284	$01B1			CLRF	_strtoint_local_i
$0285	$01B2			CLRF	_strtoint_local_i+1
;conv.ppas,348 :: 		
$0286	$01B7			CLRF	_strtoint_local_tmp
$0287	$01B8			CLRF	_strtoint_local_tmp+1
$0288	$01B9			CLRF	_strtoint_local_tmp+2
$0289	$01BA			CLRF	_strtoint_local_tmp+3
;conv.ppas,349 :: 		
$028A	$01B5			CLRF	_strtoint_local_negative
$028B	$01B6			CLRF	_strtoint_local_negative+1
;conv.ppas,353 :: 		
$028C	$	conv_L_172:
$028C	$0831			MOVF	_strtoint_local_i, 0
$028D	$072E			ADDWF	FARG_StrToInt, 0
$028E	$0084			MOVWF	FSR
$028F	$0800			MOVF	INDF, 0
$0290	$00F4			MOVWF	STACK_4
$0291	$0874			MOVF	STACK_4, 0
$0292	$3A00			XORLW	0
$0293	$1903			BTFSC	STATUS, Z
$0294	$2AF8			GOTO	conv_L_173
;conv.ppas,355 :: 		
$0295	$0831			MOVF	_strtoint_local_i, 0
$0296	$072E			ADDWF	FARG_StrToInt, 0
$0297	$0084			MOVWF	FSR
$0298	$0800			MOVF	INDF, 0
$0299	$00F4			MOVWF	STACK_4
$029A	$0874			MOVF	STACK_4, 0
$029B	$3A2D			XORLW	45
$029C	$1D03			BTFSS	STATUS, Z
$029D	$2AA5			GOTO	conv_L_177
$029E	$	conv_L_176:
;conv.ppas,357 :: 		
$029E	$30FF			MOVLW	255
$029F	$00B5			MOVWF	_strtoint_local_negative
$02A0	$01B6			CLRF	_strtoint_local_negative+1
;conv.ppas,358 :: 		
$02A1	$0AB1			INCF	_strtoint_local_i, 1
$02A2	$1903			BTFSC	STATUS, Z
$02A3	$0AB2			INCF	_strtoint_local_i+1, 1
;conv.ppas,359 :: 		
$02A4	$2A8C			GOTO	conv_L_172
;conv.ppas,360 :: 		
$02A5	$	conv_L_177:
$02A5	$	conv_L_178:
;conv.ppas,361 :: 		
$02A5	$0831			MOVF	_strtoint_local_i, 0
$02A6	$072E			ADDWF	FARG_StrToInt, 0
$02A7	$0084			MOVWF	FSR
$02A8	$0800			MOVF	INDF, 0
$02A9	$00F4			MOVWF	STACK_4
$02AA	$0874			MOVF	STACK_4, 0
$02AB	$3A20			XORLW	32
$02AC	$1903			BTFSC	STATUS, Z
$02AD	$2AE8			GOTO	conv_L_180
$02AE	$	conv_L_179:
;conv.ppas,362 :: 		
$02AE	$0831			MOVF	_strtoint_local_i, 0
$02AF	$072E			ADDWF	FARG_StrToInt, 0
$02B0	$0084			MOVWF	FSR
$02B1	$0800			MOVF	INDF, 0
$02B2	$00F0			MOVWF	STACK_0
$02B3	$3030			MOVLW	48
$02B4	$00F8			MOVWF	STACK_8
$02B5	$01F9			CLRF	STACK_8+1
$02B6	$01FA			CLRF	STACK_8+2
$02B7	$01FB			CLRF	STACK_8+3
$02B8	$0870			MOVF	STACK_0, 0
$02B9	$00F4			MOVWF	STACK_4
$02BA	$01F5			CLRF	STACK_4+1
$02BB	$01F6			CLRF	STACK_4+2
$02BC	$01F7			CLRF	STACK_4+3
$02BD	$0874			MOVF	STACK_4, 0
$02BE	$00F0			MOVWF	STACK_0
$02BF	$0875			MOVF	STACK_4+1, 0
$02C0	$00F1			MOVWF	STACK_0+1
$02C1	$0876			MOVF	STACK_4+2, 0
$02C2	$00F2			MOVWF	STACK_0+2
$02C3	$0877			MOVF	STACK_4+3, 0
$02C4	$00F3			MOVWF	STACK_0+3
$02C5	$0878			MOVF	STACK_8, 0
$02C6	$02F0			SUBWF	STACK_0, 1
$02C7	$0879			MOVF	STACK_8+1, 0
$02C8	$1C03			BTFSS	STATUS, C
$02C9	$0F79			INCFSZ	STACK_8+1, 0
$02CA	$02F1			SUBWF	STACK_0+1, 1
$02CB	$087A			MOVF	STACK_8+2, 0
$02CC	$1C03			BTFSS	STATUS, C
$02CD	$0F7A			INCFSZ	STACK_8+2, 0
$02CE	$02F2			SUBWF	STACK_0+2, 1
$02CF	$087B			MOVF	STACK_8+3, 0
$02D0	$1C03			BTFSS	STATUS, C
$02D1	$0F7B			INCFSZ	STACK_8+3, 0
$02D2	$02F3			SUBWF	STACK_0+3, 1
$02D3	$0833			MOVF	_strtoint_local_ep, 0
$02D4	$00F4			MOVWF	STACK_4
$02D5	$0834			MOVF	_strtoint_local_ep+1, 0
$02D6	$00F5			MOVWF	STACK_4+1
$02D7	$01F6			CLRF	STACK_4+2
$02D8	$01F7			CLRF	STACK_4+3
$02D9	$241B			CALL	_mul_32x32_s
$02DA	$0870			MOVF	STACK_0, 0
$02DB	$07B7			ADDWF	_strtoint_local_tmp, 1
$02DC	$0871			MOVF	STACK_0+1, 0
$02DD	$1803			BTFSC	STATUS, C
$02DE	$0F71			INCFSZ	STACK_0+1, 0
$02DF	$07B8			ADDWF	_strtoint_local_tmp+1, 1
$02E0	$0872			MOVF	STACK_0+2, 0
$02E1	$1803			BTFSC	STATUS, C
$02E2	$0F72			INCFSZ	STACK_0+2, 0
$02E3	$07B9			ADDWF	_strtoint_local_tmp+2, 1
$02E4	$0873			MOVF	STACK_0+3, 0
$02E5	$1803			BTFSC	STATUS, C
$02E6	$0F73			INCFSZ	STACK_0+3, 0
$02E7	$07BA			ADDWF	_strtoint_local_tmp+3, 1
$02E8	$	conv_L_180:
$02E8	$	conv_L_181:
;conv.ppas,363 :: 		
$02E8	$300A			MOVLW	10
$02E9	$00F4			MOVWF	STACK_4
$02EA	$01F5			CLRF	STACK_4+1
$02EB	$0833			MOVF	_strtoint_local_ep, 0
$02EC	$00F0			MOVWF	STACK_0
$02ED	$0834			MOVF	_strtoint_local_ep+1, 0
$02EE	$00F1			MOVWF	STACK_0+1
$02EF	$248D			CALL	_div_16x16_u
$02F0	$0870			MOVF	STACK_0, 0
$02F1	$00B3			MOVWF	_strtoint_local_ep
$02F2	$0871			MOVF	STACK_0+1, 0
$02F3	$00B4			MOVWF	_strtoint_local_ep+1
;conv.ppas,365 :: 		
$02F4	$0AB1			INCF	_strtoint_local_i, 1
$02F5	$1903			BTFSC	STATUS, Z
$02F6	$0AB2			INCF	_strtoint_local_i+1, 1
;conv.ppas,366 :: 		
$02F7	$2A8C			GOTO	conv_L_172
$02F8	$	conv_L_173:
;conv.ppas,370 :: 		
$02F8	$0835			MOVF	_strtoint_local_negative, 0
$02F9	$0436			IORWF	_strtoint_local_negative+1, 0
$02FA	$1903			BTFSC	STATUS, Z
$02FB	$2B00			GOTO	conv_L_183
$02FC	$	conv_L_182:
$02FC	$3006			MOVLW	6
$02FD	$00B3			MOVWF	_strtoint_local_ep
$02FE	$01B4			CLRF	_strtoint_local_ep+1
$02FF	$2B03			GOTO	conv_L_184
;conv.ppas,371 :: 		
$0300	$	conv_L_183:
$0300	$3005			MOVLW	5
$0301	$00B3			MOVWF	_strtoint_local_ep
$0302	$01B4			CLRF	_strtoint_local_ep+1
$0303	$	conv_L_184:
;conv.ppas,373 :: 		
$0303	$	conv_L_186:
$0303	$0832			MOVF	_strtoint_local_i+1, 0
$0304	$0634			XORWF	_strtoint_local_ep+1, 0
$0305	$1D03			BTFSS	STATUS, Z
$0306	$2B09			GOTO	L_StrToInt_20
$0307	$0833			MOVF	_strtoint_local_ep, 0
$0308	$0631			XORWF	_strtoint_local_i, 0
$0309	$	L_StrToInt_20:
$0309	$1903			BTFSC	STATUS, Z
$030A	$2B25			GOTO	conv_L_187
;conv.ppas,375 :: 		
$030B	$300A			MOVLW	10
$030C	$00F4			MOVWF	STACK_4
$030D	$01F5			CLRF	STACK_4+1
$030E	$01F6			CLRF	STACK_4+2
$030F	$01F7			CLRF	STACK_4+3
$0310	$0837			MOVF	_strtoint_local_tmp, 0
$0311	$00F0			MOVWF	STACK_0
$0312	$0838			MOVF	_strtoint_local_tmp+1, 0
$0313	$00F1			MOVWF	STACK_0+1
$0314	$0839			MOVF	_strtoint_local_tmp+2, 0
$0315	$00F2			MOVWF	STACK_0+2
$0316	$083A			MOVF	_strtoint_local_tmp+3, 0
$0317	$00F3			MOVWF	STACK_0+3
$0318	$233E			CALL	_div_32x32_s
$0319	$0870			MOVF	STACK_0, 0
$031A	$00B7			MOVWF	_strtoint_local_tmp
$031B	$0871			MOVF	STACK_0+1, 0
$031C	$00B8			MOVWF	_strtoint_local_tmp+1
$031D	$0872			MOVF	STACK_0+2, 0
$031E	$00B9			MOVWF	_strtoint_local_tmp+2
$031F	$0873			MOVF	STACK_0+3, 0
$0320	$00BA			MOVWF	_strtoint_local_tmp+3
;conv.ppas,376 :: 		
$0321	$0AB1			INCF	_strtoint_local_i, 1
$0322	$1903			BTFSC	STATUS, Z
$0323	$0AB2			INCF	_strtoint_local_i+1, 1
;conv.ppas,377 :: 		
$0324	$2B03			GOTO	conv_L_186
$0325	$	conv_L_187:
;conv.ppas,380 :: 		
$0325	$0837			MOVF	_strtoint_local_tmp, 0
$0326	$00AF			MOVWF	_strtoint_local_result
$0327	$0838			MOVF	_strtoint_local_tmp+1, 0
$0328	$00B0			MOVWF	_strtoint_local_result+1
;conv.ppas,382 :: 		
$0329	$3000			MOVLW	0
$032A	$0636			XORWF	_strtoint_local_negative+1, 0
$032B	$1D03			BTFSS	STATUS, Z
$032C	$2B2F			GOTO	L_StrToInt_21
$032D	$30FF			MOVLW	255
$032E	$0635			XORWF	_strtoint_local_negative, 0
$032F	$	L_StrToInt_21:
$032F	$1D03			BTFSS	STATUS, Z
$0330	$2B39			GOTO	conv_L_191
$0331	$	conv_L_190:
;conv.ppas,383 :: 		
$0331	$082F			MOVF	_strtoint_local_result, 0
$0332	$3C00			SUBLW	0
$0333	$00AF			MOVWF	_strtoint_local_result
$0334	$0830			MOVF	_strtoint_local_result+1, 0
$0335	$1C03			BTFSS	STATUS, C
$0336	$3F01			ADDLW	1
$0337	$01B0			CLRF	_strtoint_local_result+1
$0338	$02B0			SUBWF	_strtoint_local_result+1, 1
$0339	$	conv_L_191:
$0339	$	conv_L_192:
$0339	$	conv_L_170:
;conv.ppas,384 :: 		
$0339	$082F			MOVF	_strtoint_local_result, 0
$033A	$00F0			MOVWF	STACK_0
$033B	$0830			MOVF	_strtoint_local_result+1, 0
$033C	$00F1			MOVWF	STACK_0+1
$033D	$0008			RETURN
$04AA	$	_usart_write_text:
;USART_b75.ppas,121 :: 		
;USART_b75.ppas,122 :: 		
$04AA	$1303			BCF	STATUS, RP1
$04AB	$1283			BCF	STATUS, RP0
$04AC	$01AF			CLRF	_usart_write_text_local_i, 1
;USART_b75.ppas,123 :: 		
$04AD	$082E			MOVF	FARG_Usart_Write_Text, 0
$04AE	$0084			MOVWF	FSR
$04AF	$0800			MOVF	INDF, 0
$04B0	$00B0			MOVWF	_usart_write_text_local_data
;USART_b75.ppas,124 :: 		
$04B1	$	USART_b75_L_47:
$04B1	$0830			MOVF	_usart_write_text_local_data, 0
$04B2	$3A00			XORLW	0
$04B3	$1903			BTFSC	STATUS, Z
$04B4	$2CBF			GOTO	USART_b75_L_48
;USART_b75.ppas,126 :: 		
$04B5	$0830			MOVF	_usart_write_text_local_data, 0
$04B6	$00BB			MOVWF	FARG_USART_Write
$04B7	$24FB			CALL	_usart_write
;USART_b75.ppas,127 :: 		
$04B8	$0AAF			INCF	_usart_write_text_local_i, 1
;USART_b75.ppas,128 :: 		
$04B9	$082F			MOVF	_usart_write_text_local_i, 0
$04BA	$072E			ADDWF	FARG_Usart_Write_Text, 0
$04BB	$0084			MOVWF	FSR
$04BC	$0800			MOVF	INDF, 0
$04BD	$00B0			MOVWF	_usart_write_text_local_data
;USART_b75.ppas,129 :: 		
$04BE	$2CB1			GOTO	USART_b75_L_47
$04BF	$	USART_b75_L_48:
$04BF	$	USART_b75_L_45:
;USART_b75.ppas,130 :: 		
$04BF	$0008			RETURN
$04C0	$	_usart_init:
;USART_b75.ppas,22 :: 		
;USART_b75.ppas,24 :: 		
$04C0	$	USART_b75_L_1:
$04C0	$1303			BCF	STATUS, RP1
$04C1	$1683			BSF	STATUS, RP0
$04C2	$1698			BSF	TXSTA, 5
$04C3	$	USART_b75_L_2:
;USART_b75.ppas,25 :: 		
$04C3	$3090			MOVLW	144
$04C4	$1283			BCF	STATUS, RP0
$04C5	$0098			MOVWF	RCSTA
;USART_b75.ppas,31 :: 		
$04C6	$	USART_b75_L_3:
$04C6	$1683			BSF	STATUS, RP0
$04C7	$1686			BSF	TRISB, 5
$04C8	$	USART_b75_L_4:
;USART_b75.ppas,32 :: 		
$04C8	$	USART_b75_L_5:
$04C8	$1786			BSF	TRISB, 7
$04C9	$	USART_b75_L_6:
;USART_b75.ppas,35 :: 		
$04C9	$	USART_b75_L_8:
$04C9	$1283			BCF	STATUS, RP0
$04CA	$080C			MOVF	PIR1, 0
$04CB	$00F1			MOVWF	STACK_1
$04CC	$3000			MOVLW	0
$04CD	$1AF1			BTFSC	STACK_1, 5
$04CE	$3001			MOVLW	1
$04CF	$00F1			MOVWF	STACK_1
$04D0	$0871			MOVF	STACK_1, 0
$04D1	$3A01			XORLW	1
$04D2	$1903			BTFSC	STATUS, Z
$04D3	$2CC9			GOTO	USART_b75_L_8
;USART_b75.ppas,36 :: 		
$04D4	$	USART_b75_L_9:
$04D4	$	USART_b75_L_0:
;USART_b75.ppas,37 :: 		
$04D4	$0008			RETURN
$0004	$	_main:
;motores.pbas,7 :: 		main:
$0004	$	_main_main:
;motores.pbas,8 :: 		TRISA=%11111111
$0004	$30FF			MOVLW	255
$0005	$1303			BCF	STATUS, RP1
$0006	$1683			BSF	STATUS, RP0
$0007	$0085			MOVWF	TRISA
;motores.pbas,9 :: 		TRISB=%00111111
$0008	$303F			MOVLW	63
$0009	$0086			MOVWF	TRISB
;motores.pbas,10 :: 		TRISC=%00000000
$000A	$0187			CLRF	TRISC, 1
;motores.pbas,11 :: 		INTCON=%00000000
$000B	$018B			CLRF	INTCON, 1
;motores.pbas,12 :: 		ANSEL=%00000000
$000C	$1703			BSF	STATUS, RP1
$000D	$1283			BCF	STATUS, RP0
$000E	$019E			CLRF	ANSEL, 1
;motores.pbas,13 :: 		ANSELH=%00000000
$000F	$019F			CLRF	ANSELH, 1
;motores.pbas,14 :: 		portA=0
$0010	$1303			BCF	STATUS, RP1
$0011	$0185			CLRF	PORTA, 1
;motores.pbas,15 :: 		portB=0
$0012	$0186			CLRF	PORTB, 1
;motores.pbas,16 :: 		portC=0
$0013	$0187			CLRF	PORTC, 1
;motores.pbas,18 :: 		USART_INIT(9600)
$0014	$3019			MOVLW	25
$0015	$1683			BSF	STATUS, RP0
$0016	$0099			MOVWF	SPBRG
$0017	$1518			BSF	TXSTA, BRGH
$0018	$24C0			CALL	_usart_init
;motores.pbas,20 :: 		portc.0 = 1 portc.1 = 1 portc.2 = 1
$0019	$	motores_L_1:
$0019	$1407			BSF	PORTC, 0
$001A	$	motores_L_2:
$001A	$	motores_L_3:
$001A	$1487			BSF	PORTC, 1
$001B	$	motores_L_4:
$001B	$	motores_L_5:
$001B	$1507			BSF	PORTC, 2
$001C	$	motores_L_6:
;motores.pbas,22 :: 		SPI_INIT
$001C	$251B			CALL	_spi_init
;motores.pbas,24 :: 		clearbit(portc,0) Spi_Write(17) Spi_Write(0) setbit(portc,0)
$001D	$1007			BCF	PORTC, 0
$001E	$3011			MOVLW	17
$001F	$00AE			MOVWF	FARG_SPI_write
$0020	$24E8			CALL	_spi_write
$0021	$01AE			CLRF	FARG_SPI_write, 1
$0022	$24E8			CALL	_spi_write
$0023	$1407			BSF	PORTC, 0
;motores.pbas,25 :: 		clearbit(portc,1) Spi_Write(17) Spi_Write(0) setbit(portc,1)
$0024	$1087			BCF	PORTC, 1
$0025	$3011			MOVLW	17
$0026	$00AE			MOVWF	FARG_SPI_write
$0027	$24E8			CALL	_spi_write
$0028	$01AE			CLRF	FARG_SPI_write, 1
$0029	$24E8			CALL	_spi_write
$002A	$1487			BSF	PORTC, 1
;motores.pbas,26 :: 		clearbit(portc,2) Spi_Write(17) Spi_Write(0) setbit(portc,2)
$002B	$1107			BCF	PORTC, 2
$002C	$3011			MOVLW	17
$002D	$00AE			MOVWF	FARG_SPI_write
$002E	$24E8			CALL	_spi_write
$002F	$01AE			CLRF	FARG_SPI_write, 1
$0030	$24E8			CALL	_spi_write
$0031	$1507			BSF	PORTC, 2
;motores.pbas,28 :: 		executa:
$0032	$	_main_executa:
;motores.pbas,29 :: 		if Usart_Data_Ready() > 0 then
$0032	$2528			CALL	_usart_data_ready
$0033	$0870			MOVF	STACK_0, 0
$0034	$3C00			SUBLW	0
$0035	$1803			BTFSC	STATUS, C
$0036	$294C			GOTO	motores_L_8
$0037	$	motores_L_7:
;motores.pbas,30 :: 		Usart_Read_Text(recebe,"/")
$0037	$3021			MOVLW	_recebe
$0038	$00AE			MOVWF	FARG_Usart_Read_Text
$0039	$302F			MOVLW	47
$003A	$00AC			MOVWF	?main_Local_Text+0
$003B	$01AD			CLRF	?main_Local_Text+1
$003C	$302C			MOVLW	?main_Local_Text
$003D	$00AF			MOVWF	FARG_Usart_Read_Text+1
$003E	$23D8			CALL	_usart_read_text
;motores.pbas,31 :: 		valor = StrToInt(recebe)
$003F	$3021			MOVLW	_recebe
$0040	$00AE			MOVWF	FARG_StrToInt
$0041	$227C			CALL	_strtoint
$0042	$0870			MOVF	STACK_0, 0
$0043	$00A8			MOVWF	_valor
$0044	$0871			MOVF	STACK_0+1, 0
$0045	$00A9			MOVWF	_valor+1
;motores.pbas,33 :: 		if (valor > 999) and (valor < 4256) then
$0046	$3080			MOVLW	128
$0047	$3A03			XORLW	3
$0048	$00F3			MOVWF	STACK_3
$0049	$3080			MOVLW	128
$004A	$0671			XORWF	STACK_0+1, 0
$004B	$0273			SUBWF	STACK_3, 0
$004C	$1D03			BTFSS	STATUS, Z
$004D	$2850			GOTO	L_main_0
$004E	$0870			MOVF	STACK_0, 0
$004F	$3CE7			SUBLW	231
$0050	$	L_main_0:
$0050	$30FF			MOVLW	255
$0051	$1803			BTFSC	STATUS, C
$0052	$3000			MOVLW	0
$0053	$00F3			MOVWF	STACK_3
$0054	$3080			MOVLW	128
$0055	$0671			XORWF	STACK_0+1, 0
$0056	$00F2			MOVWF	STACK_2
$0057	$3080			MOVLW	128
$0058	$3A10			XORLW	16
$0059	$0272			SUBWF	STACK_2, 0
$005A	$1D03			BTFSS	STATUS, Z
$005B	$285E			GOTO	L_main_1
$005C	$30A0			MOVLW	160
$005D	$0270			SUBWF	STACK_0, 0
$005E	$	L_main_1:
$005E	$30FF			MOVLW	255
$005F	$1803			BTFSC	STATUS, C
$0060	$3000			MOVLW	0
$0061	$00F2			MOVWF	STACK_2
$0062	$0872			MOVF	STACK_2, 0
$0063	$0573			ANDWF	STACK_3, 0
$0064	$00F0			MOVWF	STACK_0
$0065	$1903			BTFSC	STATUS, Z
$0066	$294C			GOTO	motores_L_11
$0067	$	motores_L_10:
;motores.pbas,35 :: 		if (valor >= 1000) And (valor < 1256) then
$0067	$3080			MOVLW	128
$0068	$0629			XORWF	_valor+1, 0
$0069	$00F2			MOVWF	STACK_2
$006A	$3080			MOVLW	128
$006B	$3A03			XORLW	3
$006C	$0272			SUBWF	STACK_2, 0
$006D	$1D03			BTFSS	STATUS, Z
$006E	$2871			GOTO	L_main_2
$006F	$30E8			MOVLW	232
$0070	$0228			SUBWF	_valor, 0
$0071	$	L_main_2:
$0071	$30FF			MOVLW	255
$0072	$1C03			BTFSS	STATUS, C
$0073	$3000			MOVLW	0
$0074	$00F2			MOVWF	STACK_2
$0075	$3080			MOVLW	128
$0076	$0629			XORWF	_valor+1, 0
$0077	$00F0			MOVWF	STACK_0
$0078	$3080			MOVLW	128
$0079	$3A04			XORLW	4
$007A	$0270			SUBWF	STACK_0, 0
$007B	$1D03			BTFSS	STATUS, Z
$007C	$287F			GOTO	L_main_3
$007D	$30E8			MOVLW	232
$007E	$0228			SUBWF	_valor, 0
$007F	$	L_main_3:
$007F	$30FF			MOVLW	255
$0080	$1803			BTFSC	STATUS, C
$0081	$3000			MOVLW	0
$0082	$00F0			MOVWF	STACK_0
$0083	$0872			MOVF	STACK_2, 0
$0084	$05F0			ANDWF	STACK_0, 1
$0085	$1903			BTFSC	STATUS, Z
$0086	$2890			GOTO	motores_L_14
$0087	$	motores_L_13:
;motores.pbas,36 :: 		mcp = 1
$0087	$3001			MOVLW	1
$0088	$00AA			MOVWF	_mcp
$0089	$01AB			CLRF	_mcp+1
;motores.pbas,37 :: 		valor = valor - 1000
$008A	$30E8			MOVLW	232
$008B	$02A8			SUBWF	_valor, 1
$008C	$1C03			BTFSS	STATUS, C
$008D	$03A9			DECF	_valor+1, 1
$008E	$3003			MOVLW	3
$008F	$02A9			SUBWF	_valor+1, 1
$0090	$	motores_L_14:
;motores.pbas,38 :: 		end if
$0090	$	motores_L_15:
;motores.pbas,39 :: 		if (valor >= 2000) And (valor < 2256) then
$0090	$3080			MOVLW	128
$0091	$0629			XORWF	_valor+1, 0
$0092	$00F2			MOVWF	STACK_2
$0093	$3080			MOVLW	128
$0094	$3A07			XORLW	7
$0095	$0272			SUBWF	STACK_2, 0
$0096	$1D03			BTFSS	STATUS, Z
$0097	$289A			GOTO	L_main_4
$0098	$30D0			MOVLW	208
$0099	$0228			SUBWF	_valor, 0
$009A	$	L_main_4:
$009A	$30FF			MOVLW	255
$009B	$1C03			BTFSS	STATUS, C
$009C	$3000			MOVLW	0
$009D	$00F2			MOVWF	STACK_2
$009E	$3080			MOVLW	128
$009F	$0629			XORWF	_valor+1, 0
$00A0	$00F0			MOVWF	STACK_0
$00A1	$3080			MOVLW	128
$00A2	$3A08			XORLW	8
$00A3	$0270			SUBWF	STACK_0, 0
$00A4	$1D03			BTFSS	STATUS, Z
$00A5	$28A8			GOTO	L_main_5
$00A6	$30D0			MOVLW	208
$00A7	$0228			SUBWF	_valor, 0
$00A8	$	L_main_5:
$00A8	$30FF			MOVLW	255
$00A9	$1803			BTFSC	STATUS, C
$00AA	$3000			MOVLW	0
$00AB	$00F0			MOVWF	STACK_0
$00AC	$0872			MOVF	STACK_2, 0
$00AD	$05F0			ANDWF	STACK_0, 1
$00AE	$1903			BTFSC	STATUS, Z
$00AF	$28B9			GOTO	motores_L_17
$00B0	$	motores_L_16:
;motores.pbas,40 :: 		mcp = 2
$00B0	$3002			MOVLW	2
$00B1	$00AA			MOVWF	_mcp
$00B2	$01AB			CLRF	_mcp+1
;motores.pbas,41 :: 		valor = valor - 2000
$00B3	$30D0			MOVLW	208
$00B4	$02A8			SUBWF	_valor, 1
$00B5	$1C03			BTFSS	STATUS, C
$00B6	$03A9			DECF	_valor+1, 1
$00B7	$3007			MOVLW	7
$00B8	$02A9			SUBWF	_valor+1, 1
$00B9	$	motores_L_17:
;motores.pbas,42 :: 		end if
$00B9	$	motores_L_18:
;motores.pbas,43 :: 		if (valor >= 3000) And (valor < 3256) then
$00B9	$3080			MOVLW	128
$00BA	$0629			XORWF	_valor+1, 0
$00BB	$00F2			MOVWF	STACK_2
$00BC	$3080			MOVLW	128
$00BD	$3A0B			XORLW	11
$00BE	$0272			SUBWF	STACK_2, 0
$00BF	$1D03			BTFSS	STATUS, Z
$00C0	$28C3			GOTO	L_main_6
$00C1	$30B8			MOVLW	184
$00C2	$0228			SUBWF	_valor, 0
$00C3	$	L_main_6:
$00C3	$30FF			MOVLW	255
$00C4	$1C03			BTFSS	STATUS, C
$00C5	$3000			MOVLW	0
$00C6	$00F2			MOVWF	STACK_2
$00C7	$3080			MOVLW	128
$00C8	$0629			XORWF	_valor+1, 0
$00C9	$00F0			MOVWF	STACK_0
$00CA	$3080			MOVLW	128
$00CB	$3A0C			XORLW	12
$00CC	$0270			SUBWF	STACK_0, 0
$00CD	$1D03			BTFSS	STATUS, Z
$00CE	$28D1			GOTO	L_main_7
$00CF	$30B8			MOVLW	184
$00D0	$0228			SUBWF	_valor, 0
$00D1	$	L_main_7:
$00D1	$30FF			MOVLW	255
$00D2	$1803			BTFSC	STATUS, C
$00D3	$3000			MOVLW	0
$00D4	$00F0			MOVWF	STACK_0
$00D5	$0872			MOVF	STACK_2, 0
$00D6	$05F0			ANDWF	STACK_0, 1
$00D7	$1903			BTFSC	STATUS, Z
$00D8	$28E2			GOTO	motores_L_20
$00D9	$	motores_L_19:
;motores.pbas,44 :: 		mcp = 3
$00D9	$3003			MOVLW	3
$00DA	$00AA			MOVWF	_mcp
$00DB	$01AB			CLRF	_mcp+1
;motores.pbas,45 :: 		valor = valor - 3000
$00DC	$30B8			MOVLW	184
$00DD	$02A8			SUBWF	_valor, 1
$00DE	$1C03			BTFSS	STATUS, C
$00DF	$03A9			DECF	_valor+1, 1
$00E0	$300B			MOVLW	11
$00E1	$02A9			SUBWF	_valor+1, 1
$00E2	$	motores_L_20:
;motores.pbas,46 :: 		end if
$00E2	$	motores_L_21:
;motores.pbas,47 :: 		if (valor >= 4000) And (valor < 4256) then
$00E2	$3080			MOVLW	128
$00E3	$0629			XORWF	_valor+1, 0
$00E4	$00F2			MOVWF	STACK_2
$00E5	$3080			MOVLW	128
$00E6	$3A0F			XORLW	15
$00E7	$0272			SUBWF	STACK_2, 0
$00E8	$1D03			BTFSS	STATUS, Z
$00E9	$28EC			GOTO	L_main_8
$00EA	$30A0			MOVLW	160
$00EB	$0228			SUBWF	_valor, 0
$00EC	$	L_main_8:
$00EC	$30FF			MOVLW	255
$00ED	$1C03			BTFSS	STATUS, C
$00EE	$3000			MOVLW	0
$00EF	$00F2			MOVWF	STACK_2
$00F0	$3080			MOVLW	128
$00F1	$0629			XORWF	_valor+1, 0
$00F2	$00F0			MOVWF	STACK_0
$00F3	$3080			MOVLW	128
$00F4	$3A10			XORLW	16
$00F5	$0270			SUBWF	STACK_0, 0
$00F6	$1D03			BTFSS	STATUS, Z
$00F7	$28FA			GOTO	L_main_9
$00F8	$30A0			MOVLW	160
$00F9	$0228			SUBWF	_valor, 0
$00FA	$	L_main_9:
$00FA	$30FF			MOVLW	255
$00FB	$1803			BTFSC	STATUS, C
$00FC	$3000			MOVLW	0
$00FD	$00F0			MOVWF	STACK_0
$00FE	$0872			MOVF	STACK_2, 0
$00FF	$05F0			ANDWF	STACK_0, 1
$0100	$1903			BTFSC	STATUS, Z
$0101	$290B			GOTO	motores_L_23
$0102	$	motores_L_22:
;motores.pbas,48 :: 		mcp = 4
$0102	$3004			MOVLW	4
$0103	$00AA			MOVWF	_mcp
$0104	$01AB			CLRF	_mcp+1
;motores.pbas,49 :: 		valor = valor - 4000
$0105	$30A0			MOVLW	160
$0106	$02A8			SUBWF	_valor, 1
$0107	$1C03			BTFSS	STATUS, C
$0108	$03A9			DECF	_valor+1, 1
$0109	$300F			MOVLW	15
$010A	$02A9			SUBWF	_valor+1, 1
$010B	$	motores_L_23:
;motores.pbas,50 :: 		end if
$010B	$	motores_L_24:
;motores.pbas,52 :: 		if mcp = 1 then
$010B	$3000			MOVLW	0
$010C	$062B			XORWF	_mcp+1, 0
$010D	$1D03			BTFSS	STATUS, Z
$010E	$2911			GOTO	L_main_10
$010F	$3001			MOVLW	1
$0110	$062A			XORWF	_mcp, 0
$0111	$	L_main_10:
$0111	$1D03			BTFSS	STATUS, Z
$0112	$2914			GOTO	motores_L_26
$0113	$	motores_L_25:
;motores.pbas,53 :: 		clearbit(portc,0)
$0113	$1007			BCF	PORTC, 0
$0114	$	motores_L_26:
;motores.pbas,54 :: 		end if
$0114	$	motores_L_27:
;motores.pbas,55 :: 		if mcp = 2 then
$0114	$3000			MOVLW	0
$0115	$062B			XORWF	_mcp+1, 0
$0116	$1D03			BTFSS	STATUS, Z
$0117	$291A			GOTO	L_main_11
$0118	$3002			MOVLW	2
$0119	$062A			XORWF	_mcp, 0
$011A	$	L_main_11:
$011A	$1D03			BTFSS	STATUS, Z
$011B	$291D			GOTO	motores_L_29
$011C	$	motores_L_28:
;motores.pbas,56 :: 		clearbit(portc,1)
$011C	$1087			BCF	PORTC, 1
$011D	$	motores_L_29:
;motores.pbas,57 :: 		end if
$011D	$	motores_L_30:
;motores.pbas,58 :: 		if mcp = 3 then
$011D	$3000			MOVLW	0
$011E	$062B			XORWF	_mcp+1, 0
$011F	$1D03			BTFSS	STATUS, Z
$0120	$2923			GOTO	L_main_12
$0121	$3003			MOVLW	3
$0122	$062A			XORWF	_mcp, 0
$0123	$	L_main_12:
$0123	$1D03			BTFSS	STATUS, Z
$0124	$2926			GOTO	motores_L_32
$0125	$	motores_L_31:
;motores.pbas,59 :: 		clearbit(portc,2)
$0125	$1107			BCF	PORTC, 2
$0126	$	motores_L_32:
;motores.pbas,60 :: 		end if
$0126	$	motores_L_33:
;motores.pbas,62 :: 		if mcp = 4 then
$0126	$3000			MOVLW	0
$0127	$062B			XORWF	_mcp+1, 0
$0128	$1D03			BTFSS	STATUS, Z
$0129	$292C			GOTO	L_main_13
$012A	$3004			MOVLW	4
$012B	$062A			XORWF	_mcp, 0
$012C	$	L_main_13:
$012C	$1D03			BTFSS	STATUS, Z
$012D	$2931			GOTO	motores_L_35
$012E	$	motores_L_34:
;motores.pbas,63 :: 		portc.0 = 0
$012E	$1007			BCF	PORTC, 0
$012F	$	motores_L_38:
;motores.pbas,64 :: 		portc.1 = 0
$012F	$1087			BCF	PORTC, 1
$0130	$	motores_L_40:
;motores.pbas,65 :: 		portc.2 = 0
$0130	$1107			BCF	PORTC, 2
$0131	$	motores_L_42:
$0131	$	motores_L_35:
;motores.pbas,66 :: 		end if
$0131	$	motores_L_36:
;motores.pbas,68 :: 		spi_write(17)
$0131	$3011			MOVLW	17
$0132	$00AE			MOVWF	FARG_SPI_write
$0133	$24E8			CALL	_spi_write
;motores.pbas,69 :: 		spi_Write(valor)
$0134	$0828			MOVF	_valor, 0
$0135	$00AE			MOVWF	FARG_SPI_write
$0136	$24E8			CALL	_spi_write
;motores.pbas,71 :: 		portc.0 = 1
$0137	$	motores_L_43:
$0137	$1407			BSF	PORTC, 0
$0138	$	motores_L_44:
;motores.pbas,72 :: 		portc.1 = 1
$0138	$	motores_L_45:
$0138	$1487			BSF	PORTC, 1
$0139	$	motores_L_46:
;motores.pbas,73 :: 		portc.2 = 1
$0139	$	motores_L_47:
$0139	$1507			BSF	PORTC, 2
$013A	$	motores_L_48:
;motores.pbas,75 :: 		delay_ms(10)
$013A	$300D			MOVLW	13
$013B	$00FB			MOVWF	STACK_11
$013C	$30FF			MOVLW	255
$013D	$00FA			MOVWF	STACK_10
$013E	$0BFB			DECFSZ	STACK_11, F
$013F	$2941			GOTO	$+2
$0140	$2944			GOTO	$+4
$0141	$0BFA			DECFSZ	STACK_10, F
$0142	$2941			GOTO	$-1
$0143	$293E			GOTO	$-5
$0144	$30F3			MOVLW	243
$0145	$00FA			MOVWF	STACK_10
$0146	$0BFA			DECFSZ	STACK_10, F
$0147	$2946			GOTO	$-1
$0148	$0000			NOP
;motores.pbas,77 :: 		Usart_Write_Text(recebe)
$0149	$3021			MOVLW	_recebe
$014A	$00AE			MOVWF	FARG_Usart_Write_Text
$014B	$24AA			CALL	_usart_write_text
$014C	$	motores_L_11:
;motores.pbas,79 :: 		end if
$014C	$	motores_L_12:
$014C	$	motores_L_8:
;motores.pbas,81 :: 		end if
$014C	$	motores_L_9:
;motores.pbas,83 :: 		goto executa
$014C	$2832			GOTO	_main_executa
$014D	$294D			GOTO	$
